
/// <reference path="./GLib-2.0.d.ts" />
/// <reference path="./GObject-2.0.d.ts" />

/**
 * Type Definitions for GJS (https://gjs.guide/), generated by [GirGen](https://github.com/aylur/girgen)
 * If you found a bug, create a bug report on [GirGen's Repository](https://github.com/aylur/girgen/issues/new)
 */
declare module "gi://DBusGLib?version=1.0" {
    import type GLib from "gi://GLib?version=2.0"
    import type GObject from "gi://GObject?version=2.0"

    /**
     * Do **not** import this at runtime.
     * This namespace is only exported for module augmentation.
     */
    export namespace GI {
        

        namespace DBusGLib {
            

            namespace Proxy {
                interface SignalSignatures extends GObject.Object.SignalSignatures {
                }

                interface ReadWriteProperties extends GObject.Object.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, GObject.Object.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, GObject.Object.WritableProperties {
                }

                interface ConstructOnlyProperties extends GObject.Object.ConstructOnlyProperties {
                }
            }

            interface Proxy extends GObject.Object {
                readonly $signals: Proxy.SignalSignatures
                readonly $readableProperties: Proxy.ReadableProperties
                readonly $writableProperties: Proxy.WritableProperties
                readonly $constructOnlyProperties: Proxy.ConstructOnlyProperties
            }

            interface ProxyClass extends Omit<GObject.ObjectClass, "new"> {
                readonly $gtype: GObject.GType<Proxy>
                readonly prototype: Proxy

                new (props?: Partial<GObject.ConstructorProps<Proxy>>): Proxy
            }

            interface $Exports {
                
                Proxy: ProxyClass
            }
            

            interface ConnectionStruct {
                readonly $gtype: GObject.GType<Connection>
                new (fields?: {
                }): Connection
            }

            interface Connection {
            }

            interface $Exports {
                Connection: ConnectionStruct
            }
            

            interface MethodInvocationStruct {
                readonly $gtype: GObject.GType<MethodInvocation>
                new (fields?: {
                }): MethodInvocation
            }

            interface MethodInvocation {
            }

            interface $Exports {
                MethodInvocation: MethodInvocationStruct
            }
            

            interface ProxyClassStruct {
                readonly $gtype: GObject.GType<ProxyClass>
                new (fields?: {
                }): ProxyClass
            }

            interface ProxyClass {
            }

            interface $Exports {
                ProxyClass: ProxyClassStruct
            }

            interface $Exports {
                __name__: "DBusGLib"
                __version__: "1.0"
            }
        }

        const DBusGLib: DBusGLib.$Exports
    }

    export default GI.DBusGLib
}