
/// <reference path="./GLib-2.0.d.ts" />
/// <reference path="./GModule-2.0.d.ts" />
/// <reference path="./GObject-2.0.d.ts" />
/// <reference path="./Gio-2.0.d.ts" />
/// <reference path="./freetype2-2.0.d.ts" />
/// <reference path="./HarfBuzz-0.0.d.ts" />
/// <reference path="./cairo-1.0.d.ts" />
/// <reference path="./Pango-1.0.d.ts" />
/// <reference path="./GdkPixbuf-2.0.d.ts" />
/// <reference path="./PangoCairo-1.0.d.ts" />
/// <reference path="./Gdk-4.0.d.ts" />

/**
 * Type Definitions for GJS (https://gjs.guide/), generated by [GirGen](https://github.com/aylur/girgen)
 * If you found a bug, create a bug report on [GirGen's Repository](https://github.com/aylur/girgen/issues/new)
 */
declare module "gi://GdkWayland?version=4.0" {
    import type GLib from "gi://GLib?version=2.0"
    import type GModule from "gi://GModule?version=2.0"
    import type GObject from "gi://GObject?version=2.0"
    import type Gio from "gi://Gio?version=2.0"
    import type freetype2 from "gi://freetype2?version=2.0"
    import type HarfBuzz from "gi://HarfBuzz?version=0.0"
    import type cairo from "gi://cairo?version=1.0"
    import type Pango from "gi://Pango?version=1.0"
    import type GdkPixbuf from "gi://GdkPixbuf?version=2.0"
    import type PangoCairo from "gi://PangoCairo?version=1.0"
    import type Gdk from "gi://Gdk?version=4.0"

    /**
     * Do **not** import this at runtime.
     * This namespace is only exported for module augmentation.
     */
    export namespace GI {
        

        namespace GdkWayland {
            

            namespace WaylandDevice {
                interface SignalSignatures extends Gdk.Device.SignalSignatures {
                }

                interface ReadWriteProperties extends Gdk.Device.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, Gdk.Device.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, Gdk.Device.WritableProperties {
                }

                interface ConstructOnlyProperties extends Gdk.Device.ConstructOnlyProperties {
                }
            }

            interface WaylandDevice extends Gdk.Device {
                readonly $signals: WaylandDevice.SignalSignatures
                readonly $readableProperties: WaylandDevice.ReadableProperties
                readonly $writableProperties: WaylandDevice.WritableProperties
                readonly $constructOnlyProperties: WaylandDevice.ConstructOnlyProperties
                /**
                 * Returns the `/dev/input/event*` path of this device.
                 *
                 * For `GdkDevice`s that possibly coalesce multiple hardware
                 * devices (eg. mouse, keyboard, touch,...), this function
                 * will return %NULL.
                 *
                 * This is most notably implemented for devices of type
                 * %GDK_SOURCE_PEN, %GDK_SOURCE_TABLET_PAD.
                 * @returns the `/dev/input/event*`   path of this device
                 */
                get_node_path(): string | null
                /**
                 * Returns the `xkb_keymap` of a `GdkDevice`.
                 * @since 4.4
                 * @returns a `struct xkb_keymap`
                 */
                get_xkb_keymap(): never | null
            }

            interface WaylandDeviceClass extends Omit<Gdk.DeviceClass, "new"> {
                readonly $gtype: GObject.GType<WaylandDevice>
                readonly prototype: WaylandDevice

                new (props?: Partial<GObject.ConstructorProps<WaylandDevice>>): WaylandDevice
            }

            interface $Exports {
                /**
                 * The Wayland implementation of `GdkDevice`.
                 *
                 * Beyond the regular {@link Gdk.Device} API, the Wayland implementation
                 * provides access to Wayland objects such as the `wl_seat` with
                 * {@link GdkWayland.WaylandDevice.get_wl_seat}, the `wl_keyboard` with
                 * {@link GdkWayland.WaylandDevice.get_wl_keyboard} and the `wl_pointer` with
                 * {@link GdkWayland.WaylandDevice.get_wl_pointer}.
                 */
                WaylandDevice: WaylandDeviceClass
            }
            

            namespace WaylandDisplay {
                interface SignalSignatures extends Gdk.Display.SignalSignatures {
                }

                interface ReadWriteProperties extends Gdk.Display.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, Gdk.Display.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, Gdk.Display.WritableProperties {
                }

                interface ConstructOnlyProperties extends Gdk.Display.ConstructOnlyProperties {
                }
            }

            interface WaylandDisplay extends Gdk.Display {
                readonly $signals: WaylandDisplay.SignalSignatures
                readonly $readableProperties: WaylandDisplay.ReadableProperties
                readonly $writableProperties: WaylandDisplay.WritableProperties
                readonly $constructOnlyProperties: WaylandDisplay.ConstructOnlyProperties
                /**
                 * Retrieves the EGL display connection object for the given GDK display.
                 * @since 4.4
                 * @returns the EGL display
                 */
                get_egl_display(): never | null
                /**
                 * Gets the startup notification ID for a Wayland display, or `NULL`
                 * if no ID has been defined.
                 * @deprecated since 4.10.
                 * @returns the startup notification ID for `display`
                 */
                get_startup_notification_id(): string | null
                /**
                 * Returns true if the interface was found in the display
                 * `wl_registry.global` handler.
                 * @param global global interface to query in the registry
                 * @returns true if the global is offered by the compositor
                 */
                query_registry(global: string): boolean
                /**
                 * Sets the cursor theme for the given `display`.
                 * @deprecated since 4.16 Use the cursor-related properties of   [GtkSettings](../gtk4/class.Settings.html) to set the cursor theme
                 * @param name the new cursor theme
                 * @param size the size to use for cursors
                 */
                set_cursor_theme(name: string, size: number): void
                /**
                 * Sets the startup notification ID for a display.
                 *
                 * This is usually taken from the value of the `DESKTOP_STARTUP_ID`
                 * environment variable, but in some cases (such as the application not
                 * being launched using exec()) it can come from other sources.
                 *
                 * The startup ID is also what is used to signal that the startup is
                 * complete (for example, when opening a window or when calling
                 * {@link Gdk.Display.notify_startup_complete}).
                 * @deprecated since 4.10. Use {@link Gdk.Toplevel.set_startup_id}
                 * @param startup_id the startup notification ID (must be valid utf8)
                 */
                set_startup_notification_id(startup_id: string): void
            }

            interface WaylandDisplayClass extends Omit<Gdk.DisplayClass, "new"> {
                readonly $gtype: GObject.GType<WaylandDisplay>
                readonly prototype: WaylandDisplay

                new (props?: Partial<GObject.ConstructorProps<WaylandDisplay>>): WaylandDisplay
            }

            interface $Exports {
                /**
                 * The Wayland implementation of `GdkDisplay`.
                 *
                 * Beyond the regular {@link Gdk.Display} API, the Wayland implementation
                 * provides access to Wayland objects such as the `wl_display` with
                 * {@link GdkWayland.WaylandDisplay.get_wl_display}, the `wl_compositor` with
                 * {@link GdkWayland.WaylandDisplay.get_wl_compositor}.
                 *
                 * You can find out what Wayland globals are supported by a display
                 * with {@link GdkWayland.WaylandDisplay.query_registry}.
                 */
                WaylandDisplay: WaylandDisplayClass
            }
            

            namespace WaylandGLContext {
                interface SignalSignatures extends Gdk.GLContext.SignalSignatures {
                }

                interface ReadWriteProperties extends Gdk.GLContext.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, Gdk.GLContext.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, Gdk.GLContext.WritableProperties {
                }

                interface ConstructOnlyProperties extends Gdk.GLContext.ConstructOnlyProperties {
                }
            }

            interface WaylandGLContext extends Gdk.GLContext {
                readonly $signals: WaylandGLContext.SignalSignatures
                readonly $readableProperties: WaylandGLContext.ReadableProperties
                readonly $writableProperties: WaylandGLContext.WritableProperties
                readonly $constructOnlyProperties: WaylandGLContext.ConstructOnlyProperties
            }

            interface WaylandGLContextClass extends Omit<Gdk.GLContextClass, "new"> {
                readonly $gtype: GObject.GType<WaylandGLContext>
                readonly prototype: WaylandGLContext

                new (props?: Partial<GObject.ConstructorProps<WaylandGLContext>>): WaylandGLContext
            }

            interface $Exports {
                /**
                 * The Wayland implementation of `GdkGLContext`.
                 */
                WaylandGLContext: WaylandGLContextClass
            }
            

            namespace WaylandMonitor {
                interface SignalSignatures extends Gdk.Monitor.SignalSignatures {
                }

                interface ReadWriteProperties extends Gdk.Monitor.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, Gdk.Monitor.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, Gdk.Monitor.WritableProperties {
                }

                interface ConstructOnlyProperties extends Gdk.Monitor.ConstructOnlyProperties {
                }
            }

            interface WaylandMonitor extends Gdk.Monitor {
                readonly $signals: WaylandMonitor.SignalSignatures
                readonly $readableProperties: WaylandMonitor.ReadableProperties
                readonly $writableProperties: WaylandMonitor.WritableProperties
                readonly $constructOnlyProperties: WaylandMonitor.ConstructOnlyProperties
            }

            interface WaylandMonitorClass extends Omit<Gdk.MonitorClass, "new"> {
                readonly $gtype: GObject.GType<WaylandMonitor>
                readonly prototype: WaylandMonitor

                new (props?: Partial<GObject.ConstructorProps<WaylandMonitor>>): WaylandMonitor
            }

            interface $Exports {
                /**
                 * The Wayland implementation of `GdkMonitor`.
                 *
                 * Beyond the {@link Gdk.Monitor} API, the Wayland implementation
                 * offers access to the Wayland `wl_output` object with
                 * {@link GdkWayland.WaylandMonitor.get_wl_output}.
                 */
                WaylandMonitor: WaylandMonitorClass
            }
            

            namespace WaylandPopup {
                interface SignalSignatures extends WaylandSurface.SignalSignatures, Gdk.Popup.SignalSignatures {
                }

                interface ReadWriteProperties extends WaylandSurface.ReadWriteProperties, Gdk.Popup.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, WaylandSurface.ReadableProperties, Gdk.Popup.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, WaylandSurface.WritableProperties, Gdk.Popup.WritableProperties {
                }

                interface ConstructOnlyProperties extends WaylandSurface.ConstructOnlyProperties, Gdk.Popup.ConstructOnlyProperties {
                }
            }

            interface WaylandPopup extends WaylandSurface, Gdk.Popup {
                readonly $signals: WaylandPopup.SignalSignatures
                readonly $readableProperties: WaylandPopup.ReadableProperties
                readonly $writableProperties: WaylandPopup.WritableProperties
                readonly $constructOnlyProperties: WaylandPopup.ConstructOnlyProperties
            }

            interface WaylandPopupClass extends Omit<WaylandSurfaceClass, "new"> {
                readonly $gtype: GObject.GType<WaylandPopup>
                readonly prototype: WaylandPopup

                new (props?: Partial<GObject.ConstructorProps<WaylandPopup>>): WaylandPopup
            }

            interface $Exports {
                /**
                 * The Wayland implementation of `GdkPopup`.
                 */
                WaylandPopup: WaylandPopupClass
            }
            

            namespace WaylandSeat {
                interface SignalSignatures extends Gdk.Seat.SignalSignatures {
                }

                interface ReadWriteProperties extends Gdk.Seat.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, Gdk.Seat.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, Gdk.Seat.WritableProperties {
                }

                interface ConstructOnlyProperties extends Gdk.Seat.ConstructOnlyProperties {
                }
            }

            interface WaylandSeat extends Gdk.Seat {
                readonly $signals: WaylandSeat.SignalSignatures
                readonly $readableProperties: WaylandSeat.ReadableProperties
                readonly $writableProperties: WaylandSeat.WritableProperties
                readonly $constructOnlyProperties: WaylandSeat.ConstructOnlyProperties
            }

            interface WaylandSeatClass extends Omit<Gdk.SeatClass, "new"> {
                readonly $gtype: GObject.GType<WaylandSeat>
                readonly prototype: WaylandSeat

                new (props?: Partial<GObject.ConstructorProps<WaylandSeat>>): WaylandSeat
            }

            interface $Exports {
                /**
                 * The Wayland implementation of `GdkSeat`.
                 *
                 * Beyond the regular {@link Gdk.Seat} API, the Wayland implementation
                 * provides access to the Wayland `wl_seat` object with
                 * {@link GdkWayland.WaylandSeat.get_wl_seat}.
                 */
                WaylandSeat: WaylandSeatClass
            }
            

            namespace WaylandSurface {
                interface SignalSignatures extends Gdk.Surface.SignalSignatures {
                }

                interface ReadWriteProperties extends Gdk.Surface.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, Gdk.Surface.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, Gdk.Surface.WritableProperties {
                }

                interface ConstructOnlyProperties extends Gdk.Surface.ConstructOnlyProperties {
                }
            }

            interface WaylandSurface extends Gdk.Surface {
                readonly $signals: WaylandSurface.SignalSignatures
                readonly $readableProperties: WaylandSurface.ReadableProperties
                readonly $writableProperties: WaylandSurface.WritableProperties
                readonly $constructOnlyProperties: WaylandSurface.ConstructOnlyProperties
                /**
                 * Forces next commit.
                 * @since 4.18
                 */
                force_next_commit(): void
            }

            interface WaylandSurfaceClass extends Omit<Gdk.SurfaceClass, "new"> {
                readonly $gtype: GObject.GType<WaylandSurface>
                readonly prototype: WaylandSurface

                new (props?: Partial<GObject.ConstructorProps<WaylandSurface>>): WaylandSurface
            }

            interface $Exports {
                /**
                 * The Wayland implementation of `GdkSurface`.
                 *
                 * Beyond the {@link Gdk.Surface} API, the Wayland implementation offers
                 * access to the Wayland `wl_surface` object with
                 * {@link GdkWayland.WaylandSurface.get_wl_surface}.
                 */
                WaylandSurface: WaylandSurfaceClass
            }
            

            namespace WaylandToplevel {
                interface SignalSignatures extends WaylandSurface.SignalSignatures, Gdk.Toplevel.SignalSignatures {
                }

                interface ReadWriteProperties extends WaylandSurface.ReadWriteProperties, Gdk.Toplevel.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, WaylandSurface.ReadableProperties, Gdk.Toplevel.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, WaylandSurface.WritableProperties, Gdk.Toplevel.WritableProperties {
                }

                interface ConstructOnlyProperties extends WaylandSurface.ConstructOnlyProperties, Gdk.Toplevel.ConstructOnlyProperties {
                }
            }

            interface WaylandToplevel extends WaylandSurface, Gdk.Toplevel {
                readonly $signals: WaylandToplevel.SignalSignatures
                readonly $readableProperties: WaylandToplevel.ReadableProperties
                readonly $writableProperties: WaylandToplevel.WritableProperties
                readonly $constructOnlyProperties: WaylandToplevel.ConstructOnlyProperties
                /**
                 * Destroy a handle that was obtained with gdk_wayland_toplevel_export_handle().
                 *
                 * Note that this API depends on an unstable Wayland protocol,
                 * and thus may require changes in the future.
                 * @since 4.12
                 * @param handle the handle to drop
                 */
                drop_exported_handle(handle: string): void
                /**
                 * Asynchronously obtains a handle for a surface that can be passed
                 * to other processes.
                 *
                 * When the handle has been obtained, `callback` will be called.
                 *
                 * It is an error to call this function on a surface that is already
                 * exported.
                 *
                 * When the handle is no longer needed, {@link GdkWayland.WaylandToplevel.unexport_handle}
                 * should be called to clean up resources.
                 *
                 * The main purpose for obtaining a handle is to mark a surface
                 * from another surface as transient for this one, see
                 * {@link GdkWayland.WaylandToplevel.set_transient_for_exported}.
                 *
                 * Before 4.12, this API could not safely be used multiple times,
                 * since there was no reference counting for handles. Starting with
                 * 4.12, every call to this function obtains a new handle, and every
                 * call to {@link GdkWayland.WaylandToplevel.drop_exported_handle} drops
                 * just the handle that it is given.
                 *
                 * Note that this API depends on an unstable Wayland protocol,
                 * and thus may require changes in the future.
                 * @param callback callback to call with the handle
                 * @returns %TRUE if the handle has been requested, %FALSE if   an error occurred.
                 */
                export_handle(callback: WaylandToplevelExported): boolean
                /**
                 * Sets the application id on a `GdkToplevel`.
                 * @param application_id the application id for the `toplevel`
                 */
                set_application_id(application_id: string): void
                /**
                 * Marks `toplevel` as transient for the surface to which the given
                 *  `parent_handle_str` refers.
                 *
                 * Typically, the handle will originate from a
                 * {@link GdkWayland.WaylandToplevel.export_handle} call in another process.
                 *
                 * Note that this API depends on an unstable Wayland protocol,
                 * and thus may require changes in the future.
                 * @param parent_handle_str an exported handle for a surface
                 * @returns %TRUE if the surface has been marked as transient,   %FALSE if an error occurred.
                 */
                set_transient_for_exported(parent_handle_str: string): boolean
                /**
                 * Destroys the handle that was obtained with
                 * gdk_wayland_toplevel_export_handle().
                 *
                 * It is an error to call this function on a surface that
                 * does not have a handle.
                 *
                 * Since 4.12, this function does nothing. Use
                 * {@link GdkWayland.WaylandToplevel.drop_exported_handle} instead to drop a
                 * handle that was obtained with {@link GdkWayland.WaylandToplevel.export_handle}.
                 *
                 * Note that this API depends on an unstable Wayland protocol,
                 * and thus may require changes in the future.
                 * @deprecated since 4.12 Use {@link GdkWayland.WaylandToplevel.drop_exported_handle}   instead, this function does nothing
                 */
                unexport_handle(): void
            }

            interface WaylandToplevelClass extends Omit<WaylandSurfaceClass, "new"> {
                readonly $gtype: GObject.GType<WaylandToplevel>
                readonly prototype: WaylandToplevel

                new (props?: Partial<GObject.ConstructorProps<WaylandToplevel>>): WaylandToplevel
            }

            interface $Exports {
                /**
                 * The Wayland implementation of `GdkToplevel`.
                 *
                 * Beyond the {@link Gdk.Toplevel} API, the Wayland implementation
                 * has API to set up cross-process parent-child relationships between
                 * surfaces with {@link GdkWayland.WaylandToplevel.export_handle} and
                 * {@link GdkWayland.WaylandToplevel.set_transient_for_exported}.
                 */
                WaylandToplevel: WaylandToplevelClass
            }
            /**
             * Callback that gets called when the handle for a surface has been
             * obtained from the Wayland compositor.
             *
             * This callback is used in {@link GdkWayland.WaylandToplevel.export_handle}.
             *
             * The `handle` can be passed to other processes, for the purpose of
             * marking surfaces as transient for out-of-process surfaces.
             * @param toplevel the `GdkToplevel` that is exported
             * @param handle the handle
             */
            type WaylandToplevelExported = (toplevel: WaylandToplevel, handle: string) => void

            interface $Exports {
                __name__: "GdkWayland"
                __version__: "4.0"
            }
        }

        const GdkWayland: GdkWayland.$Exports
    }

    export default GI.GdkWayland
}