
/// <reference path="./GLib-2.0.d.ts" />
/// <reference path="./GModule-2.0.d.ts" />
/// <reference path="./GObject-2.0.d.ts" />
/// <reference path="./Gio-2.0.d.ts" />
/// <reference path="./freetype2-2.0.d.ts" />
/// <reference path="./HarfBuzz-0.0.d.ts" />
/// <reference path="./cairo-1.0.d.ts" />
/// <reference path="./GdkPixbuf-2.0.d.ts" />
/// <reference path="./Pango-1.0.d.ts" />
/// <reference path="./Gdk-3.0.d.ts" />
/// <reference path="./xlib-2.0.d.ts" />

/**
 * Type Definitions for GJS (https://gjs.guide/), generated by [GirGen](https://github.com/aylur/girgen)
 * If you found a bug, create a bug report on [GirGen's Repository](https://github.com/aylur/girgen/issues/new)
 */
declare module "gi://GdkX11?version=3.0" {
    import type GLib from "gi://GLib?version=2.0"
    import type GModule from "gi://GModule?version=2.0"
    import type GObject from "gi://GObject?version=2.0"
    import type Gio from "gi://Gio?version=2.0"
    import type freetype2 from "gi://freetype2?version=2.0"
    import type HarfBuzz from "gi://HarfBuzz?version=0.0"
    import type cairo from "gi://cairo?version=1.0"
    import type GdkPixbuf from "gi://GdkPixbuf?version=2.0"
    import type Pango from "gi://Pango?version=1.0"
    import type Gdk from "gi://Gdk?version=3.0"
    import type xlib from "gi://xlib?version=2.0"

    /**
     * Do **not** import this at runtime.
     * This namespace is only exported for module augmentation.
     */
    export namespace GI {
        

        namespace GdkX11 {
            

            namespace X11AppLaunchContext {
                interface SignalSignatures extends Gdk.AppLaunchContext.SignalSignatures {
                }

                interface ReadWriteProperties extends Gdk.AppLaunchContext.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, Gdk.AppLaunchContext.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, Gdk.AppLaunchContext.WritableProperties {
                }

                interface ConstructOnlyProperties extends Gdk.AppLaunchContext.ConstructOnlyProperties {
                }
            }

            interface X11AppLaunchContext extends Gdk.AppLaunchContext {
                readonly $signals: X11AppLaunchContext.SignalSignatures
                readonly $readableProperties: X11AppLaunchContext.ReadableProperties
                readonly $writableProperties: X11AppLaunchContext.WritableProperties
                readonly $constructOnlyProperties: X11AppLaunchContext.ConstructOnlyProperties
            }

            interface X11AppLaunchContextClass extends Omit<Gdk.AppLaunchContextClass, "new"> {
                readonly $gtype: GObject.GType<X11AppLaunchContext>
                readonly prototype: X11AppLaunchContext

                new (props?: Partial<GObject.ConstructorProps<X11AppLaunchContext>>): X11AppLaunchContext
            }

            interface $Exports {
                
                X11AppLaunchContext: X11AppLaunchContextClass
            }
            

            namespace X11Cursor {
                interface SignalSignatures extends Gdk.Cursor.SignalSignatures {
                }

                interface ReadWriteProperties extends Gdk.Cursor.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, Gdk.Cursor.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, Gdk.Cursor.WritableProperties {
                }

                interface ConstructOnlyProperties extends Gdk.Cursor.ConstructOnlyProperties {
                }
            }

            interface X11Cursor extends Gdk.Cursor {
                readonly $signals: X11Cursor.SignalSignatures
                readonly $readableProperties: X11Cursor.ReadableProperties
                readonly $writableProperties: X11Cursor.WritableProperties
                readonly $constructOnlyProperties: X11Cursor.ConstructOnlyProperties
                /**
                 * Returns the X cursor belonging to a #GdkCursor.
                 * @returns an Xlib Cursor.
                 */
                get_xcursor(): xlib.Cursor
                /**
                 * Returns the display of a #GdkCursor.
                 * @returns an Xlib Display*.
                 */
                get_xdisplay(): xlib.Display
            }

            interface X11CursorClass extends Omit<Gdk.CursorClass, "new"> {
                readonly $gtype: GObject.GType<X11Cursor>
                readonly prototype: X11Cursor

                new (props?: Partial<GObject.ConstructorProps<X11Cursor>>): X11Cursor
            }

            interface $Exports {
                
                X11Cursor: X11CursorClass
            }
            

            namespace X11DeviceCore {
                interface SignalSignatures extends Gdk.Device.SignalSignatures {
                }

                interface ReadWriteProperties extends Gdk.Device.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, Gdk.Device.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, Gdk.Device.WritableProperties {
                }

                interface ConstructOnlyProperties extends Gdk.Device.ConstructOnlyProperties {
                }
            }

            interface X11DeviceCore extends Gdk.Device {
                readonly $signals: X11DeviceCore.SignalSignatures
                readonly $readableProperties: X11DeviceCore.ReadableProperties
                readonly $writableProperties: X11DeviceCore.WritableProperties
                readonly $constructOnlyProperties: X11DeviceCore.ConstructOnlyProperties
            }

            interface X11DeviceCoreClass extends Omit<Gdk.DeviceClass, "new"> {
                readonly $gtype: GObject.GType<X11DeviceCore>
                readonly prototype: X11DeviceCore

                new (props?: Partial<GObject.ConstructorProps<X11DeviceCore>>): X11DeviceCore
            }

            interface $Exports {
                
                X11DeviceCore: X11DeviceCoreClass
            }
            

            namespace X11DeviceManagerCore {
                interface SignalSignatures extends Gdk.DeviceManager.SignalSignatures {
                }

                interface ReadWriteProperties extends Gdk.DeviceManager.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, Gdk.DeviceManager.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, Gdk.DeviceManager.WritableProperties {
                }

                interface ConstructOnlyProperties extends Gdk.DeviceManager.ConstructOnlyProperties {
                }
            }

            interface X11DeviceManagerCore extends Gdk.DeviceManager {
                readonly $signals: X11DeviceManagerCore.SignalSignatures
                readonly $readableProperties: X11DeviceManagerCore.ReadableProperties
                readonly $writableProperties: X11DeviceManagerCore.WritableProperties
                readonly $constructOnlyProperties: X11DeviceManagerCore.ConstructOnlyProperties
            }

            interface X11DeviceManagerCoreClass extends Omit<Gdk.DeviceManagerClass, "new"> {
                readonly $gtype: GObject.GType<X11DeviceManagerCore>
                readonly prototype: X11DeviceManagerCore

                new (props?: Partial<GObject.ConstructorProps<X11DeviceManagerCore>>): X11DeviceManagerCore
            }

            interface $Exports {
                
                X11DeviceManagerCore: X11DeviceManagerCoreClass
            }
            

            namespace X11DeviceManagerXI2 {
                interface SignalSignatures extends X11DeviceManagerCore.SignalSignatures {
                }

                interface ReadWriteProperties extends X11DeviceManagerCore.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, X11DeviceManagerCore.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, X11DeviceManagerCore.WritableProperties {
                }

                interface ConstructOnlyProperties extends X11DeviceManagerCore.ConstructOnlyProperties {
                    "major": number
                    "minor": number
                    "opcode": number
                }
            }

            interface X11DeviceManagerXI2 extends X11DeviceManagerCore {
                readonly $signals: X11DeviceManagerXI2.SignalSignatures
                readonly $readableProperties: X11DeviceManagerXI2.ReadableProperties
                readonly $writableProperties: X11DeviceManagerXI2.WritableProperties
                readonly $constructOnlyProperties: X11DeviceManagerXI2.ConstructOnlyProperties
                /**
                 * @default 0
                 */
                get major(): number
                set major(value: number)
                /**
                 * @default 0
                 */
                get minor(): number
                set minor(value: number)
                /**
                 * @default 0
                 */
                get opcode(): number
                set opcode(value: number)
            }

            interface X11DeviceManagerXI2Class extends Omit<X11DeviceManagerCoreClass, "new"> {
                readonly $gtype: GObject.GType<X11DeviceManagerXI2>
                readonly prototype: X11DeviceManagerXI2

                new (props?: Partial<GObject.ConstructorProps<X11DeviceManagerXI2>>): X11DeviceManagerXI2
            }

            interface $Exports {
                
                X11DeviceManagerXI2: X11DeviceManagerXI2Class
            }
            

            namespace X11DeviceXI2 {
                interface SignalSignatures extends Gdk.Device.SignalSignatures {
                }

                interface ReadWriteProperties extends Gdk.Device.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, Gdk.Device.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, Gdk.Device.WritableProperties {
                }

                interface ConstructOnlyProperties extends Gdk.Device.ConstructOnlyProperties {
                    "device-id": number
                }
            }

            interface X11DeviceXI2 extends Gdk.Device {
                readonly $signals: X11DeviceXI2.SignalSignatures
                readonly $readableProperties: X11DeviceXI2.ReadableProperties
                readonly $writableProperties: X11DeviceXI2.WritableProperties
                readonly $constructOnlyProperties: X11DeviceXI2.ConstructOnlyProperties
                /**
                 * @default 0
                 */
                get deviceId(): number
                set deviceId(value: number)
            }

            interface X11DeviceXI2Class extends Omit<Gdk.DeviceClass, "new"> {
                readonly $gtype: GObject.GType<X11DeviceXI2>
                readonly prototype: X11DeviceXI2

                new (props?: Partial<GObject.ConstructorProps<X11DeviceXI2>>): X11DeviceXI2
            }

            interface $Exports {
                
                X11DeviceXI2: X11DeviceXI2Class
            }
            

            namespace X11Display {
                interface SignalSignatures extends Gdk.Display.SignalSignatures {
                }

                interface ReadWriteProperties extends Gdk.Display.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, Gdk.Display.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, Gdk.Display.WritableProperties {
                }

                interface ConstructOnlyProperties extends Gdk.Display.ConstructOnlyProperties {
                }
            }

            interface X11Display extends Gdk.Display {
                readonly $signals: X11Display.SignalSignatures
                readonly $readableProperties: X11Display.ReadableProperties
                readonly $writableProperties: X11Display.WritableProperties
                readonly $constructOnlyProperties: X11Display.ConstructOnlyProperties
                /**
                 * Pops the error trap pushed by gdk_x11_display_error_trap_push().
                 * Will XSync() if necessary and will always block until
                 * the error is known to have occurred or not occurred,
                 * so the error code can be returned.
                 *
                 * If you don’t need to use the return value,
                 * gdk_x11_display_error_trap_pop_ignored() would be more efficient.
                 *
                 * See gdk_error_trap_pop() for the all-displays-at-once
                 * equivalent.
                 * @since 3.0
                 * @returns X error code or 0 on success
                 */
                error_trap_pop(): number
                /**
                 * Pops the error trap pushed by gdk_x11_display_error_trap_push().
                 * Does not block to see if an error occurred; merely records the
                 * range of requests to ignore errors for, and ignores those errors
                 * if they arrive asynchronously.
                 *
                 * See gdk_error_trap_pop_ignored() for the all-displays-at-once
                 * equivalent.
                 * @since 3.0
                 */
                error_trap_pop_ignored(): void
                /**
                 * Begins a range of X requests on `display` for which X error events
                 * will be ignored. Unignored errors (when no trap is pushed) will abort
                 * the application. Use gdk_x11_display_error_trap_pop() or
                 * gdk_x11_display_error_trap_pop_ignored()to lift a trap pushed
                 * with this function.
                 *
                 * See also gdk_error_trap_push() to push a trap on all displays.
                 * @since 3.0
                 */
                error_trap_push(): void
                /**
                 * Gets the startup notification ID for a display.
                 * @since 2.12
                 * @returns the startup notification ID for `display`
                 */
                get_startup_notification_id(): string
                /**
                 * Returns the timestamp of the last user interaction on
                 *  `display`. The timestamp is taken from events caused
                 * by user interaction such as key presses or pointer
                 * movements. See gdk_x11_window_set_user_time().
                 * @since 2.8
                 * @returns the timestamp of the last user interaction
                 */
                get_user_time(): number
                /**
                 * Returns the X display of a #GdkDisplay.
                 * @since 2.2
                 * @returns an X display
                 */
                get_xdisplay(): xlib.Display
                /**
                 * Call XGrabServer() on `display`.
                 * To ungrab the display again, use gdk_x11_display_ungrab().
                 *
                 * gdk_x11_display_grab()/gdk_x11_display_ungrab() calls can be nested.
                 * @since 2.2
                 */
                grab(): void
                /**
                 * Sets the cursor theme from which the images for cursor
                 * should be taken.
                 *
                 * If the windowing system supports it, existing cursors created
                 * with gdk_cursor_new(), gdk_cursor_new_for_display() and
                 * gdk_cursor_new_from_name() are updated to reflect the theme
                 * change. Custom cursors constructed with
                 * gdk_cursor_new_from_pixbuf() will have to be handled
                 * by the application (GTK+ applications can learn about
                 * cursor theme changes by listening for change notification
                 * for the corresponding #GtkSetting).
                 * @since 2.8
                 * @param theme the name of the cursor theme to use, or %NULL to unset         a previously set value
                 * @param size the cursor size to use, or 0 to keep the previous size
                 */
                set_cursor_theme(theme: string | null, size: number): void
                /**
                 * Sets the startup notification ID for a display.
                 *
                 * This is usually taken from the value of the DESKTOP_STARTUP_ID
                 * environment variable, but in some cases (such as the application not
                 * being launched using exec()) it can come from other sources.
                 *
                 * If the ID contains the string "_TIME" then the portion following that
                 * string is taken to be the X11 timestamp of the event that triggered
                 * the application to be launched and the GDK current event time is set
                 * accordingly.
                 *
                 * The startup ID is also what is used to signal that the startup is
                 * complete (for example, when opening a window or when calling
                 * gdk_notify_startup_complete()).
                 * @since 3.0
                 * @param startup_id the startup notification ID (must be valid utf8)
                 */
                set_startup_notification_id(startup_id: string): void
                /**
                 * Forces a specific window scale for all windows on this display,
                 * instead of using the default or user configured scale. This
                 * is can be used to disable scaling support by setting `scale` to
                 * 1, or to programmatically set the window scale.
                 *
                 * Once the scale is set by this call it will not change in response
                 * to later user configuration changes.
                 * @since 3.10
                 * @param scale The new scale value
                 */
                set_window_scale(scale: number): void
                /**
                 * Convert a string from the encoding of the current
                 * locale into a form suitable for storing in a window property.
                 * @since 2.24
                 * @param str a nul-terminated string
                 * @returns 0 upon success, non-zero upon failure, location to store the encoding atom     (to be used as the type for the property), location to store the format of the property, location to store newly     allocated data for the property
                 */
                string_to_compound_text(str: string): [number, Gdk.Atom, number, Uint8Array]
                /**
                 * Convert a text string from the encoding as it is stored
                 * in a property into an array of strings in the encoding of
                 * the current locale. (The elements of the array represent the
                 * nul-separated elements of the original text string.)
                 * @since 2.24
                 * @param encoding an atom representing the encoding. The most    common values for this are STRING, or COMPOUND_TEXT.    This is value used as the type for the property
                 * @param format the format of the property
                 * @param text The text data
                 * @param length The number of items to transform
                 * @param list location to store an  array of strings in    the encoding of the current locale. This array should be    freed using gdk_free_text_list().
                 * @returns the number of strings stored in list, or 0,     if the conversion failed
                 */
                text_property_to_text_list(encoding: Gdk.Atom, format: number, text: number, length: number, list: string): number
                /**
                 * Ungrab `display` after it has been grabbed with
                 * gdk_x11_display_grab().
                 * @since 2.2
                 */
                ungrab(): void
                /**
                 * Converts from UTF-8 to compound text.
                 * @since 2.24
                 * @param str a UTF-8 string
                 * @returns %TRUE if the conversion succeeded,     otherwise %FALSE, location to store resulting encoding, location to store format of the result, location to store the data of the result
                 */
                utf8_to_compound_text(str: string): [boolean, Gdk.Atom, number, Uint8Array]
            }

            interface X11DisplayClass extends Omit<Gdk.DisplayClass, "new"> {
                readonly $gtype: GObject.GType<X11Display>
                readonly prototype: X11Display

                new (props?: Partial<GObject.ConstructorProps<X11Display>>): X11Display
                /**
                 * Retrieves the version of the GLX implementation.
                 * @since 3.16
                 * @param display a #GdkDisplay
                 * @returns %TRUE if GLX is available, return location for the GLX major version, return location for the GLX minor version
                 */
                get_glx_version(display: Gdk.Display): [boolean, number, number]
            }

            interface $Exports {
                
                X11Display: X11DisplayClass
            }
            

            namespace X11DisplayManager {
                interface SignalSignatures extends Gdk.DisplayManager.SignalSignatures {
                }

                interface ReadWriteProperties extends Gdk.DisplayManager.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, Gdk.DisplayManager.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, Gdk.DisplayManager.WritableProperties {
                }

                interface ConstructOnlyProperties extends Gdk.DisplayManager.ConstructOnlyProperties {
                }
            }

            interface X11DisplayManager extends Gdk.DisplayManager {
                readonly $signals: X11DisplayManager.SignalSignatures
                readonly $readableProperties: X11DisplayManager.ReadableProperties
                readonly $writableProperties: X11DisplayManager.WritableProperties
                readonly $constructOnlyProperties: X11DisplayManager.ConstructOnlyProperties
            }

            interface X11DisplayManagerClass extends Omit<Gdk.DisplayManagerClass, "new"> {
                readonly $gtype: GObject.GType<X11DisplayManager>
                readonly prototype: X11DisplayManager

                new (props?: Partial<GObject.ConstructorProps<X11DisplayManager>>): X11DisplayManager
            }

            interface $Exports {
                
                X11DisplayManager: X11DisplayManagerClass
            }
            

            namespace X11DragContext {
                interface SignalSignatures extends Gdk.DragContext.SignalSignatures {
                }

                interface ReadWriteProperties extends Gdk.DragContext.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, Gdk.DragContext.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, Gdk.DragContext.WritableProperties {
                }

                interface ConstructOnlyProperties extends Gdk.DragContext.ConstructOnlyProperties {
                }
            }

            interface X11DragContext extends Gdk.DragContext {
                readonly $signals: X11DragContext.SignalSignatures
                readonly $readableProperties: X11DragContext.ReadableProperties
                readonly $writableProperties: X11DragContext.WritableProperties
                readonly $constructOnlyProperties: X11DragContext.ConstructOnlyProperties
            }

            interface X11DragContextClass extends Omit<Gdk.DragContextClass, "new"> {
                readonly $gtype: GObject.GType<X11DragContext>
                readonly prototype: X11DragContext

                new (props?: Partial<GObject.ConstructorProps<X11DragContext>>): X11DragContext
            }

            interface $Exports {
                
                X11DragContext: X11DragContextClass
            }
            

            namespace X11GLContext {
                interface SignalSignatures extends Gdk.GLContext.SignalSignatures {
                }

                interface ReadWriteProperties extends Gdk.GLContext.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, Gdk.GLContext.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, Gdk.GLContext.WritableProperties {
                }

                interface ConstructOnlyProperties extends Gdk.GLContext.ConstructOnlyProperties {
                }
            }

            interface X11GLContext extends Gdk.GLContext {
                readonly $signals: X11GLContext.SignalSignatures
                readonly $readableProperties: X11GLContext.ReadableProperties
                readonly $writableProperties: X11GLContext.WritableProperties
                readonly $constructOnlyProperties: X11GLContext.ConstructOnlyProperties
            }

            interface X11GLContextClass extends Omit<Gdk.GLContextClass, "new"> {
                readonly $gtype: GObject.GType<X11GLContext>
                readonly prototype: X11GLContext

                new (props?: Partial<GObject.ConstructorProps<X11GLContext>>): X11GLContext
            }

            interface $Exports {
                
                X11GLContext: X11GLContextClass
            }
            

            namespace X11Keymap {
                interface SignalSignatures extends Gdk.Keymap.SignalSignatures {
                }

                interface ReadWriteProperties extends Gdk.Keymap.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, Gdk.Keymap.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, Gdk.Keymap.WritableProperties {
                }

                interface ConstructOnlyProperties extends Gdk.Keymap.ConstructOnlyProperties {
                }
            }

            interface X11Keymap extends Gdk.Keymap {
                readonly $signals: X11Keymap.SignalSignatures
                readonly $readableProperties: X11Keymap.ReadableProperties
                readonly $writableProperties: X11Keymap.WritableProperties
                readonly $constructOnlyProperties: X11Keymap.ConstructOnlyProperties
                /**
                 * Extracts the group from the state field sent in an X Key event.
                 * This is only needed for code processing raw X events, since #GdkEventKey
                 * directly includes an is_modifier field.
                 * @since 3.6
                 * @param state raw state returned from X
                 * @returns the index of the active keyboard group for the event
                 */
                get_group_for_state(state: number): number
                /**
                 * Determines whether a particular key code represents a key that
                 * is a modifier. That is, it’s a key that normally just affects
                 * the keyboard state and the behavior of other keys rather than
                 * producing a direct effect itself. This is only needed for code
                 * processing raw X events, since #GdkEventKey directly includes
                 * an is_modifier field.
                 * @since 3.6
                 * @param keycode the hardware keycode from a key event
                 * @returns %TRUE if the hardware keycode is a modifier key
                 */
                key_is_modifier(keycode: number): boolean
            }

            interface X11KeymapClass extends Omit<Gdk.KeymapClass, "new"> {
                readonly $gtype: GObject.GType<X11Keymap>
                readonly prototype: X11Keymap

                new (props?: Partial<GObject.ConstructorProps<X11Keymap>>): X11Keymap
            }

            interface $Exports {
                
                X11Keymap: X11KeymapClass
            }
            

            namespace X11Monitor {
                interface SignalSignatures extends Gdk.Monitor.SignalSignatures {
                }

                interface ReadWriteProperties extends Gdk.Monitor.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, Gdk.Monitor.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, Gdk.Monitor.WritableProperties {
                }

                interface ConstructOnlyProperties extends Gdk.Monitor.ConstructOnlyProperties {
                }
            }

            interface X11Monitor extends Gdk.Monitor {
                readonly $signals: X11Monitor.SignalSignatures
                readonly $readableProperties: X11Monitor.ReadableProperties
                readonly $writableProperties: X11Monitor.WritableProperties
                readonly $constructOnlyProperties: X11Monitor.ConstructOnlyProperties
            }

            interface X11MonitorClass extends Omit<Gdk.MonitorClass, "new"> {
                readonly $gtype: GObject.GType<X11Monitor>
                readonly prototype: X11Monitor

                new (props?: Partial<GObject.ConstructorProps<X11Monitor>>): X11Monitor
                /**
                 * @param monitor
                 */
                get_output(monitor: Gdk.Monitor): xlib.XID
            }

            interface $Exports {
                
                X11Monitor: X11MonitorClass
            }
            

            namespace X11Screen {
                interface SignalSignatures extends Gdk.Screen.SignalSignatures {
                    
                    "window-manager-changed"(): void
                }

                interface ReadWriteProperties extends Gdk.Screen.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, Gdk.Screen.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, Gdk.Screen.WritableProperties {
                }

                interface ConstructOnlyProperties extends Gdk.Screen.ConstructOnlyProperties {
                }
            }

            interface X11Screen extends Gdk.Screen {
                readonly $signals: X11Screen.SignalSignatures
                readonly $readableProperties: X11Screen.ReadableProperties
                readonly $writableProperties: X11Screen.WritableProperties
                readonly $constructOnlyProperties: X11Screen.ConstructOnlyProperties
                /**
                 * Returns the current workspace for `screen` when running under a
                 * window manager that supports multiple workspaces, as described
                 * in the
                 * [Extended Window Manager Hints](https://specifications.freedesktop.org/wm/latest/) specification.
                 * @since 3.10
                 * @returns the current workspace, or 0 if workspaces are not supported
                 */
                get_current_desktop(): number
                /**
                 * Gets the XID of the specified output/monitor.
                 * If the X server does not support version 1.2 of the RANDR
                 * extension, 0 is returned.
                 * @since 2.14
                 * @param monitor_num number of the monitor, between 0 and gdk_screen_get_n_monitors (screen)
                 * @returns the XID of the monitor
                 */
                get_monitor_output(monitor_num: number): xlib.XID
                /**
                 * Returns the number of workspaces for `screen` when running under a
                 * window manager that supports multiple workspaces, as described
                 * in the
                 * [Extended Window Manager Hints](https://specifications.freedesktop.org/wm/latest/) specification.
                 * @since 3.10
                 * @returns the number of workspaces, or 0 if workspaces are not supported
                 */
                get_number_of_desktops(): number
                /**
                 * Returns the index of a #GdkScreen.
                 * @since 2.2
                 * @returns the position of `screen` among the screens     of its display
                 */
                get_screen_number(): number
                /**
                 * Returns the name of the window manager for `screen`.
                 * @since 2.2
                 * @returns the name of the window manager screen `screen`, or "unknown" if the window manager is unknown. The string is owned by GDK and should not be freed.
                 */
                get_window_manager_name(): string
                /**
                 * Returns the screen of a #GdkScreen.
                 * @since 2.2
                 * @returns an Xlib Screen*
                 */
                get_xscreen(): xlib.Screen
                /**
                 * Looks up the #GdkVisual for a particular screen and X Visual ID.
                 * @since 2.2
                 * @param xvisualid an X Visual ID.
                 * @returns the #GdkVisual (owned by the screen   object), or %NULL if the visual ID wasn’t found.
                 */
                lookup_visual(xvisualid: xlib.VisualID): X11Visual
                /**
                 * This function is specific to the X11 backend of GDK, and indicates
                 * whether the window manager supports a certain hint from the
                 * [Extended Window Manager Hints](https://specifications.freedesktop.org/wm/latest/) specification.
                 *
                 * When using this function, keep in mind that the window manager
                 * can change over time; so you shouldn’t use this function in
                 * a way that impacts persistent application state. A common bug
                 * is that your application can start up before the window manager
                 * does when the user logs in, and before the window manager starts
                 * gdk_x11_screen_supports_net_wm_hint() will return %FALSE for every property.
                 * You can monitor the window_manager_changed signal on #GdkScreen to detect
                 * a window manager change.
                 * @since 2.2
                 * @param property a property atom.
                 * @returns %TRUE if the window manager supports `property`
                 */
                supports_net_wm_hint(property: Gdk.Atom): boolean
            }

            interface X11ScreenClass extends Omit<Gdk.ScreenClass, "new"> {
                readonly $gtype: GObject.GType<X11Screen>
                readonly prototype: X11Screen

                new (props?: Partial<GObject.ConstructorProps<X11Screen>>): X11Screen
            }

            interface $Exports {
                
                X11Screen: X11ScreenClass
            }
            

            namespace X11Visual {
                interface SignalSignatures extends Gdk.Visual.SignalSignatures {
                }

                interface ReadWriteProperties extends Gdk.Visual.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, Gdk.Visual.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, Gdk.Visual.WritableProperties {
                }

                interface ConstructOnlyProperties extends Gdk.Visual.ConstructOnlyProperties {
                }
            }

            interface X11Visual extends Gdk.Visual {
                readonly $signals: X11Visual.SignalSignatures
                readonly $readableProperties: X11Visual.ReadableProperties
                readonly $writableProperties: X11Visual.WritableProperties
                readonly $constructOnlyProperties: X11Visual.ConstructOnlyProperties
                /**
                 * Returns the X visual belonging to a #GdkVisual.
                 * @returns an Xlib Visual*.
                 */
                get_xvisual(): xlib.Visual
            }

            interface X11VisualClass extends Omit<Gdk.VisualClass, "new"> {
                readonly $gtype: GObject.GType<X11Visual>
                readonly prototype: X11Visual

                new (props?: Partial<GObject.ConstructorProps<X11Visual>>): X11Visual
            }

            interface $Exports {
                
                X11Visual: X11VisualClass
            }
            

            namespace X11Window {
                interface SignalSignatures extends Gdk.Window.SignalSignatures {
                }

                interface ReadWriteProperties extends Gdk.Window.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, Gdk.Window.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, Gdk.Window.WritableProperties {
                }

                interface ConstructOnlyProperties extends Gdk.Window.ConstructOnlyProperties {
                }
            }

            interface X11Window extends Gdk.Window {
                readonly $signals: X11Window.SignalSignatures
                readonly $readableProperties: X11Window.ReadableProperties
                readonly $writableProperties: X11Window.WritableProperties
                readonly $constructOnlyProperties: X11Window.ConstructOnlyProperties
                /**
                 * Gets the number of the workspace `window` is on.
                 * @since 3.10
                 * @returns the current workspace of `window`
                 */
                get_desktop(): number
                /**
                 * Returns the X resource (window) belonging to a #GdkWindow.
                 * @returns the ID of `drawable`’s X resource.
                 */
                get_xid(): xlib.Window
                /**
                 * Moves the window to the correct workspace when running under a
                 * window manager that supports multiple workspaces, as described
                 * in the [Extended Window Manager Hints](https://specifications.freedesktop.org/wm/latest/) specification.
                 * Will not do anything if the window is already on all workspaces.
                 * @since 2.8
                 */
                move_to_current_desktop(): void
                /**
                 * Moves the window to the given workspace when running unde a
                 * window manager that supports multiple workspaces, as described
                 * in the [Extended Window Manager Hints](https://specifications.freedesktop.org/wm/latest/) specification.
                 * @since 3.10
                 * @param desktop the number of the workspace to move the window to
                 */
                move_to_desktop(desktop: number): void
                /**
                 * This is the same as gdk_window_set_shadow_width() but it only works
                 * on GdkX11Window.
                 * @since 3.10
                 * @deprecated since 3.12 Use gdk_window_set_shadow_width() instead.
                 * @param left The left extent
                 * @param right The right extent
                 * @param top The top extent
                 * @param bottom The bottom extent
                 */
                set_frame_extents(left: number, right: number, top: number, bottom: number): void
                /**
                 * This function can be used to disable frame synchronization for a window.
                 * Normally frame synchronziation will be enabled or disabled based on whether
                 * the system has a compositor that supports frame synchronization, but if
                 * the window is not directly managed by the window manager, then frame
                 * synchronziation may need to be disabled. This is the case for a window
                 * embedded via the XEMBED protocol.
                 * @since 3.8
                 * @param frame_sync_enabled whether frame-synchronization should be enabled
                 */
                set_frame_sync_enabled(frame_sync_enabled: boolean): void
                /**
                 * Set a hint for the window manager, requesting that the titlebar
                 * should be hidden when the window is maximized.
                 *
                 * Note that this property is automatically updated by GTK+, so this
                 * function should only be used by applications which do not use GTK+
                 * to create toplevel windows.
                 * @since 3.4
                 * @param hide_titlebar_when_maximized whether to hide the titlebar when                                maximized
                 */
                set_hide_titlebar_when_maximized(hide_titlebar_when_maximized: boolean): void
                /**
                 * GTK+ applications can request a dark theme variant. In order to
                 * make other applications - namely window managers using GTK+ for
                 * themeing - aware of this choice, GTK+ uses this function to
                 * export the requested theme variant as _GTK_THEME_VARIANT property
                 * on toplevel windows.
                 *
                 * Note that this property is automatically updated by GTK+, so this
                 * function should only be used by applications which do not use GTK+
                 * to create toplevel windows.
                 * @since 3.2
                 * @param variant the theme variant to export
                 */
                set_theme_variant(variant: string): void
                /**
                 * The application can use this call to update the _NET_WM_USER_TIME
                 * property on a toplevel window.  This property stores an Xserver
                 * time which represents the time of the last user input event
                 * received for this window.  This property may be used by the window
                 * manager to alter the focus, stacking, and/or placement behavior of
                 * windows when they are mapped depending on whether the new window
                 * was created by a user action or is a "pop-up" window activated by a
                 * timer or some other event.
                 *
                 * Note that this property is automatically updated by GDK, so this
                 * function should only be used by applications which handle input
                 * events bypassing GDK.
                 * @since 2.6
                 * @param timestamp An XServer timestamp to which the property should be set
                 */
                set_user_time(timestamp: number): void
                /**
                 * This function modifies or removes an arbitrary X11 window
                 * property of type UTF8_STRING.  If the given `window` is
                 * not a toplevel window, it is ignored.
                 * @since 3.4
                 * @param name Property name, will be interned as an X atom
                 * @param value Property value, or %NULL to delete
                 */
                set_utf8_property(name: string, value: string | null): void
            }

            interface X11WindowClass extends Omit<Gdk.WindowClass, "new"> {
                readonly $gtype: GObject.GType<X11Window>
                readonly prototype: X11Window

                new (props?: Partial<GObject.ConstructorProps<X11Window>>): X11Window
                /**
                 * Wraps a native window in a #GdkWindow. The function will try to
                 * look up the window using gdk_x11_window_lookup_for_display() first.
                 * If it does not find it there, it will create a new window.
                 *
                 * This may fail if the window has been destroyed. If the window
                 * was already known to GDK, a new reference to the existing
                 * #GdkWindow is returned.
                 * @since 2.24
                 * @param display the #GdkDisplay where the window handle comes from.
                 * @param window an Xlib Window
                 * @returns a #GdkWindow wrapper for the native   window, or %NULL if the window has been destroyed. The wrapper   will be newly created, if one doesn’t exist already.
                 */
                foreign_new_for_display(display: X11Display, window: xlib.Window): X11Window
                /**
                 * Looks up the #GdkWindow that wraps the given native window handle.
                 * @since 2.24
                 * @param display the #GdkDisplay corresponding to the           window handle
                 * @param window an Xlib Window
                 * @returns the #GdkWindow wrapper for the native    window, or %NULL if there is none.
                 */
                lookup_for_display(display: X11Display, window: xlib.Window): X11Window
            }

            interface $Exports {
                
                X11Window: X11WindowClass
            }

            interface $Exports {
                __name__: "GdkX11"
                __version__: "3.0"
                /**
                 * Converts from a #GdkAtom to the X atom for the default GDK display
                 * with the same string value.
                 * @param atom A #GdkAtom
                 * @returns the X atom corresponding to `atom`.
                 */
                x11_atom_to_xatom(atom: Gdk.Atom): xlib.Atom
                /**
                 * Converts from a #GdkAtom to the X atom for a #GdkDisplay
                 * with the same string value. The special value %GDK_NONE
                 * is converted to %None.
                 * @since 2.2
                 * @param display A #GdkDisplay
                 * @param atom A #GdkAtom, or %GDK_NONE
                 * @returns the X atom corresponding to `atom`, or %None
                 */
                x11_atom_to_xatom_for_display(display: X11Display, atom: Gdk.Atom): xlib.Atom
                /**
                 * Returns the device ID as seen by XInput2.
                 *
                 * > If gdk_disable_multidevice() has been called, this function
                 * > will respectively return 2/3 for the core pointer and keyboard,
                 * > (matching the IDs for the Virtual Core Pointer and Keyboard in
                 * > XInput 2), but calling this function on any slave devices (i.e.
                 * > those managed via XInput 1.x), will return 0.
                 * @since 3.2
                 * @param device a #GdkDevice
                 * @returns the XInput2 device ID.
                 */
                x11_device_get_id(device: X11DeviceCore): number
                /**
                 * Returns the #GdkDevice that wraps the given device ID.
                 * @since 3.2
                 * @param device_manager a #GdkDeviceManager
                 * @param device_id a device ID, as understood by the XInput2 protocol
                 * @returns The #GdkDevice wrapping the device ID,          or %NULL if the given ID doesn’t currently represent a device.
                 */
                x11_device_manager_lookup(device_manager: X11DeviceManagerCore, device_id: number): X11DeviceCore | null
                /**
                 * Frees the data returned from gdk_x11_display_string_to_compound_text().
                 * @since 2.24
                 * @param ctext The pointer stored in `ctext` from a call to   gdk_x11_display_string_to_compound_text().
                 */
                x11_free_compound_text(ctext: number): void
                /**
                 * Frees the array of strings created by
                 * gdk_x11_display_text_property_to_text_list().
                 * @since 2.24
                 * @param list the value stored in the `list` parameter by   a call to gdk_x11_display_text_property_to_text_list().
                 */
                x11_free_text_list(list: string): void
                /**
                 * Gets the root window of the default screen
                 * (see gdk_x11_get_default_screen()).
                 * @returns an Xlib Window.
                 */
                x11_get_default_root_xwindow(): xlib.Window
                /**
                 * Gets the default GTK+ screen number.
                 * @returns returns the screen number specified by   the --display command line option or the DISPLAY environment   variable when gdk_init() calls XOpenDisplay().
                 */
                x11_get_default_screen(): number
                /**
                 * Gets the default GTK+ display.
                 * @returns the Xlib Display* for the display specified in the `--display` command line option or the `DISPLAY` environment variable.
                 */
                x11_get_default_xdisplay(): xlib.Display
                /**
                 * Used with gdk_window_set_background_pattern() to inherit background from
                 * parent window. Useful for imitating transparency when compositing is not
                 * available. Otherwise behaves like a transparent pattern.
                 * @since 3.24.2
                 * @deprecated since 3.24 Don't use this function
                 */
                x11_get_parent_relative_pattern(): cairo.Pattern
                /**
                 * Routine to get the current X server time stamp.
                 * @param window a #GdkWindow, used for communication          with the server.  The window must have          GDK_PROPERTY_CHANGE_MASK in its events mask or a hang will          result.
                 * @returns the time stamp.
                 */
                x11_get_server_time(window: X11Window): number
                /**
                 * Returns the X atom for GDK’s default display corresponding to `atom_name`.
                 * This function caches the result, so if called repeatedly it is much
                 * faster than XInternAtom(), which is a round trip to the server each time.
                 * @param atom_name a string
                 * @returns a X atom for GDK’s default display.
                 */
                x11_get_xatom_by_name(atom_name: string): xlib.Atom
                /**
                 * Returns the X atom for a #GdkDisplay corresponding to `atom_name`.
                 * This function caches the result, so if called repeatedly it is much
                 * faster than XInternAtom(), which is a round trip to the server each time.
                 * @since 2.2
                 * @param display a #GdkDisplay
                 * @param atom_name a string
                 * @returns a X atom for a #GdkDisplay
                 */
                x11_get_xatom_by_name_for_display(display: X11Display, atom_name: string): xlib.Atom
                /**
                 * Returns the name of an X atom for GDK’s default display. This
                 * function is meant mainly for debugging, so for convenience, unlike
                 * XAtomName() and gdk_atom_name(), the result
                 * doesn’t need to be freed. Also, this function will never return %NULL,
                 * even if `xatom` is invalid.
                 * @param xatom an X atom for GDK’s default display
                 * @returns name of the X atom; this string is owned by GTK+,   so it shouldn’t be modifed or freed.
                 */
                x11_get_xatom_name(xatom: xlib.Atom): string
                /**
                 * Returns the name of an X atom for its display. This
                 * function is meant mainly for debugging, so for convenience, unlike
                 * XAtomName() and gdk_atom_name(), the result doesn’t need to
                 * be freed.
                 * @since 2.2
                 * @param display the #GdkDisplay where `xatom` is defined
                 * @param xatom an X atom
                 * @returns name of the X atom; this string is owned by GDK,   so it shouldn’t be modifed or freed.
                 */
                x11_get_xatom_name_for_display(display: X11Display, xatom: xlib.Atom): string
                /**
                 * Call gdk_x11_display_grab() on the default display.
                 * To ungrab the server again, use gdk_x11_ungrab_server().
                 *
                 * gdk_x11_grab_server()/gdk_x11_ungrab_server() calls can be nested.
                 */
                x11_grab_server(): void
                /**
                 * Find the #GdkDisplay corresponding to `xdisplay`, if any exists.
                 * @since 2.2
                 * @param xdisplay a pointer to an X Display
                 * @returns the #GdkDisplay, if found, otherwise %NULL.
                 */
                x11_lookup_xdisplay(xdisplay: xlib.Display): X11Display
                /**
                 * Registers interest in receiving extension events with type codes
                 * between `event_base` and `event_base + n_events - 1`.
                 * The registered events must have the window field in the same place
                 * as core X events (this is not the case for e.g. XKB extension events).
                 *
                 * If an event type is registered, events of this type will go through
                 * global and window-specific filters (see gdk_window_add_filter()).
                 * Unregistered events will only go through global filters.
                 * GDK may register the events of some X extensions on its own.
                 *
                 * This function should only be needed in unusual circumstances, e.g.
                 * when filtering XInput extension events on the root window.
                 * @since 2.4
                 * @param display a #GdkDisplay
                 * @param event_base first event type code to register
                 * @param n_events number of event type codes to register
                 */
                x11_register_standard_event_type(display: X11Display, event_base: number, n_events: number): void
                /**
                 * Sets the `SM_CLIENT_ID` property on the application’s leader window so that
                 * the window manager can save the application’s state using the X11R6 ICCCM
                 * session management protocol.
                 *
                 * See the X Session Management Library documentation for more information on
                 * session management and the Inter-Client Communication Conventions Manual
                 * @since 2.24
                 * @param sm_client_id the client id assigned by the session manager    when the connection was opened, or %NULL to remove the property.
                 */
                x11_set_sm_client_id(sm_client_id: string | null): void
                /**
                 * Ungrab the default display after it has been grabbed with
                 * gdk_x11_grab_server().
                 */
                x11_ungrab_server(): void
                /**
                 * Convert from an X atom for the default display to the corresponding
                 * #GdkAtom.
                 * @param xatom an X atom for the default GDK display
                 * @returns the corresponding G#dkAtom.
                 */
                x11_xatom_to_atom(xatom: xlib.Atom): Gdk.Atom
                /**
                 * Convert from an X atom for a #GdkDisplay to the corresponding
                 * #GdkAtom.
                 * @since 2.2
                 * @param display A #GdkDisplay
                 * @param xatom an X atom
                 * @returns the corresponding #GdkAtom.
                 */
                x11_xatom_to_atom_for_display(display: X11Display, xatom: xlib.Atom): Gdk.Atom
            }
        }

        const GdkX11: GdkX11.$Exports
    }

    export default GI.GdkX11
}