
/// <reference path="./GLib-2.0.d.ts" />
/// <reference path="./GModule-2.0.d.ts" />
/// <reference path="./GObject-2.0.d.ts" />
/// <reference path="./Gio-2.0.d.ts" />
/// <reference path="./freetype2-2.0.d.ts" />
/// <reference path="./HarfBuzz-0.0.d.ts" />
/// <reference path="./cairo-1.0.d.ts" />
/// <reference path="./Pango-1.0.d.ts" />
/// <reference path="./GdkPixbuf-2.0.d.ts" />
/// <reference path="./PangoCairo-1.0.d.ts" />
/// <reference path="./Gdk-4.0.d.ts" />
/// <reference path="./xlib-2.0.d.ts" />

/**
 * Type Definitions for GJS (https://gjs.guide/), generated by [GirGen](https://github.com/aylur/girgen)
 * If you found a bug, create a bug report on [GirGen's Repository](https://github.com/aylur/girgen/issues/new)
 */
declare module "gi://GdkX11?version=4.0" {
    import type GLib from "gi://GLib?version=2.0"
    import type GModule from "gi://GModule?version=2.0"
    import type GObject from "gi://GObject?version=2.0"
    import type Gio from "gi://Gio?version=2.0"
    import type freetype2 from "gi://freetype2?version=2.0"
    import type HarfBuzz from "gi://HarfBuzz?version=0.0"
    import type cairo from "gi://cairo?version=1.0"
    import type Pango from "gi://Pango?version=1.0"
    import type GdkPixbuf from "gi://GdkPixbuf?version=2.0"
    import type PangoCairo from "gi://PangoCairo?version=1.0"
    import type Gdk from "gi://Gdk?version=4.0"
    import type xlib from "gi://xlib?version=2.0"

    /**
     * Do **not** import this at runtime.
     * This namespace is only exported for module augmentation.
     */
    export namespace GI {
        

        namespace GdkX11 {
            

            namespace X11AppLaunchContext {
                interface SignalSignatures extends Gdk.AppLaunchContext.SignalSignatures {
                }

                interface ReadWriteProperties extends Gdk.AppLaunchContext.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, Gdk.AppLaunchContext.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, Gdk.AppLaunchContext.WritableProperties {
                }

                interface ConstructOnlyProperties extends Gdk.AppLaunchContext.ConstructOnlyProperties {
                }
            }

            interface X11AppLaunchContext extends Gdk.AppLaunchContext {
                readonly $signals: X11AppLaunchContext.SignalSignatures
                readonly $readableProperties: X11AppLaunchContext.ReadableProperties
                readonly $writableProperties: X11AppLaunchContext.WritableProperties
                readonly $constructOnlyProperties: X11AppLaunchContext.ConstructOnlyProperties
            }

            interface X11AppLaunchContextClass extends Omit<Gdk.AppLaunchContextClass, "new"> {
                readonly $gtype: GObject.GType<X11AppLaunchContext>
                readonly prototype: X11AppLaunchContext

                new (props?: Partial<GObject.ConstructorProps<X11AppLaunchContext>>): X11AppLaunchContext
            }

            interface $Exports {
                
                X11AppLaunchContext: X11AppLaunchContextClass
            }
            

            namespace X11DeviceManagerXI2 {
                interface SignalSignatures extends GObject.Object.SignalSignatures {
                }

                interface ReadWriteProperties extends GObject.Object.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, GObject.Object.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, GObject.Object.WritableProperties {
                }

                interface ConstructOnlyProperties extends GObject.Object.ConstructOnlyProperties {
                    "display": Gdk.Display
                    "major": number
                    "minor": number
                    "opcode": number
                }
            }

            interface X11DeviceManagerXI2 extends GObject.Object {
                readonly $signals: X11DeviceManagerXI2.SignalSignatures
                readonly $readableProperties: X11DeviceManagerXI2.ReadableProperties
                readonly $writableProperties: X11DeviceManagerXI2.WritableProperties
                readonly $constructOnlyProperties: X11DeviceManagerXI2.ConstructOnlyProperties
                
                get display(): Gdk.Display
                set display(value: Gdk.Display)
                /**
                 * @default 0
                 */
                get major(): number
                set major(value: number)
                /**
                 * @default 0
                 */
                get minor(): number
                set minor(value: number)
                /**
                 * @default 0
                 */
                get opcode(): number
                set opcode(value: number)
            }

            interface X11DeviceManagerXI2Class extends Omit<GObject.ObjectClass, "new"> {
                readonly $gtype: GObject.GType<X11DeviceManagerXI2>
                readonly prototype: X11DeviceManagerXI2

                new (props?: Partial<GObject.ConstructorProps<X11DeviceManagerXI2>>): X11DeviceManagerXI2
            }

            interface $Exports {
                
                X11DeviceManagerXI2: X11DeviceManagerXI2Class
            }
            

            namespace X11DeviceXI2 {
                interface SignalSignatures extends Gdk.Device.SignalSignatures {
                }

                interface ReadWriteProperties extends Gdk.Device.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, Gdk.Device.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, Gdk.Device.WritableProperties {
                }

                interface ConstructOnlyProperties extends Gdk.Device.ConstructOnlyProperties {
                    "device-id": number
                }
            }

            interface X11DeviceXI2 extends Gdk.Device {
                readonly $signals: X11DeviceXI2.SignalSignatures
                readonly $readableProperties: X11DeviceXI2.ReadableProperties
                readonly $writableProperties: X11DeviceXI2.WritableProperties
                readonly $constructOnlyProperties: X11DeviceXI2.ConstructOnlyProperties
                /**
                 * @default 0
                 */
                get deviceId(): number
                set deviceId(value: number)
            }

            interface X11DeviceXI2Class extends Omit<Gdk.DeviceClass, "new"> {
                readonly $gtype: GObject.GType<X11DeviceXI2>
                readonly prototype: X11DeviceXI2

                new (props?: Partial<GObject.ConstructorProps<X11DeviceXI2>>): X11DeviceXI2
            }

            interface $Exports {
                
                X11DeviceXI2: X11DeviceXI2Class
            }
            

            namespace X11Display {
                interface SignalSignatures extends Gdk.Display.SignalSignatures {
                    /**
                     * The ::xevent signal is a low level signal that is emitted
                     * whenever an XEvent has been received.
                     *
                     * When handlers to this signal return %TRUE, no other handlers will be
                     * invoked. In particular, the default handler for this function is
                     * GDK's own event handling mechanism, so by returning %TRUE for an event
                     * that GDK expects to translate, you may break GDK and/or GTK+ in
                     * interesting ways. You have been warned.
                     *
                     * If you want this signal handler to queue a `GdkEvent`, you can use
                     * gdk_display_put_event().
                     *
                     * If you are interested in X GenericEvents, bear in mind that
                     * XGetEventData() has been already called on the event, and
                     * XFreeEventData() will be called afterwards.
                     * @param xevent a pointer to the XEvent to process
                     * @returns %TRUE to stop other handlers from being invoked for the event.   %FALSE to propagate the event further.
                     */
                    "xevent"(xevent: never | null): boolean
                }

                interface ReadWriteProperties extends Gdk.Display.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, Gdk.Display.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, Gdk.Display.WritableProperties {
                }

                interface ConstructOnlyProperties extends Gdk.Display.ConstructOnlyProperties {
                }
            }

            interface X11Display extends Gdk.Display {
                readonly $signals: X11Display.SignalSignatures
                readonly $readableProperties: X11Display.ReadableProperties
                readonly $writableProperties: X11Display.WritableProperties
                readonly $constructOnlyProperties: X11Display.ConstructOnlyProperties
                /**
                 * Pops the error trap pushed by gdk_x11_display_error_trap_push().
                 * Will XSync() if necessary and will always block until
                 * the error is known to have occurred or not occurred,
                 * so the error code can be returned.
                 *
                 * If you don’t need to use the return value,
                 * gdk_x11_display_error_trap_pop_ignored() would be more efficient.
                 * @deprecated since 4.18
                 * @returns X error code or 0 on success
                 */
                error_trap_pop(): number
                /**
                 * Pops the error trap pushed by gdk_x11_display_error_trap_push().
                 * Does not block to see if an error occurred; merely records the
                 * range of requests to ignore errors for, and ignores those errors
                 * if they arrive asynchronously.
                 * @deprecated since 4.18
                 */
                error_trap_pop_ignored(): void
                /**
                 * Begins a range of X requests on `display` for which X error events
                 * will be ignored. Unignored errors (when no trap is pushed) will abort
                 * the application. Use gdk_x11_display_error_trap_pop() or
                 * gdk_x11_display_error_trap_pop_ignored()to lift a trap pushed
                 * with this function.
                 * @deprecated since 4.18
                 */
                error_trap_push(): void
                /**
                 * Returns the default group leader surface for all toplevel surfaces
                 * on `display`. This surface is implicitly created by GDK.
                 * See gdk_x11_surface_set_group().
                 * @deprecated since 4.18
                 * @returns The default group leader surface for `display`
                 */
                get_default_group(): Gdk.Surface
                /**
                 * Retrieves the EGL display connection object for the given GDK display.
                 *
                 * This function returns `NULL` if GDK is using GLX.
                 * @since 4.4
                 * @deprecated since 4.18
                 * @returns the EGL display object
                 */
                get_egl_display(): never | null
                /**
                 * Retrieves the version of the EGL implementation.
                 * @since 4.4
                 * @deprecated since 4.18
                 * @returns %TRUE if EGL is available, return location for the EGL major version, return location for the EGL minor version
                 */
                get_egl_version(): [boolean, number, number]
                /**
                 * Retrieves the version of the GLX implementation.
                 * @deprecated since 4.18
                 * @returns %TRUE if GLX is available, return location for the GLX major version, return location for the GLX minor version
                 */
                get_glx_version(): [boolean, number, number]
                /**
                 * Gets the primary monitor for the display.
                 *
                 * The primary monitor is considered the monitor where the “main desktop”
                 * lives. While normal application surfaces typically allow the window
                 * manager to place the surfaces, specialized desktop applications
                 * such as panels should place themselves on the primary monitor.
                 *
                 * If no monitor is the designated primary monitor, any monitor
                 * (usually the first) may be returned.
                 * @deprecated since 4.18
                 * @returns the primary monitor, or any monitor if no   primary monitor is configured by the user
                 */
                get_primary_monitor(): Gdk.Monitor
                /**
                 * Retrieves the `GdkX11Screen` of the `display`.
                 * @deprecated since 4.18
                 * @returns the `GdkX11Screen`
                 */
                get_screen(): X11Screen
                /**
                 * Gets the startup notification ID for a display.
                 * @deprecated since 4.10
                 * @returns the startup notification ID for `display`
                 */
                get_startup_notification_id(): string
                /**
                 * Returns the timestamp of the last user interaction on
                 *  `display`. The timestamp is taken from events caused
                 * by user interaction such as key presses or pointer
                 * movements. See gdk_x11_surface_set_user_time().
                 * @deprecated since 4.18
                 * @returns the timestamp of the last user interaction
                 */
                get_user_time(): number
                /**
                 * Returns the X cursor belonging to a `GdkCursor`, potentially
                 * creating the cursor.
                 *
                 * Be aware that the returned cursor may not be unique to `cursor`.
                 * It may for example be shared with its fallback cursor. On old
                 * X servers that don't support the XCursor extension, all cursors
                 * may even fall back to a few default cursors.
                 * @deprecated since 4.18
                 * @param cursor a `GdkCursor`
                 * @returns an Xlib Cursor.
                 */
                get_xcursor(cursor: Gdk.Cursor): xlib.Cursor
                /**
                 * Returns the X display of a `GdkDisplay`.
                 * @deprecated since 4.18
                 * @returns an X display
                 */
                get_xdisplay(): xlib.Display
                /**
                 * Returns the root X window used by `GdkDisplay`.
                 * @deprecated since 4.18
                 * @returns an X Window
                 */
                get_xrootwindow(): xlib.Window
                /**
                 * Returns the X Screen used by `GdkDisplay`.
                 * @deprecated since 4.18
                 * @returns an X Screen
                 */
                get_xscreen(): xlib.Screen
                /**
                 * Call XGrabServer() on `display`.
                 * To ungrab the display again, use gdk_x11_display_ungrab().
                 *
                 * gdk_x11_display_grab()/gdk_x11_display_ungrab() calls can be nested.
                 * @deprecated since 4.18
                 */
                grab(): void
                /**
                 * Sets the cursor theme from which the images for cursor
                 * should be taken.
                 *
                 * If the windowing system supports it, existing cursors created
                 * with {@link Gdk.Cursor.new_from_name} are updated to reflect the theme
                 * change. Custom cursors constructed with {@link Gdk.Cursor.new_from_texture}
                 * will have to be handled by the application (GTK applications can learn
                 * about cursor theme changes by listening for change notification
                 * for the corresponding `GtkSetting`).
                 * @deprecated since 4.16 Use the cursor-related properties of   [GtkSettings](../gtk4/class.Settings.html) to set the cursor theme
                 * @param theme the name of the cursor theme to use, or %NULL   to unset a previously set value
                 * @param size the cursor size to use, or 0 to keep the previous size
                 */
                set_cursor_theme(theme: string | null, size: number): void
                /**
                 * Sets the startup notification ID for a display.
                 *
                 * This is usually taken from the value of the DESKTOP_STARTUP_ID
                 * environment variable, but in some cases (such as the application not
                 * being launched using exec()) it can come from other sources.
                 *
                 * If the ID contains the string "_TIME" then the portion following that
                 * string is taken to be the X11 timestamp of the event that triggered
                 * the application to be launched and the GDK current event time is set
                 * accordingly.
                 *
                 * The startup ID is also what is used to signal that the startup is
                 * complete (for example, when opening a window or when calling
                 * gdk_display_notify_startup_complete()).
                 * @deprecated since 4.10 Using {@link Gdk.Toplevel.set_startup_id} is sufficient
                 * @param startup_id the startup notification ID (must be valid utf8)
                 */
                set_startup_notification_id(startup_id: string): void
                /**
                 * Forces a specific window scale for all windows on this display,
                 * instead of using the default or user configured scale. This
                 * is can be used to disable scaling support by setting `scale` to
                 * 1, or to programmatically set the window scale.
                 *
                 * Once the scale is set by this call it will not change in response
                 * to later user configuration changes.
                 * @deprecated since 4.18
                 * @param scale The new scale value
                 */
                set_surface_scale(scale: number): void
                /**
                 * Convert a string from the encoding of the current
                 * locale into a form suitable for storing in a window property.
                 * @deprecated since 4.18
                 * @param str a nul-terminated string
                 * @returns 0 upon success, non-zero upon failure, location to store the encoding   (to be used as the type for the property), location to store the format of the property, location to store newly   allocated data for the property
                 */
                string_to_compound_text(str: string): [number, string, number, Uint8Array]
                /**
                 * Convert a text string from the encoding as it is stored
                 * in a property into an array of strings in the encoding of
                 * the current locale. (The elements of the array represent the
                 * nul-separated elements of the original text string.)
                 * @deprecated since 4.18
                 * @param encoding a string representing the encoding. The most   common values for this are "STRING", or "COMPOUND_TEXT".   This is value used as the type for the property
                 * @param format the format of the property
                 * @param text The text data
                 * @param length The number of items to transform
                 * @param list location to store an  array of strings in   the encoding of the current locale. This array should be   freed using gdk_x11_free_text_list().
                 * @returns the number of strings stored in list, or 0,   if the conversion failed
                 */
                text_property_to_text_list(encoding: string, format: number, text: number, length: number, list: string): number
                /**
                 * Ungrab `display` after it has been grabbed with
                 * gdk_x11_display_grab().
                 * @deprecated since 4.18
                 */
                ungrab(): void
                /**
                 * Converts from UTF-8 to compound text.
                 * @deprecated since 4.18
                 * @param str a UTF-8 string
                 * @returns %TRUE if the conversion succeeded, otherwise %FALSE, location to store resulting encoding, location to store format of the result, location to store the data of the result
                 */
                utf8_to_compound_text(str: string): [boolean, string, number, Uint8Array]
            }

            interface X11DisplayClass extends Omit<Gdk.DisplayClass, "new"> {
                readonly $gtype: GObject.GType<X11Display>
                readonly prototype: X11Display

                new (props?: Partial<GObject.ConstructorProps<X11Display>>): X11Display
                /**
                 * Tries to open a new display to the X server given by
                 *  `display_name`. If opening the display fails, %NULL is
                 * returned.
                 * @deprecated since 4.18
                 * @param display_name name of the X display.   See the XOpenDisplay() for details.
                 * @returns The new display
                 */
                open(display_name: string | null): Gdk.Display | null
                /**
                 * Sets the program class.
                 *
                 * The X11 backend uses the program class to set the class name part
                 * of the `WM_CLASS` property on toplevel windows; see the ICCCM.
                 * @deprecated since 4.18
                 * @param display a `GdkDisplay`
                 * @param program_class a string
                 */
                set_program_class(display: Gdk.Display, program_class: string): void
            }

            interface $Exports {
                
                X11Display: X11DisplayClass
            }
            

            namespace X11Drag {
                interface SignalSignatures extends Gdk.Drag.SignalSignatures {
                }

                interface ReadWriteProperties extends Gdk.Drag.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, Gdk.Drag.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, Gdk.Drag.WritableProperties {
                }

                interface ConstructOnlyProperties extends Gdk.Drag.ConstructOnlyProperties {
                }
            }

            interface X11Drag extends Gdk.Drag {
                readonly $signals: X11Drag.SignalSignatures
                readonly $readableProperties: X11Drag.ReadableProperties
                readonly $writableProperties: X11Drag.WritableProperties
                readonly $constructOnlyProperties: X11Drag.ConstructOnlyProperties
            }

            interface X11DragClass extends Omit<Gdk.DragClass, "new"> {
                readonly $gtype: GObject.GType<X11Drag>
                readonly prototype: X11Drag

                new (props?: Partial<GObject.ConstructorProps<X11Drag>>): X11Drag
            }

            interface $Exports {
                
                X11Drag: X11DragClass
            }
            

            namespace X11GLContext {
                interface SignalSignatures extends Gdk.GLContext.SignalSignatures {
                }

                interface ReadWriteProperties extends Gdk.GLContext.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, Gdk.GLContext.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, Gdk.GLContext.WritableProperties {
                }

                interface ConstructOnlyProperties extends Gdk.GLContext.ConstructOnlyProperties {
                }
            }

            interface X11GLContext extends Gdk.GLContext {
                readonly $signals: X11GLContext.SignalSignatures
                readonly $readableProperties: X11GLContext.ReadableProperties
                readonly $writableProperties: X11GLContext.WritableProperties
                readonly $constructOnlyProperties: X11GLContext.ConstructOnlyProperties
            }

            interface X11GLContextClass extends Omit<Gdk.GLContextClass, "new"> {
                readonly $gtype: GObject.GType<X11GLContext>
                readonly prototype: X11GLContext

                new (props?: Partial<GObject.ConstructorProps<X11GLContext>>): X11GLContext
            }

            interface $Exports {
                
                X11GLContext: X11GLContextClass
            }
            

            namespace X11Monitor {
                interface SignalSignatures extends Gdk.Monitor.SignalSignatures {
                }

                interface ReadWriteProperties extends Gdk.Monitor.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, Gdk.Monitor.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, Gdk.Monitor.WritableProperties {
                }

                interface ConstructOnlyProperties extends Gdk.Monitor.ConstructOnlyProperties {
                }
            }

            interface X11Monitor extends Gdk.Monitor {
                readonly $signals: X11Monitor.SignalSignatures
                readonly $readableProperties: X11Monitor.ReadableProperties
                readonly $writableProperties: X11Monitor.WritableProperties
                readonly $constructOnlyProperties: X11Monitor.ConstructOnlyProperties
                /**
                 * Returns the XID of the Output corresponding to `monitor`.
                 * @deprecated since 4.18
                 * @returns the XID of `monitor`
                 */
                get_output(): xlib.XID
                /**
                 * Retrieves the size and position of the “work area” on a monitor
                 * within the display coordinate space.
                 *
                 * The returned geometry is in ”application pixels”, not in ”device pixels”
                 * (see {@link Gdk.Monitor.get_scale_factor}).
                 * @deprecated since 4.18
                 * @returns , a `GdkRectangle` to be filled with the monitor workarea
                 */
                get_workarea(): Gdk.Rectangle
            }

            interface X11MonitorClass extends Omit<Gdk.MonitorClass, "new"> {
                readonly $gtype: GObject.GType<X11Monitor>
                readonly prototype: X11Monitor

                new (props?: Partial<GObject.ConstructorProps<X11Monitor>>): X11Monitor
            }

            interface $Exports {
                
                X11Monitor: X11MonitorClass
            }
            

            namespace X11Screen {
                interface SignalSignatures extends GObject.Object.SignalSignatures {
                    
                    "window-manager-changed"(): void
                }

                interface ReadWriteProperties extends GObject.Object.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, GObject.Object.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, GObject.Object.WritableProperties {
                }

                interface ConstructOnlyProperties extends GObject.Object.ConstructOnlyProperties {
                }
            }

            interface X11Screen extends GObject.Object {
                readonly $signals: X11Screen.SignalSignatures
                readonly $readableProperties: X11Screen.ReadableProperties
                readonly $writableProperties: X11Screen.WritableProperties
                readonly $constructOnlyProperties: X11Screen.ConstructOnlyProperties
                /**
                 * Returns the current workspace for `screen` when running under a
                 * window manager that supports multiple workspaces, as described
                 * in the
                 * [Extended Window Manager Hints](https://specifications.freedesktop.org/wm/latest/) specification.
                 * @deprecated since 4.18
                 * @returns the current workspace, or 0 if workspaces are not supported
                 */
                get_current_desktop(): number
                /**
                 * Gets the XID of the specified output/monitor.
                 * If the X server does not support version 1.2 of the RANDR
                 * extension, 0 is returned.
                 * @deprecated since 4.18
                 * @param monitor_num number of the monitor, between 0 and gdk_screen_get_n_monitors (screen)
                 * @returns the XID of the monitor
                 */
                get_monitor_output(monitor_num: number): xlib.XID
                /**
                 * Returns the number of workspaces for `screen` when running under a
                 * window manager that supports multiple workspaces, as described
                 * in the
                 * [Extended Window Manager Hints](https://specifications.freedesktop.org/wm/latest/) specification.
                 * @deprecated since 4.18
                 * @returns the number of workspaces, or 0 if workspaces are not supported
                 */
                get_number_of_desktops(): number
                /**
                 * Returns the index of a `GdkX11Screen`.
                 * @deprecated since 4.18
                 * @returns the position of `screen` among the screens   of its display
                 */
                get_screen_number(): number
                /**
                 * Returns the name of the window manager for `screen`.
                 * @deprecated since 4.18
                 * @returns the name of the window manager screen `screen`, or "unknown" if the window manager is unknown. The string is owned by GDK and should not be freed.
                 */
                get_window_manager_name(): string
                /**
                 * Returns the screen of a `GdkX11Screen`.
                 * @deprecated since 4.18
                 * @returns an Xlib Screen*
                 */
                get_xscreen(): xlib.Screen
                /**
                 * This function is specific to the X11 backend of GDK, and indicates
                 * whether the window manager supports a certain hint from the
                 * [Extended Window Manager Hints](https://specifications.freedesktop.org/wm/latest/) specification.
                 *
                 * When using this function, keep in mind that the window manager
                 * can change over time; so you shouldn’t use this function in
                 * a way that impacts persistent application state. A common bug
                 * is that your application can start up before the window manager
                 * does when the user logs in, and before the window manager starts
                 * gdk_x11_screen_supports_net_wm_hint() will return %FALSE for every property.
                 * You can monitor the window_manager_changed signal on `GdkX11Screen` to detect
                 * a window manager change.
                 * @deprecated since 4.18
                 * @param property_name name of the WM property
                 * @returns %TRUE if the window manager supports `property`
                 */
                supports_net_wm_hint(property_name: string): boolean
            }

            interface X11ScreenClass extends Omit<GObject.ObjectClass, "new"> {
                readonly $gtype: GObject.GType<X11Screen>
                readonly prototype: X11Screen

                new (props?: Partial<GObject.ConstructorProps<X11Screen>>): X11Screen
            }

            interface $Exports {
                
                X11Screen: X11ScreenClass
            }
            

            namespace X11Surface {
                interface SignalSignatures extends Gdk.Surface.SignalSignatures {
                }

                interface ReadWriteProperties extends Gdk.Surface.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, Gdk.Surface.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, Gdk.Surface.WritableProperties {
                }

                interface ConstructOnlyProperties extends Gdk.Surface.ConstructOnlyProperties {
                }
            }

            interface X11Surface extends Gdk.Surface {
                readonly $signals: X11Surface.SignalSignatures
                readonly $readableProperties: X11Surface.ReadableProperties
                readonly $writableProperties: X11Surface.WritableProperties
                readonly $constructOnlyProperties: X11Surface.ConstructOnlyProperties
                /**
                 * Gets the number of the workspace `surface` is on.
                 * @deprecated since 4.18
                 * @returns the current workspace of `surface`
                 */
                get_desktop(): number
                /**
                 * Returns the group this surface belongs to.
                 * @deprecated since 4.18
                 * @returns The group of this surface;
                 */
                get_group(): Gdk.Surface | null
                /**
                 * Returns the X resource (surface) belonging to a `GdkSurface`.
                 * @deprecated since 4.18
                 * @returns the ID of `drawable`’s X resource.
                 */
                get_xid(): xlib.Window
                /**
                 * Moves the surface to the correct workspace when running under a
                 * window manager that supports multiple workspaces, as described
                 * in the [Extended Window Manager Hints](https://specifications.freedesktop.org/wm/latest/) specification.
                 * Will not do anything if the surface is already on all workspaces.
                 * @deprecated since 4.18
                 */
                move_to_current_desktop(): void
                /**
                 * Moves the surface to the given workspace when running unde a
                 * window manager that supports multiple workspaces, as described
                 * in the [Extended Window Manager Hints](https://specifications.freedesktop.org/wm/latest/) specification.
                 * @deprecated since 4.18
                 * @param desktop the number of the workspace to move the surface to
                 */
                move_to_desktop(desktop: number): void
                /**
                 * This function can be used to disable frame synchronization for a surface.
                 * Normally frame synchronziation will be enabled or disabled based on whether
                 * the system has a compositor that supports frame synchronization, but if
                 * the surface is not directly managed by the window manager, then frame
                 * synchronziation may need to be disabled. This is the case for a surface
                 * embedded via the XEMBED protocol.
                 * @deprecated since 4.18
                 * @param frame_sync_enabled whether frame-synchronization should be enabled
                 */
                set_frame_sync_enabled(frame_sync_enabled: boolean): void
                /**
                 * Sets the group leader of `surface` to be `leader`.
                 * See the ICCCM for details.
                 * @deprecated since 4.18
                 * @param leader a `GdkSurface`
                 */
                set_group(leader: Gdk.Surface): void
                /**
                 * Sets a hint on `surface` that pagers should not
                 * display it. See the EWMH for details.
                 * @deprecated since 4.18
                 * @param skips_pager %TRUE to skip pagers
                 */
                set_skip_pager_hint(skips_pager: boolean): void
                /**
                 * Sets a hint on `surface` that taskbars should not
                 * display it. See the EWMH for details.
                 * @deprecated since 4.18
                 * @param skips_taskbar %TRUE to skip taskbars
                 */
                set_skip_taskbar_hint(skips_taskbar: boolean): void
                /**
                 * GTK applications can request a dark theme variant. In order to
                 * make other applications - namely window managers using GTK for
                 * themeing - aware of this choice, GTK uses this function to
                 * export the requested theme variant as _GTK_THEME_VARIANT property
                 * on toplevel surfaces.
                 *
                 * Note that this property is automatically updated by GTK, so this
                 * function should only be used by applications which do not use GTK
                 * to create toplevel surfaces.
                 * @deprecated since 4.18
                 * @param variant the theme variant to export
                 */
                set_theme_variant(variant: string): void
                /**
                 * Sets a hint on `surface` that it needs user attention.
                 * See the ICCCM for details.
                 * @deprecated since 4.18
                 * @param urgent %TRUE to indicate urgenct attention needed
                 */
                set_urgency_hint(urgent: boolean): void
                /**
                 * The application can use this call to update the _NET_WM_USER_TIME
                 * property on a toplevel surface.  This property stores an Xserver
                 * time which represents the time of the last user input event
                 * received for this surface.  This property may be used by the window
                 * manager to alter the focus, stacking, and/or placement behavior of
                 * surfaces when they are mapped depending on whether the new surface
                 * was created by a user action or is a "pop-up" surface activated by a
                 * timer or some other event.
                 *
                 * Note that this property is automatically updated by GDK, so this
                 * function should only be used by applications which handle input
                 * events bypassing GDK.
                 * @deprecated since 4.18
                 * @param timestamp An XServer timestamp to which the property should be set
                 */
                set_user_time(timestamp: number): void
                /**
                 * This function modifies or removes an arbitrary X11 window
                 * property of type UTF8_STRING.  If the given `surface` is
                 * not a toplevel surface, it is ignored.
                 * @deprecated since 4.18
                 * @param name Property name, will be interned as an X atom
                 * @param value Property value, or %NULL to delete
                 */
                set_utf8_property(name: string, value: string | null): void
            }

            interface X11SurfaceClass extends Omit<Gdk.SurfaceClass, "new"> {
                readonly $gtype: GObject.GType<X11Surface>
                readonly prototype: X11Surface

                new (props?: Partial<GObject.ConstructorProps<X11Surface>>): X11Surface
                /**
                 * Looks up the `GdkSurface` that wraps the given native window handle.
                 * @deprecated since 4.18
                 * @param display the `GdkDisplay` corresponding to the   window handle
                 * @param window an Xlib Window
                 * @returns the `GdkSurface` wrapper   for the native  window
                 */
                lookup_for_display(display: X11Display, window: xlib.Window): X11Surface
            }

            interface $Exports {
                
                X11Surface: X11SurfaceClass
            }
            
            interface X11DeviceTypeEnum {
                readonly $gtype: GObject.GType<X11DeviceType>
                
                readonly "LOGICAL": 0
                
                readonly "PHYSICAL": 1
                
                readonly "FLOATING": 2
            }
            type X11DeviceType = X11DeviceTypeEnum[Exclude<keyof X11DeviceTypeEnum, "$gtype">]
            interface $Exports {
                
                X11DeviceType: X11DeviceTypeEnum
            }

            interface $Exports {
                __name__: "GdkX11"
                __version__: "4.0"
                /**
                 * Returns the device ID as seen by XInput2.
                 * @deprecated since 4.18
                 * @param device a `GdkDevice`
                 * @returns the XInput2 device ID
                 */
                x11_device_get_id(device: X11DeviceXI2): number
                /**
                 * Returns the `GdkDevice` that wraps the given device ID.
                 * @deprecated since 4.18
                 * @param device_manager a `GdkDeviceManager`
                 * @param device_id a device ID, as understood by the XInput2 protocol
                 * @returns The   `GdkDevice` wrapping the device ID, or %NULL if the given ID   doesn’t currently represent a device.
                 */
                x11_device_manager_lookup(device_manager: X11DeviceManagerXI2, device_id: number): X11DeviceXI2 | null
                /**
                 * Frees the data returned from gdk_x11_display_string_to_compound_text().
                 * @deprecated since 4.18
                 * @param ctext The pointer stored in `ctext` from a call to   gdk_x11_display_string_to_compound_text().
                 */
                x11_free_compound_text(ctext: number): void
                /**
                 * Frees the array of strings created by
                 * gdk_x11_display_text_property_to_text_list().
                 * @deprecated since 4.18
                 * @param list the value stored in the `list` parameter by   a call to gdk_x11_display_text_property_to_text_list().
                 */
                x11_free_text_list(list: string): void
                /**
                 * Routine to get the current X server time stamp.
                 * @deprecated since 4.18
                 * @param surface a `GdkSurface`, used for communication   with the server. The surface must have `GDK_PROPERTY_CHANGE_MASK` in   its events mask or a hang will result.
                 * @returns the time stamp
                 */
                x11_get_server_time(surface: X11Surface): number
                /**
                 * Returns the X atom for a `GdkDisplay` corresponding to `atom_name`.
                 * This function caches the result, so if called repeatedly it is much
                 * faster than XInternAtom(), which is a round trip to the server each time.
                 * @deprecated since 4.18
                 * @param display a `GdkDisplay`
                 * @param atom_name a string
                 * @returns a X atom for a `GdkDisplay`
                 */
                x11_get_xatom_by_name_for_display(display: X11Display, atom_name: string): xlib.Atom
                /**
                 * Returns the name of an X atom for its display. This
                 * function is meant mainly for debugging, so for convenience, unlike
                 * XAtomName() and the result doesn’t need to
                 * be freed.
                 * @deprecated since 4.18
                 * @param display the `GdkDisplay` where `xatom` is defined
                 * @param xatom an X atom
                 * @returns name of the X atom; this string is owned by GDK,   so it shouldn’t be modified or freed.
                 */
                x11_get_xatom_name_for_display(display: X11Display, xatom: xlib.Atom): string
                /**
                 * Find the `GdkDisplay` corresponding to `xdisplay`, if any exists.
                 * @deprecated since 4.18
                 * @param xdisplay a pointer to an X Display
                 * @returns the `GdkDisplay`, if found, otherwise %NULL.
                 */
                x11_lookup_xdisplay(xdisplay: xlib.Display): X11Display
                /**
                 * Sets the `SM_CLIENT_ID` property on the application’s leader window so that
                 * the window manager can save the application’s state using the X11R6 ICCCM
                 * session management protocol.
                 *
                 * See the X Session Management Library documentation for more information on
                 * session management and the Inter-Client Communication Conventions Manual
                 * @deprecated since 4.18
                 * @param sm_client_id the client id assigned by the session manager    when the connection was opened, or %NULL to remove the property.
                 */
                x11_set_sm_client_id(sm_client_id: string | null): void
            }
        }

        const GdkX11: GdkX11.$Exports
    }

    export default GI.GdkX11
}