
/// <reference path="./GLib-2.0.d.ts" />
/// <reference path="./GModule-2.0.d.ts" />
/// <reference path="./GObject-2.0.d.ts" />
/// <reference path="./Gio-2.0.d.ts" />

/**
 * Type Definitions for GJS (https://gjs.guide/), generated by [GirGen](https://github.com/aylur/girgen)
 * If you found a bug, create a bug report on [GirGen's Repository](https://github.com/aylur/girgen/issues/new)
 */
declare module "gi://GioUnix?version=2.0" {
    import type GLib from "gi://GLib?version=2.0"
    import type GModule from "gi://GModule?version=2.0"
    import type GObject from "gi://GObject?version=2.0"
    import type Gio from "gi://Gio?version=2.0"

    /**
     * Do **not** import this at runtime.
     * This namespace is only exported for module augmentation.
     */
    export namespace GI {
        

        namespace GioUnix {
            

            namespace DesktopAppInfo {
                interface SignalSignatures extends GObject.Object.SignalSignatures, Gio.AppInfo.SignalSignatures {
                }

                interface ReadWriteProperties extends GObject.Object.ReadWriteProperties, Gio.AppInfo.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, GObject.Object.ReadableProperties, Gio.AppInfo.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, GObject.Object.WritableProperties, Gio.AppInfo.WritableProperties {
                }

                interface ConstructOnlyProperties extends GObject.Object.ConstructOnlyProperties, Gio.AppInfo.ConstructOnlyProperties {
                    "filename": string | null
                }
            }

            interface DesktopAppInfo extends GObject.Object, Gio.AppInfo {
                readonly $signals: DesktopAppInfo.SignalSignatures
                readonly $readableProperties: DesktopAppInfo.ReadableProperties
                readonly $writableProperties: DesktopAppInfo.WritableProperties
                readonly $constructOnlyProperties: DesktopAppInfo.ConstructOnlyProperties
                /**
                 * The origin filename of this {@link GioUnix.DesktopAppInfo}
                 * @default NULL
                 */
                get filename(): string | null
                set filename(value: string | null)
                /**
                 * Gets the user-visible display name of the
                 * [‘additional application actions’](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s11.html)
                 * specified by `action_name`.
                 *
                 * This corresponds to the `Name` key within the keyfile group for the
                 * action.
                 * @since 2.38
                 * @param action_name the name of the action as from   {@link GioUnix.DesktopAppInfo.list_actions}
                 * @returns the locale-specific action name
                 */
                get_action_name(action_name: string): string
                /**
                 * Looks up a boolean value in the keyfile backing `info`.
                 *
                 * The `key` is looked up in the `Desktop Entry` group.
                 * @since 2.36
                 * @param key the key to look up
                 * @returns the boolean value, or `FALSE` if the key is not found
                 */
                get_boolean(key: string): boolean
                /**
                 * Gets the categories from the desktop file.
                 * @returns The unparsed   [`Categories` key](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s06.html#key-categories)   from the desktop file;   i.e. no attempt is made to split it by `;` or validate it.
                 */
                get_categories(): string | null
                /**
                 * When `info` was created from a known filename, return it.
                 *
                 * In some situations such as a {@link GioUnix.DesktopAppInfo} returned
                 * from {@link GioUnix.DesktopAppInfo.new_from_keyfile}, this function
                 * will return `NULL`.
                 * @since 2.24
                 * @returns The full path to the file for `info`,   or `NULL` if not known.
                 */
                get_filename(): string | null
                /**
                 * Gets the generic name from the desktop file.
                 * @returns The value of the   [`GenericName` key](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s06.html#key-genericname)
                 */
                get_generic_name(): string | null
                /**
                 * A desktop file is hidden if the
                 * [`Hidden` key](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s06.html#key-hidden)
                 * in it is set to `True`.
                 * @returns `TRUE` if hidden, `FALSE` otherwise.
                 */
                get_is_hidden(): boolean
                /**
                 * Gets the keywords from the desktop file.
                 * @since 2.32
                 * @returns The value of the   [`Keywords` key](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s06.html#key-keywords)
                 */
                get_keywords(): string[] | null
                /**
                 * Looks up a localized string value in the keyfile backing `info`
                 * translated to the current locale.
                 *
                 * The `key` is looked up in the `Desktop Entry` group.
                 * @since 2.56
                 * @param key the key to look up
                 * @returns a newly allocated string, or `NULL` if the key is not   found
                 */
                get_locale_string(key: string): string | null
                /**
                 * Gets the value of the
                 * [`NoDisplay` key](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s06.html#key-nodisplay)
                 *  which helps determine if the application info should be shown in menus. See
                 * `G_KEY_FILE_DESKTOP_KEY_NO_DISPLAY` and {@link Gio.AppInfo.should_show}.
                 * @since 2.30
                 * @returns The value of the `NoDisplay` key
                 */
                get_nodisplay(): boolean
                /**
                 * Checks if the application info should be shown in menus that list available
                 * applications for a specific name of the desktop, based on the
                 * [`OnlyShowIn`](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s06.html#key-onlyshowin)
                 * and [`NotShowIn`](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s06.html#key-notshowin)
                 * keys.
                 *
                 *  `desktop_env` should typically be given as `NULL`, in which case the
                 * `XDG_CURRENT_DESKTOP` environment variable is consulted.  If you want
                 * to override the default mechanism then you may specify `desktop_env`,
                 * but this is not recommended.
                 *
                 * Note that {@link Gio.AppInfo.should_show} for `info` will include this check
                 * (with `NULL` for `desktop_env`) as well as additional checks.
                 * @since 2.30
                 * @param desktop_env a string specifying a desktop name
                 * @returns `TRUE` if the `info` should be shown in `desktop_env` according to the `OnlyShowIn` and `NotShowIn` keys, `FALSE` otherwise.
                 */
                get_show_in(desktop_env: string | null): boolean
                /**
                 * Retrieves the `StartupWMClass` field from `info`. This represents the
                 * `WM_CLASS` property of the main window of the application, if launched
                 * through `info`.
                 * @since 2.34
                 * @returns the startup WM class, or `NULL` if none   is set in the desktop file.
                 */
                get_startup_wm_class(): string | null
                /**
                 * Looks up a string value in the keyfile backing `info`.
                 *
                 * The `key` is looked up in the `Desktop Entry` group.
                 * @since 2.36
                 * @param key the key to look up
                 * @returns a newly allocated string, or `NULL` if the key is not   found
                 */
                get_string(key: string): string | null
                /**
                 * Looks up a string list value in the keyfile backing `info`.
                 *
                 * The `key` is looked up in the `Desktop Entry` group.
                 * @since 2.60
                 * @param key the key to look up
                 * @returns    a `NULL`-terminated string array or `NULL` if the specified   key cannot be found. The array should be freed with {@link GLib.strfreev}.
                 */
                get_string_list(key: string): string[] | null
                /**
                 * Returns whether `key` exists in the `Desktop Entry` group
                 * of the keyfile backing `info`.
                 * @since 2.36
                 * @param key the key to look up
                 * @returns `TRUE` if the `key` exists
                 */
                has_key(key: string): boolean
                /**
                 * Activates the named application action.
                 *
                 * You may only call this function on action names that were
                 * returned from {@link GioUnix.DesktopAppInfo.list_actions}.
                 *
                 * Note that if the main entry of the desktop file indicates that the
                 * application supports startup notification, and `launch_context` is
                 * non-`NULL`, then startup notification will be used when activating the
                 * action (and as such, invocation of the action on the receiving side
                 * must signal the end of startup notification when it is completed).
                 * This is the expected behaviour of applications declaring additional
                 * actions, as per the
                 * [desktop file specification](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s11.html).
                 *
                 * As with {@link Gio.AppInfo.launch} there is no way to detect failures that
                 * occur while using this function.
                 * @since 2.38
                 * @param action_name the name of the action as from   {@link GioUnix.DesktopAppInfo.list_actions}
                 * @param launch_context a {@link Gio.AppLaunchContext}
                 */
                launch_action(action_name: string, launch_context: Gio.AppLaunchContext | null): void
                /**
                 * This function performs the equivalent of {@link Gio.AppInfo.launch_uris},
                 * but is intended primarily for operating system components that
                 * launch applications.  Ordinary applications should use
                 * {@link Gio.AppInfo.launch_uris}.
                 *
                 * If the application is launched via GSpawn, then `spawn_flags`, `user_setup`
                 * and `user_setup_data` are used for the call to {@link GLib.spawn_async}.
                 * Additionally, `pid_callback` (with `pid_callback_data`) will be called to
                 * inform about the PID of the created process. See
                 * {@link GLib.spawn_async_with_pipes} for information on certain parameter
                 * conditions that can enable an optimized [`posix_spawn()`](man:posix_spawn(3))
                 * code path to be used.
                 *
                 * If application launching occurs via some other mechanism (for example, D-Bus
                 * activation) then `spawn_flags`, `user_setup`, `user_setup_data`,
                 *  `pid_callback` and `pid_callback_data` are ignored.
                 * @throws {GLib.Error}
                 * @param uris List of URIs
                 * @param launch_context a {@link Gio.AppLaunchContext}
                 * @param spawn_flags {@link GLib.SpawnFlags}, used for each process
                 * @param user_setup a {@link GLib.SpawnChildSetupFunc},   used once  for each process.
                 * @param pid_callback Callback for child processes
                 * @returns `TRUE` on successful launch, `FALSE` otherwise.
                 */
                launch_uris_as_manager(uris: string[], launch_context: Gio.AppLaunchContext | null, spawn_flags: GLib.SpawnFlags, user_setup: GLib.SpawnChildSetupFunc | null, pid_callback: DesktopAppLaunchCallback | null): boolean
                /**
                 * Equivalent to {@link GioUnix.DesktopAppInfo.launch_uris_as_manager} but
                 * allows you to pass in file descriptors for the stdin, stdout and stderr
                 * streams of the launched process.
                 *
                 * If application launching occurs via some non-spawn mechanism (e.g. D-Bus
                 * activation) then `stdin_fd`, `stdout_fd` and `stderr_fd` are ignored.
                 * @throws {GLib.Error}
                 * @since 2.58
                 * @param uris List of URIs
                 * @param launch_context a {@link Gio.AppLaunchContext}
                 * @param spawn_flags {@link GLib.SpawnFlags}, used for each process
                 * @param user_setup a   {@link GLib.SpawnChildSetupFunc}, used once for each process.
                 * @param pid_callback Callback for child processes
                 * @param stdin_fd file descriptor to use for child’s stdin, or `-1`
                 * @param stdout_fd file descriptor to use for child’s stdout, or `-1`
                 * @param stderr_fd file descriptor to use for child’s stderr, or `-1`
                 * @returns `TRUE` on successful launch, `FALSE` otherwise.
                 */
                launch_uris_as_manager_with_fds(uris: string[], launch_context: Gio.AppLaunchContext | null, spawn_flags: GLib.SpawnFlags, user_setup: GLib.SpawnChildSetupFunc | null, pid_callback: DesktopAppLaunchCallback | null, stdin_fd: number, stdout_fd: number, stderr_fd: number): boolean
                /**
                 * Returns the list of
                 * [‘additional application actions’](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s11.html)
                 * supported on the desktop file, as per the desktop file specification.
                 *
                 * As per the specification, this is the list of actions that are
                 * explicitly listed in the `Actions` key of the `Desktop Entry` group.
                 * @since 2.38
                 * @returns a   list of strings, always non-`NULL`
                 */
                list_actions(): string[]
            }

            interface DesktopAppInfoClass extends Omit<GObject.ObjectClass, "new"> {
                readonly $gtype: GObject.GType<DesktopAppInfo>
                readonly prototype: DesktopAppInfo

                new (props?: Partial<GObject.ConstructorProps<DesktopAppInfo>>): DesktopAppInfo
                /**
                 * Creates a new {@link GioUnix.DesktopAppInfo} based on a desktop file ID.
                 *
                 * A desktop file ID is the basename of the desktop file, including the
                 * `.desktop` extension. GIO is looking for a desktop file with this name
                 * in the `applications` subdirectories of the XDG
                 * data directories (i.e. the directories specified in the `XDG_DATA_HOME`
                 * and `XDG_DATA_DIRS` environment variables). GIO also supports the
                 * prefix-to-subdirectory mapping that is described in the
                 * [Menu Spec](http://standards.freedesktop.org/menu-spec/latest/)
                 * (i.e. a desktop ID of `kde-foo.desktop` will match
                 * `/usr/share/applications/kde/foo.desktop`).
                 * @param desktop_id the desktop file ID
                 * @returns a new {@link GioUnix.DesktopAppInfo}, or `NULL` if no    desktop file with that ID exists.
                 */
                "new"(desktop_id: string): DesktopAppInfo | null
                /**
                 * Creates a new {@link GioUnix.DesktopAppInfo}.
                 * @param filename the path of a desktop file, in the GLib      filename encoding
                 * @returns a new {@link GioUnix.DesktopAppInfo} or `NULL` on error.
                 */
                new_from_filename(filename: string): DesktopAppInfo | null
                /**
                 * Creates a new {@link GioUnix.DesktopAppInfo}.
                 * @since 2.18
                 * @param key_file an opened {@link GLib.KeyFile}
                 * @returns a new {@link GioUnix.DesktopAppInfo} or `NULL` on error.
                 */
                new_from_keyfile(key_file: GLib.KeyFile): DesktopAppInfo | null
                /**
                 * Gets all applications that implement `interface`.
                 *
                 * An application implements an interface if that interface is listed in
                 * the `Implements` line of the desktop file of the application.
                 * @since 2.42
                 * @param interface the name of the interface
                 * @returns a list of   {@link GioUnix.DesktopAppInfo} objects.
                 */
                get_implementations(interface: string): DesktopAppInfo[]
                /**
                 * Searches desktop files for ones that match `search_string`.
                 *
                 * The return value is an array of strvs.  Each strv contains a list of
                 * applications that matched `search_string` with an equal score.  The
                 * outer list is sorted by score so that the first strv contains the
                 * best-matching applications, and so on.
                 * The algorithm for determining matches is undefined and may change at
                 * any time.
                 *
                 * None of the search results are subjected to the normal validation
                 * checks performed by {@link GioUnix.DesktopAppInfo.new} (for example,
                 * checking that the executable referenced by a result exists), and so it is
                 * possible for {@link GioUnix.DesktopAppInfo.new} to return `NULL` when passed
                 * an app ID returned by this function. It is expected that calling code will
                 * do this when subsequently creating a {@link GioUnix.DesktopAppInfo} for
                 * each result.
                 * @param search_string the search string to use
                 * @returns a   list of strvs.  Free each item with {@link GLib.strfreev} and free the outer   list with {@link GLib.free}.
                 */
                search(search_string: string): string[][]
                /**
                 * Sets the name of the desktop that the application is running in.
                 *
                 * This is used by {@link Gio.AppInfo.should_show} and
                 * {@link GioUnix.DesktopAppInfo.get_show_in} to evaluate the
                 * [`OnlyShowIn`](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s06.html#key-onlyshowin)
                 * and [`NotShowIn`](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s06.html#key-notshowin)
                 * keys.
                 *
                 * Should be called only once; subsequent calls are ignored.
                 * @deprecated since 2.42 do not use this API.  Since 2.42 the value of the   `XDG_CURRENT_DESKTOP` environment variable will be used.
                 * @param desktop_env a string specifying what desktop this is
                 */
                set_desktop_env(desktop_env: string): void
            }

            interface $Exports {
                /**
                 * `GDesktopAppInfo` is an implementation of {@link Gio.AppInfo} based on
                 * desktop files.
                 *
                 * Note that `<gio/gdesktopappinfo.h>` belongs to the UNIX-specific
                 * GIO interfaces, thus you have to use the `gio-unix-2.0.pc` pkg-config
                 * file or the `GioUnix-2.0` GIR namespace when using it.
                 */
                DesktopAppInfo: DesktopAppInfoClass
            }
            

            namespace FDMessage {
                interface SignalSignatures extends Gio.SocketControlMessage.SignalSignatures {
                }

                interface ReadWriteProperties extends Gio.SocketControlMessage.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, Gio.SocketControlMessage.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, Gio.SocketControlMessage.WritableProperties {
                }

                interface ConstructOnlyProperties extends Gio.SocketControlMessage.ConstructOnlyProperties {
                    "fd-list": Gio.UnixFDList
                }
            }

            interface FDMessage extends Gio.SocketControlMessage {
                readonly $signals: FDMessage.SignalSignatures
                readonly $readableProperties: FDMessage.ReadableProperties
                readonly $writableProperties: FDMessage.WritableProperties
                readonly $constructOnlyProperties: FDMessage.ConstructOnlyProperties
                /**
                 * The {@link Gio.UnixFDList} object to send with the message.
                 * @since 2.22
                 */
                get fdList(): Gio.UnixFDList
                set fdList(value: Gio.UnixFDList)
                /**
                 * Adds a file descriptor to `message`.
                 *
                 * The file descriptor is duplicated using dup(). You keep your copy
                 * of the descriptor and the copy contained in `message` will be closed
                 * when `message` is finalized.
                 *
                 * A possible cause of failure is exceeding the per-process or
                 * system-wide file descriptor limit.
                 * @throws {GLib.Error}
                 * @since 2.22
                 * @param fd a valid open file descriptor
                 * @returns %TRUE in case of success, else %FALSE (and `error` is set)
                 */
                append_fd(fd: number): boolean
                /**
                 * Gets the #GUnixFDList contained in `message`.  This function does not
                 * return a reference to the caller, but the returned list is valid for
                 * the lifetime of `message`.
                 * @since 2.24
                 * @returns the #GUnixFDList from `message`
                 */
                get_fd_list(): Gio.UnixFDList
                /**
                 * Returns the array of file descriptors that is contained in this
                 * object.
                 *
                 * After this call, the descriptors are no longer contained in
                 *  `message`. Further calls will return an empty list (unless more
                 * descriptors have been added).
                 *
                 * The return result of this function must be freed with g_free().
                 * The caller is also responsible for closing all of the file
                 * descriptors.
                 *
                 * If `length` is non-%NULL then it is set to the number of file
                 * descriptors in the returned array. The returned array is also
                 * terminated with -1.
                 *
                 * This function never returns %NULL. In case there are no file
                 * descriptors contained in `message`, an empty array is returned.
                 * @since 2.22
                 * @returns an array of file     descriptors
                 */
                steal_fds(): number[]
            }

            interface FDMessageClass extends Omit<Gio.SocketControlMessageClass, "new"> {
                readonly $gtype: GObject.GType<FDMessage>
                readonly prototype: FDMessage

                new (props?: Partial<GObject.ConstructorProps<FDMessage>>): FDMessage
                /**
                 * Creates a new #GUnixFDMessage containing an empty file descriptor
                 * list.
                 * @since 2.22
                 * @returns a new #GUnixFDMessage
                 */
                "new"(): FDMessage
                /**
                 * Creates a new #GUnixFDMessage containing `list`.
                 * @since 2.24
                 * @param fd_list a #GUnixFDList
                 * @returns a new #GUnixFDMessage
                 */
                new_with_fd_list(fd_list: Gio.UnixFDList): FDMessage
            }

            interface $Exports {
                /**
                 * This {@link Gio.SocketControlMessage} contains a {@link Gio.UnixFDList}.
                 * It may be sent using {@link Gio.Socket.send_message} and received using
                 * {@link Gio.Socket.receive_message} over UNIX sockets (ie: sockets in the
                 * `G_SOCKET_FAMILY_UNIX` family). The file descriptors are copied
                 * between processes by the kernel.
                 *
                 * For an easier way to send and receive file descriptors over
                 * stream-oriented UNIX sockets, see {@link Gio.UnixConnection.send_fd} and
                 * {@link Gio.UnixConnection.receive_fd}.
                 *
                 * Note that `<gio/gunixfdmessage.h>` belongs to the UNIX-specific GIO
                 * interfaces, thus you have to use the `gio-unix-2.0.pc` pkg-config
                 * file or the `GioUnix-2.0` GIR namespace when using it.
                 */
                FDMessage: FDMessageClass
            }
            

            namespace InputStream {
                interface SignalSignatures extends Gio.InputStream.SignalSignatures, Gio.PollableInputStream.SignalSignatures, FileDescriptorBased.SignalSignatures {
                }

                interface ReadWriteProperties extends Gio.InputStream.ReadWriteProperties, Gio.PollableInputStream.ReadWriteProperties, FileDescriptorBased.ReadWriteProperties {
                    "close-fd": boolean
                }

                interface ReadableProperties extends ReadWriteProperties, Gio.InputStream.ReadableProperties, Gio.PollableInputStream.ReadableProperties, FileDescriptorBased.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, Gio.InputStream.WritableProperties, Gio.PollableInputStream.WritableProperties, FileDescriptorBased.WritableProperties {
                }

                interface ConstructOnlyProperties extends Gio.InputStream.ConstructOnlyProperties, Gio.PollableInputStream.ConstructOnlyProperties, FileDescriptorBased.ConstructOnlyProperties {
                    "fd": number
                }
            }

            interface InputStream extends Gio.InputStream, Gio.PollableInputStream, FileDescriptorBased {
                readonly $signals: InputStream.SignalSignatures
                readonly $readableProperties: InputStream.ReadableProperties
                readonly $writableProperties: InputStream.WritableProperties
                readonly $constructOnlyProperties: InputStream.ConstructOnlyProperties
                /**
                 * Whether to close the file descriptor when the stream is closed.
                 * @since 2.20
                 * @default TRUE
                 */
                get closeFd(): boolean
                set closeFd(value: boolean)
                /**
                 * The file descriptor that the stream reads from.
                 * @since 2.20
                 * @default -1
                 */
                get fd(): number
                set fd(value: number)
                /**
                 * Returns whether the file descriptor of `stream` will be
                 * closed when the stream is closed.
                 * @since 2.20
                 * @returns %TRUE if the file descriptor is closed when done
                 */
                get_close_fd(): boolean
                /**
                 * Return the UNIX file descriptor that the stream reads from.
                 * @since 2.20
                 * @returns The file descriptor of `stream`
                 */
                get_fd(): number
                /**
                 * Sets whether the file descriptor of `stream` shall be closed
                 * when the stream is closed.
                 * @since 2.20
                 * @param close_fd %TRUE to close the file descriptor when done
                 */
                set_close_fd(close_fd: boolean): void
            }

            interface InputStreamClass extends Omit<Gio.InputStreamClass, "new"> {
                readonly $gtype: GObject.GType<InputStream>
                readonly prototype: InputStream

                new (props?: Partial<GObject.ConstructorProps<InputStream>>): InputStream
                /**
                 * Creates a new #GUnixInputStream for the given `fd`.
                 *
                 * If `close_fd` is %TRUE, the file descriptor will be closed
                 * when the stream is closed.
                 * @param fd a UNIX file descriptor
                 * @param close_fd %TRUE to close the file descriptor when done
                 * @returns a new #GUnixInputStream
                 */
                "new"(fd: number, close_fd: boolean): InputStream
            }

            interface $Exports {
                /**
                 * `GUnixInputStream` implements {@link Gio.InputStream} for reading from a UNIX
                 * file descriptor, including asynchronous operations. (If the file
                 * descriptor refers to a socket or pipe, this will use `poll()` to do
                 * asynchronous I/O. If it refers to a regular file, it will fall back
                 * to doing asynchronous I/O in another thread.)
                 *
                 * Note that `<gio/gunixinputstream.h>` belongs to the UNIX-specific GIO
                 * interfaces, thus you have to use the `gio-unix-2.0.pc` pkg-config
                 * file or the `GioUnix-2.0` GIR namespace when using it.
                 */
                InputStream: InputStreamClass
            }
            

            namespace MountMonitor {
                interface SignalSignatures extends GObject.Object.SignalSignatures {
                    /**
                     * Emitted when the Unix mount points have changed.
                     */
                    "mountpoints-changed"(): void
                    /**
                     * Emitted when the Unix mount entries have changed.
                     */
                    "mounts-changed"(): void
                }

                interface ReadWriteProperties extends GObject.Object.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, GObject.Object.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, GObject.Object.WritableProperties {
                }

                interface ConstructOnlyProperties extends GObject.Object.ConstructOnlyProperties {
                }
            }

            interface MountMonitor extends GObject.Object {
                readonly $signals: MountMonitor.SignalSignatures
                readonly $readableProperties: MountMonitor.ReadableProperties
                readonly $writableProperties: MountMonitor.WritableProperties
                readonly $constructOnlyProperties: MountMonitor.ConstructOnlyProperties
                /**
                 * This function does nothing.
                 *
                 * Before 2.44, this was a partially-effective way of controlling the
                 * rate at which events would be reported under some uncommon
                 * circumstances.  Since `mount_monitor` is a singleton, it also meant
                 * that calling this function would have side effects for other users of
                 * the monitor.
                 * @since 2.18
                 * @deprecated since 2.44 This function does nothing. Don’t call it.
                 * @param limit_msec a integer with the limit (in milliseconds) to poll for changes
                 */
                set_rate_limit(limit_msec: number): void
            }

            interface MountMonitorClass extends Omit<GObject.ObjectClass, "new"> {
                readonly $gtype: GObject.GType<MountMonitor>
                readonly prototype: MountMonitor

                new (props?: Partial<GObject.ConstructorProps<MountMonitor>>): MountMonitor
                /**
                 * Deprecated alias for {@link GioUnix.MountMonitor.get}.
                 *
                 * This function was never a true constructor, which is why it was
                 * renamed.
                 * @deprecated since 2.44 Use {@link GioUnix.MountMonitor.get} instead.
                 * @returns a {@link GioUnix.MountMonitor}
                 */
                "new"(): MountMonitor
                /**
                 * Gets the {@link GioUnix.MountMonitor} for the current thread-default main
                 * context.
                 *
                 * The mount monitor can be used to monitor for changes to the list of
                 * mounted filesystems as well as the list of mount points (ie: fstab
                 * entries).
                 *
                 * You must only call {@link GObject.Object.unref} on the return value from
                 * under the same main context as you called this function.
                 * @since 2.44
                 * @returns the {@link GioUnix.MountMonitor}
                 */
                get(): MountMonitor
            }

            interface $Exports {
                /**
                 * Watches for changes to the set of mount entries and mount points in the
                 * system.
                 *
                 * Connect to the {@link GioUnix.MountMonitor.SignalSignatures["mounts-changed"]} signal to be
                 * notified of changes to the {@link GioUnix.MountEntry} list.
                 *
                 * Connect to the {@link GioUnix.MountMonitor.SignalSignatures["mountpoints-changed"]} signal to
                 * be notified of changes to the {@link GioUnix.MountPoint} list.
                 */
                MountMonitor: MountMonitorClass
            }
            

            namespace OutputStream {
                interface SignalSignatures extends Gio.OutputStream.SignalSignatures, Gio.PollableOutputStream.SignalSignatures, FileDescriptorBased.SignalSignatures {
                }

                interface ReadWriteProperties extends Gio.OutputStream.ReadWriteProperties, Gio.PollableOutputStream.ReadWriteProperties, FileDescriptorBased.ReadWriteProperties {
                    "close-fd": boolean
                }

                interface ReadableProperties extends ReadWriteProperties, Gio.OutputStream.ReadableProperties, Gio.PollableOutputStream.ReadableProperties, FileDescriptorBased.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, Gio.OutputStream.WritableProperties, Gio.PollableOutputStream.WritableProperties, FileDescriptorBased.WritableProperties {
                }

                interface ConstructOnlyProperties extends Gio.OutputStream.ConstructOnlyProperties, Gio.PollableOutputStream.ConstructOnlyProperties, FileDescriptorBased.ConstructOnlyProperties {
                    "fd": number
                }
            }

            interface OutputStream extends Gio.OutputStream, Gio.PollableOutputStream, FileDescriptorBased {
                readonly $signals: OutputStream.SignalSignatures
                readonly $readableProperties: OutputStream.ReadableProperties
                readonly $writableProperties: OutputStream.WritableProperties
                readonly $constructOnlyProperties: OutputStream.ConstructOnlyProperties
                /**
                 * Whether to close the file descriptor when the stream is closed.
                 * @since 2.20
                 * @default TRUE
                 */
                get closeFd(): boolean
                set closeFd(value: boolean)
                /**
                 * The file descriptor that the stream writes to.
                 * @since 2.20
                 * @default -1
                 */
                get fd(): number
                set fd(value: number)
                /**
                 * Returns whether the file descriptor of `stream` will be
                 * closed when the stream is closed.
                 * @since 2.20
                 * @returns %TRUE if the file descriptor is closed when done
                 */
                get_close_fd(): boolean
                /**
                 * Return the UNIX file descriptor that the stream writes to.
                 * @since 2.20
                 * @returns The file descriptor of `stream`
                 */
                get_fd(): number
                /**
                 * Sets whether the file descriptor of `stream` shall be closed
                 * when the stream is closed.
                 * @since 2.20
                 * @param close_fd %TRUE to close the file descriptor when done
                 */
                set_close_fd(close_fd: boolean): void
            }

            interface OutputStreamClass extends Omit<Gio.OutputStreamClass, "new"> {
                readonly $gtype: GObject.GType<OutputStream>
                readonly prototype: OutputStream

                new (props?: Partial<GObject.ConstructorProps<OutputStream>>): OutputStream
                /**
                 * Creates a new #GUnixOutputStream for the given `fd`.
                 *
                 * If `close_fd`, is %TRUE, the file descriptor will be closed when
                 * the output stream is destroyed.
                 * @param fd a UNIX file descriptor
                 * @param close_fd %TRUE to close the file descriptor when done
                 * @returns a new #GOutputStream
                 */
                "new"(fd: number, close_fd: boolean): OutputStream
            }

            interface $Exports {
                /**
                 * `GUnixOutputStream` implements {@link Gio.OutputStream} for writing to a UNIX
                 * file descriptor, including asynchronous operations. (If the file
                 * descriptor refers to a socket or pipe, this will use `poll()` to do
                 * asynchronous I/O. If it refers to a regular file, it will fall back
                 * to doing asynchronous I/O in another thread.)
                 *
                 * Note that `<gio/gunixoutputstream.h>` belongs to the UNIX-specific GIO
                 * interfaces, thus you have to use the `gio-unix-2.0.pc` pkg-config file
                 * file or the `GioUnix-2.0` GIR namespace when using it.
                 */
                OutputStream: OutputStreamClass
            }
            

            namespace DesktopAppInfoLookup {
                interface SignalSignatures extends GObject.Object.SignalSignatures {
                }

                interface ReadWriteProperties extends GObject.Object.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, GObject.Object.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, GObject.Object.WritableProperties {
                }

                interface ConstructOnlyProperties extends GObject.Object.ConstructOnlyProperties {
                }

                interface Interface extends GObject.Object {
                    /**
                     * Gets the default application for launching applications
                     * using this URI scheme for a particular {@link GioUnix.DesktopAppInfoLookup}
                     * implementation.
                     *
                     * The {@link GioUnix.DesktopAppInfoLookup} interface and this function is used
                     * to implement {@link Gio.AppInfo.get_default_for_uri_scheme} backends
                     * in a GIO module. There is no reason for applications to use it
                     * directly. Applications should use
                     * {@link Gio.AppInfo.get_default_for_uri_scheme}.
                     * @deprecated since 2.28 The {@link GioUnix.DesktopAppInfoLookup} interface is   deprecated and unused by GIO.
                     * @param uri_scheme a string containing a URI scheme.
                     * @returns {@link Gio.AppInfo} for given   `uri_scheme` or `NULL` on error.
                     */
                    vfunc_get_default_for_uri_scheme(uri_scheme: string): Gio.AppInfo | null
                }
            }

            interface DesktopAppInfoLookup extends GObject.Object, DesktopAppInfoLookup.Interface {
                readonly $signals: DesktopAppInfoLookup.SignalSignatures
                readonly $readableProperties: DesktopAppInfoLookup.ReadableProperties
                readonly $writableProperties: DesktopAppInfoLookup.WritableProperties
                readonly $constructOnlyProperties: DesktopAppInfoLookup.ConstructOnlyProperties
                /**
                 * Gets the default application for launching applications
                 * using this URI scheme for a particular {@link GioUnix.DesktopAppInfoLookup}
                 * implementation.
                 *
                 * The {@link GioUnix.DesktopAppInfoLookup} interface and this function is used
                 * to implement {@link Gio.AppInfo.get_default_for_uri_scheme} backends
                 * in a GIO module. There is no reason for applications to use it
                 * directly. Applications should use
                 * {@link Gio.AppInfo.get_default_for_uri_scheme}.
                 * @deprecated since 2.28 The {@link GioUnix.DesktopAppInfoLookup} interface is   deprecated and unused by GIO.
                 * @param uri_scheme a string containing a URI scheme.
                 * @returns {@link Gio.AppInfo} for given   `uri_scheme` or `NULL` on error.
                 */
                get_default_for_uri_scheme(uri_scheme: string): Gio.AppInfo | null
            }

            interface DesktopAppInfoLookupIface {
                readonly $gtype: GObject.GType<DesktopAppInfoLookup>
                readonly prototype: DesktopAppInfoLookup
                [Symbol.hasInstance](instance: unknown): instance is DesktopAppInfoLookup
            }

            interface $Exports {
                /**
                 * #GDesktopAppInfoLookup is an opaque data structure and can only be accessed
                 * using the following functions.
                 * @deprecated since 2.28 The {@link GioUnix.DesktopAppInfoLookup} interface is   deprecated and unused by GIO.
                 */
                DesktopAppInfoLookup: DesktopAppInfoLookupIface
            }
            

            namespace FileDescriptorBased {
                interface SignalSignatures extends GObject.Object.SignalSignatures {
                }

                interface ReadWriteProperties extends GObject.Object.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, GObject.Object.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, GObject.Object.WritableProperties {
                }

                interface ConstructOnlyProperties extends GObject.Object.ConstructOnlyProperties {
                }

                interface Interface extends GObject.Object {
                    /**
                     * Gets the underlying file descriptor.
                     * @since 2.24
                     * @returns The file descriptor
                     */
                    vfunc_get_fd(): number
                }
            }

            interface FileDescriptorBased extends GObject.Object, FileDescriptorBased.Interface {
                readonly $signals: FileDescriptorBased.SignalSignatures
                readonly $readableProperties: FileDescriptorBased.ReadableProperties
                readonly $writableProperties: FileDescriptorBased.WritableProperties
                readonly $constructOnlyProperties: FileDescriptorBased.ConstructOnlyProperties
                /**
                 * Gets the underlying file descriptor.
                 * @since 2.24
                 * @returns The file descriptor
                 */
                get_fd(): number
            }

            interface FileDescriptorBasedIface {
                readonly $gtype: GObject.GType<FileDescriptorBased>
                readonly prototype: FileDescriptorBased
                [Symbol.hasInstance](instance: unknown): instance is FileDescriptorBased
            }

            interface $Exports {
                /**
                 * `GFileDescriptorBased` is an interface for file descriptor based IO.
                 *
                 * It is implemented by streams (implementations of {@link Gio.InputStream} or
                 * {@link Gio.OutputStream}) that are based on file descriptors.
                 *
                 * Note that `<gio/gfiledescriptorbased.h>` belongs to the UNIX-specific
                 * GIO interfaces, thus you have to use the `gio-unix-2.0.pc` pkg-config
                 * file or the `GioUnix-2.0` GIR namespace when using it.
                 * @since 2.24
                 */
                FileDescriptorBased: FileDescriptorBasedIface
            }
            

            interface FDMessagePrivateStruct {
                readonly $gtype: GObject.GType<FDMessagePrivate>
                [Symbol.hasInstance](instance: unknown): instance is FDMessagePrivate
            }

            interface FDMessagePrivate {
            }

            interface $Exports {
                FDMessagePrivate: FDMessagePrivateStruct
            }
            

            interface InputStreamPrivateStruct {
                readonly $gtype: GObject.GType<InputStreamPrivate>
                [Symbol.hasInstance](instance: unknown): instance is InputStreamPrivate
            }

            interface InputStreamPrivate {
            }

            interface $Exports {
                InputStreamPrivate: InputStreamPrivateStruct
            }
            

            interface MountEntryStruct {
                readonly $gtype: GObject.GType<MountEntry>
                [Symbol.hasInstance](instance: unknown): instance is MountEntry
                /**
                 * Gets a {@link GioUnix.MountEntry} for a given mount path.
                 *
                 * If `time_read` is set, it will be filled with a Unix timestamp for checking
                 * if the mounts have changed since with
                 * {@link GioUnix.mount_entries_changed_since}.
                 *
                 * If more mounts have the same mount path, the last matching mount
                 * is returned.
                 *
                 * This will return `NULL` if there is no mount point at `mount_path`.
                 * @since 2.84
                 * @param mount_path path for a possible Unix mount
                 * @returns a {@link GioUnix.MountEntry}, return location for a timestamp
                 */
                at(mount_path: string): [MountEntry | null, number]
                /**
                 * Gets a {@link GioUnix.MountEntry} for a given file path.
                 *
                 * If `time_read` is set, it will be filled with a Unix timestamp for checking
                 * if the mounts have changed since with
                 * {@link GioUnix.mount_entries_changed_since}.
                 *
                 * If more mounts have the same mount path, the last matching mount
                 * is returned.
                 *
                 * This will return `NULL` if looking up the mount entry fails, if
                 *  `file_path` doesn’t exist or there is an I/O error.
                 * @since 2.84
                 * @param file_path file path on some Unix mount
                 * @returns a {@link GioUnix.MountEntry}, return location for a timestamp
                 */
                for(file_path: string): [MountEntry | null, number]
            }

            interface MountEntry {
                /**
                 * Compares two Unix mounts.
                 * @since 2.84
                 * @param mount2 second {@link GioUnix.MountEntry} to compare
                 * @returns `1`, `0` or `-1` if `mount1` is greater than, equal to,    or less than `mount2`, respectively
                 */
                compare(mount2: MountEntry): number
                /**
                 * Makes a copy of `mount_entry`.
                 * @since 2.84
                 * @returns a new {@link GioUnix.MountEntry}
                 */
                copy(): MountEntry
                /**
                 * Frees a Unix mount.
                 * @since 2.84
                 */
                free(): void
                /**
                 * Gets the device path for a Unix mount.
                 * @since 2.84
                 * @returns a string containing the device path
                 */
                get_device_path(): string
                /**
                 * Gets the filesystem type for the Unix mount.
                 * @since 2.84
                 * @returns a string containing the file system type
                 */
                get_fs_type(): string
                /**
                 * Gets the mount path for a Unix mount.
                 * @since 2.84
                 * @returns the mount path for `mount_entry`
                 */
                get_mount_path(): string
                /**
                 * Gets a comma separated list of mount options for the Unix mount.
                 *
                 * For example: `rw,relatime,seclabel,data=ordered`.
                 *
                 * This is similar to {@link GioUnix.MountPoint.get_options}, but it takes
                 * a {@link GioUnix.MountEntry} as an argument.
                 * @since 2.84
                 * @returns a string containing the options, or `NULL` if not    available.
                 */
                get_options(): string | null
                /**
                 * Gets the root of the mount within the filesystem. This is useful e.g. for
                 * mounts created by bind operation, or btrfs subvolumes.
                 *
                 * For example, the root path is equal to `/` for a mount created by
                 * `mount /dev/sda1 /mnt/foo` and `/bar` for
                 * `mount --bind /mnt/foo/bar /mnt/bar`.
                 * @since 2.84
                 * @returns a string containing the root, or `NULL` if not supported
                 */
                get_root_path(): string | null
                /**
                 * Guesses whether a Unix mount entry can be ejected.
                 * @since 2.84
                 * @returns true if `mount_entry` is deemed to be ejectable; false otherwise
                 */
                guess_can_eject(): boolean
                /**
                 * Guesses the icon of a Unix mount entry.
                 * @since 2.84
                 * @returns a {@link Gio.Icon}
                 */
                guess_icon(): Gio.Icon
                /**
                 * Guesses the name of a Unix mount entry.
                 *
                 * The result is a translated string.
                 * @since 2.84
                 * @returns a newly allocated translated string
                 */
                guess_name(): string
                /**
                 * Guesses whether a Unix mount entry should be displayed in the UI.
                 * @since 2.84
                 * @returns true if `mount_entry` is deemed to be displayable; false otherwise
                 */
                guess_should_display(): boolean
                /**
                 * Guesses the symbolic icon of a Unix mount entry.
                 * @since 2.84
                 * @returns a {@link Gio.Icon}
                 */
                guess_symbolic_icon(): Gio.Icon
                /**
                 * Checks if a Unix mount is mounted read only.
                 * @since 2.84
                 * @returns true if `mount_entry` is read only; false otherwise
                 */
                is_readonly(): boolean
                /**
                 * Checks if a Unix mount is a system mount.
                 *
                 * This is the Boolean OR of
                 * {@link GioUnix.is_system_fs_type}, {@link GioUnix.is_system_device_path} and
                 * {@link GioUnix.is_mount_path_system_internal} on `mount_entry`’s properties.
                 *
                 * The definition of what a ‘system’ mount entry is may change over time as new
                 * file system types and device paths are ignored.
                 * @since 2.84
                 * @returns true if the Unix mount is for a system path; false otherwise
                 */
                is_system_internal(): boolean
            }

            interface $Exports {
                MountEntry: MountEntryStruct
            }
            

            interface MountPointStruct {
                readonly $gtype: GObject.GType<MountPoint>
                [Symbol.hasInstance](instance: unknown): instance is MountPoint
                /**
                 * Gets a {@link GioUnix.MountPoint} for a given mount path.
                 *
                 * If `time_read` is set, it will be filled with a Unix timestamp for checking if
                 * the mount points have changed since with
                 * {@link GioUnix.mount_points_changed_since}.
                 *
                 * If more mount points have the same mount path, the last matching mount point
                 * is returned.
                 * @since 2.66
                 * @param mount_path path for a possible Unix mount point
                 * @returns a {@link GioUnix.MountPoint}, or `NULL`    if no match is found, return location for a timestamp
                 */
                at(mount_path: string): [MountPoint | null, number]
            }

            interface MountPoint {
                /**
                 * Compares two Unix mount points.
                 * @param mount2 a {@link GioUnix.MountPoint}
                 * @returns `1`, `0` or `-1` if `mount1` is greater than, equal to,    or less than `mount2`, respectively
                 */
                compare(mount2: MountPoint): number
                /**
                 * Makes a copy of `mount_point`.
                 * @since 2.54
                 * @returns a new {@link GioUnix.MountPoint}
                 */
                copy(): MountPoint
                /**
                 * Frees a Unix mount point.
                 */
                free(): void
                /**
                 * Gets the device path for a Unix mount point.
                 * @returns a string containing the device path
                 */
                get_device_path(): string
                /**
                 * Gets the file system type for the mount point.
                 * @returns a string containing the file system type
                 */
                get_fs_type(): string
                /**
                 * Gets the mount path for a Unix mount point.
                 * @returns a string containing the mount path
                 */
                get_mount_path(): string
                /**
                 * Gets the options for the mount point.
                 * @since 2.32
                 * @returns a string containing the options
                 */
                get_options(): string | null
                /**
                 * Guesses whether a Unix mount point can be ejected.
                 * @returns true if `mount_point` is deemed to be ejectable; false otherwise
                 */
                guess_can_eject(): boolean
                /**
                 * Guesses the icon of a Unix mount point.
                 * @returns a {@link Gio.Icon}
                 */
                guess_icon(): Gio.Icon
                /**
                 * Guesses the name of a Unix mount point.
                 *
                 * The result is a translated string.
                 * @returns a newly allocated translated string
                 */
                guess_name(): string
                /**
                 * Guesses the symbolic icon of a Unix mount point.
                 * @since 2.34
                 * @returns a {@link Gio.Icon}
                 */
                guess_symbolic_icon(): Gio.Icon
                /**
                 * Checks if a Unix mount point is a loopback device.
                 * @returns true if the mount point is a loopback device; false otherwise
                 */
                is_loopback(): boolean
                /**
                 * Checks if a Unix mount point is read only.
                 * @returns true if a mount point is read only; false otherwise
                 */
                is_readonly(): boolean
                /**
                 * Checks if a Unix mount point is mountable by the user.
                 * @returns true if the mount point is user mountable; false otherwise
                 */
                is_user_mountable(): boolean
            }

            interface $Exports {
                MountPoint: MountPointStruct
            }
            

            interface OutputStreamPrivateStruct {
                readonly $gtype: GObject.GType<OutputStreamPrivate>
                [Symbol.hasInstance](instance: unknown): instance is OutputStreamPrivate
            }

            interface OutputStreamPrivate {
            }

            interface $Exports {
                OutputStreamPrivate: OutputStreamPrivateStruct
            }
            /**
             * During invocation, g_desktop_app_info_launch_uris_as_manager() may
             * create one or more child processes.  This callback is invoked once
             * for each, providing the process ID.
             * @param appinfo a #GDesktopAppInfo
             * @param pid Process identifier
             */
            type DesktopAppLaunchCallback = (appinfo: DesktopAppInfo, pid: GLib.Pid) => void

            interface $Exports {
                __name__: "GioUnix"
                __version__: "2.0"
                DESKTOP_APP_INFO_LOOKUP_EXTENSION_POINT_NAME: "gio-desktop-app-info-lookup"
                /**
                 * Determines if `mount_path` is considered an implementation of the
                 * OS.
                 *
                 * This is primarily used for hiding mountable and mounted volumes
                 * that only are used in the OS and has little to no relevance to the
                 * casual user.
                 * @param mount_path a mount path, e.g. `/media/disk` or `/usr`
                 * @returns true if `mount_path` is considered an implementation detail    of the OS; false otherwise
                 */
                is_mount_path_system_internal(mount_path: string): boolean
                /**
                 * Determines if `device_path` is considered a block device path which is only
                 * used in implementation of the OS.
                 *
                 * This is primarily used for hiding mounted volumes that are intended as APIs
                 * for programs to read, and system administrators at a shell; rather than
                 * something that should, for example, appear in a GUI. For example, the Linux
                 * `/proc` filesystem.
                 *
                 * The list of device paths considered ‘system’ ones may change over time.
                 * @since 2.56
                 * @param device_path a device path, e.g. `/dev/loop0` or `nfsd`
                 * @returns true if `device_path` is considered an implementation detail of    the OS; false otherwise
                 */
                is_system_device_path(device_path: string): boolean
                /**
                 * Determines if `fs_type` is considered a type of file system which is only
                 * used in implementation of the OS.
                 *
                 * This is primarily used for hiding mounted volumes that are intended as APIs
                 * for programs to read, and system administrators at a shell; rather than
                 * something that should, for example, appear in a GUI. For example, the Linux
                 * `/proc` filesystem.
                 *
                 * The list of file system types considered ‘system’ ones may change over time.
                 * @since 2.56
                 * @param fs_type a file system type, e.g. `procfs` or `tmpfs`
                 * @returns true if `fs_type` is considered an implementation detail of the OS;    false otherwise
                 */
                is_system_fs_type(fs_type: string): boolean
                /**
                 * Gets a {@link GioUnix.MountEntry} for a given mount path.
                 *
                 * If `time_read` is set, it will be filled with a Unix timestamp for checking
                 * if the mounts have changed since with
                 * {@link GioUnix.mount_entries_changed_since}.
                 *
                 * If more mounts have the same mount path, the last matching mount
                 * is returned.
                 *
                 * This will return `NULL` if there is no mount point at `mount_path`.
                 * @deprecated since 2.84 Use {@link GioUnix.MountEntry.at} instead.
                 * @param mount_path path for a possible Unix mount
                 * @returns a {@link GioUnix.MountEntry}, return location for a timestamp
                 */
                mount_at(mount_path: string): [MountEntry | null, number]
                /**
                 * Compares two Unix mounts.
                 * @deprecated since 2.84 Use {@link GioUnix.MountEntry.compare} instead.
                 * @param mount1 first {@link GioUnix.MountEntry} to compare
                 * @param mount2 second {@link GioUnix.MountEntry} to compare
                 * @returns `1`, `0` or `-1` if `mount1` is greater than, equal to,    or less than `mount2`, respectively
                 */
                mount_compare(mount1: MountEntry, mount2: MountEntry): number
                /**
                 * Makes a copy of `mount_entry`.
                 * @since 2.54
                 * @deprecated since 2.84 Use {@link GioUnix.MountEntry.copy} instead.
                 * @param mount_entry a {@link GioUnix.MountEntry}
                 * @returns a new {@link GioUnix.MountEntry}
                 */
                mount_copy(mount_entry: MountEntry): MountEntry
                /**
                 * Checks if the Unix mounts have changed since a given Unix time.
                 *
                 * This can only work reliably if a {@link GioUnix.MountMonitor} is running in
                 * the process, otherwise changes in the mount entries file (such as
                 * `/proc/self/mountinfo` on Linux) cannot be detected and, as a result, this
                 * function has to conservatively always return `TRUE`.
                 *
                 * It is more efficient to use {@link GioUnix.MountMonitor.SignalSignatures["mounts-changed"]} to
                 * be signalled of changes to the mount entries, rather than polling using this
                 * function. This function is more appropriate for infrequently determining
                 * cache validity.
                 * @param time a timestamp
                 * @returns true if the mounts have changed since `time`; false otherwise Since 2.84
                 */
                mount_entries_changed_since(time: number): boolean
                /**
                 * Gets a list of {@link GioUnix.MountEntry} instances representing the Unix
                 * mounts.
                 *
                 * If `time_read` is set, it will be filled with the mount timestamp, allowing
                 * for checking if the mounts have changed with
                 * {@link GioUnix.mount_entries_changed_since}.
                 * @since 2.84
                 * @returns a list of the    Unix mounts, return location for a timestamp
                 */
                mount_entries_get(): [MountEntry[], number]
                /**
                 * Gets an array of {@link GioUnix.MountEntry}s containing the Unix mounts
                 * listed in `table_path`.
                 *
                 * This is a generalized version of {@link GioUnix.mount_entries_get}, mainly
                 * intended for internal testing use. Note that {@link GioUnix.mount_entries_get}
                 * may parse multiple hierarchical table files, so this function is not a direct
                 * superset of its functionality.
                 *
                 * If there is an error reading or parsing the file, `NULL` will be returned
                 * and both out parameters will be set to `0`.
                 * @since 2.84
                 * @param table_path path to the mounts table file (for example `/proc/self/mountinfo`)
                 * @returns mount   entries, or `NULL` if there was an error loading them, return location for the   modification time of `table_path`
                 */
                mount_entries_get_from_file(table_path: string): [MountEntry[] | null, number]
                /**
                 * Gets a {@link GioUnix.MountEntry} for a given mount path.
                 *
                 * If `time_read` is set, it will be filled with a Unix timestamp for checking
                 * if the mounts have changed since with
                 * {@link GioUnix.mount_entries_changed_since}.
                 *
                 * If more mounts have the same mount path, the last matching mount
                 * is returned.
                 *
                 * This will return `NULL` if there is no mount point at `mount_path`.
                 * @since 2.84
                 * @param mount_path path for a possible Unix mount
                 * @returns a {@link GioUnix.MountEntry}, return location for a timestamp
                 */
                mount_entry_at(mount_path: string): [MountEntry | null, number]
                /**
                 * Gets a {@link GioUnix.MountEntry} for a given file path.
                 *
                 * If `time_read` is set, it will be filled with a Unix timestamp for checking
                 * if the mounts have changed since with
                 * {@link GioUnix.mount_entries_changed_since}.
                 *
                 * If more mounts have the same mount path, the last matching mount
                 * is returned.
                 *
                 * This will return `NULL` if looking up the mount entry fails, if
                 *  `file_path` doesn’t exist or there is an I/O error.
                 * @since 2.84
                 * @param file_path file path on some Unix mount
                 * @returns a {@link GioUnix.MountEntry}, return location for a timestamp
                 */
                mount_entry_for(file_path: string): [MountEntry | null, number]
                /**
                 * Gets a {@link GioUnix.MountEntry} for a given file path.
                 *
                 * If `time_read` is set, it will be filled with a Unix timestamp for checking
                 * if the mounts have changed since with
                 * {@link GioUnix.mount_entries_changed_since}.
                 *
                 * If more mounts have the same mount path, the last matching mount
                 * is returned.
                 *
                 * This will return `NULL` if looking up the mount entry fails, if
                 *  `file_path` doesn’t exist or there is an I/O error.
                 * @since 2.52
                 * @deprecated since 2.84 Use {@link GioUnix.MountEntry.for} instead.
                 * @param file_path file path on some Unix mount
                 * @returns a {@link GioUnix.MountEntry}, return location for a timestamp
                 */
                mount_for(file_path: string): [MountEntry | null, number]
                /**
                 * Frees a Unix mount.
                 * @deprecated since 2.84 Use {@link GioUnix.MountEntry.free} instead.
                 * @param mount_entry a {@link GioUnix.MountEntry}
                 */
                mount_free(mount_entry: MountEntry): void
                /**
                 * Gets the device path for a Unix mount.
                 * @deprecated since 2.84 Use {@link GioUnix.MountEntry.get_device_path} instead.
                 * @param mount_entry a {@link GioUnix.MountEntry}
                 * @returns a string containing the device path
                 */
                mount_get_device_path(mount_entry: MountEntry): string
                /**
                 * Gets the filesystem type for the Unix mount.
                 * @deprecated since 2.84 Use {@link GioUnix.MountEntry.get_fs_type} instead.
                 * @param mount_entry a {@link GioUnix.MountEntry}
                 * @returns a string containing the file system type
                 */
                mount_get_fs_type(mount_entry: MountEntry): string
                /**
                 * Gets the mount path for a Unix mount.
                 * @deprecated since 2.84 Use {@link GioUnix.MountEntry.get_mount_path} instead.
                 * @param mount_entry a {@link GioUnix.MountEntry} to get the mount path for
                 * @returns the mount path for `mount_entry`
                 */
                mount_get_mount_path(mount_entry: MountEntry): string
                /**
                 * Gets a comma separated list of mount options for the Unix mount.
                 *
                 * For example: `rw,relatime,seclabel,data=ordered`.
                 *
                 * This is similar to {@link GioUnix.MountPoint.get_options}, but it takes
                 * a {@link GioUnix.MountEntry} as an argument.
                 * @since 2.58
                 * @deprecated since 2.84 Use {@link GioUnix.MountEntry.get_options} instead.
                 * @param mount_entry a {@link GioUnix.MountEntry}
                 * @returns a string containing the options, or `NULL` if not    available.
                 */
                mount_get_options(mount_entry: MountEntry): string | null
                /**
                 * Gets the root of the mount within the filesystem.
                 *
                 * This is useful e.g. for mounts created by bind operation, or btrfs subvolumes.
                 *
                 * For example, the root path is equal to `/` for a mount created by
                 * `mount /dev/sda1 /mnt/foo` and `/bar` for
                 * `mount --bind /mnt/foo/bar /mnt/bar`.
                 * @since 2.60
                 * @deprecated since 2.84 Use {@link GioUnix.MountEntry.get_root_path} instead.
                 * @param mount_entry a {@link GioUnix.MountEntry}
                 * @returns a string containing the root, or `NULL` if not supported
                 */
                mount_get_root_path(mount_entry: MountEntry): string | null
                /**
                 * Guesses whether a Unix mount entry can be ejected.
                 * @deprecated since 2.84 Use {@link GioUnix.MountEntry.guess_can_eject} instead.
                 * @param mount_entry a {@link GioUnix.MountEntry}
                 * @returns true if `mount_entry` is deemed to be ejectable; false otherwise
                 */
                mount_guess_can_eject(mount_entry: MountEntry): boolean
                /**
                 * Guesses the icon of a Unix mount entry.
                 * @deprecated since 2.84 Use {@link GioUnix.MountEntry.guess_icon} instead.
                 * @param mount_entry a {@link GioUnix.MountEntry}
                 * @returns a {@link Gio.Icon}
                 */
                mount_guess_icon(mount_entry: MountEntry): Gio.Icon
                /**
                 * Guesses the name of a Unix mount entry.
                 *
                 * The result is a translated string.
                 * @deprecated since 2.84 Use {@link GioUnix.MountEntry.guess_name} instead.
                 * @param mount_entry a {@link GioUnix.MountEntry}
                 * @returns a newly allocated translated string
                 */
                mount_guess_name(mount_entry: MountEntry): string
                /**
                 * Guesses whether a Unix mount entry should be displayed in the UI.
                 * @deprecated since 2.84 Use {@link GioUnix.MountEntry.guess_should_display} instead.
                 * @param mount_entry a {@link GioUnix.MountEntry}
                 * @returns true if `mount_entry` is deemed to be displayable; false otherwise
                 */
                mount_guess_should_display(mount_entry: MountEntry): boolean
                /**
                 * Guesses the symbolic icon of a Unix mount entry.
                 * @since 2.34
                 * @deprecated since 2.84 Use {@link GioUnix.MountEntry.guess_symbolic_icon} instead.
                 * @param mount_entry a {@link GioUnix.MountEntry}
                 * @returns a {@link Gio.Icon}
                 */
                mount_guess_symbolic_icon(mount_entry: MountEntry): Gio.Icon
                /**
                 * Checks if a Unix mount is mounted read only.
                 * @deprecated since 2.84 Use {@link GioUnix.MountEntry.is_readonly} instead.
                 * @param mount_entry a {@link GioUnix.MountEntry}
                 * @returns true if `mount_entry` is read only; false otherwise
                 */
                mount_is_readonly(mount_entry: MountEntry): boolean
                /**
                 * Checks if a Unix mount is a system mount.
                 *
                 * This is the Boolean OR of
                 * {@link GioUnix.is_system_fs_type}, {@link GioUnix.is_system_device_path} and
                 * {@link GioUnix.is_mount_path_system_internal} on `mount_entry`’s properties.
                 *
                 * The definition of what a ‘system’ mount entry is may change over time as new
                 * file system types and device paths are ignored.
                 * @deprecated since 2.84 Use {@link GioUnix.MountEntry.is_system_internal} instead.
                 * @param mount_entry a {@link GioUnix.MountEntry}
                 * @returns true if the Unix mount is for a system path; false otherwise
                 */
                mount_is_system_internal(mount_entry: MountEntry): boolean
                /**
                 * Gets a {@link GioUnix.MountPoint} for a given mount path.
                 *
                 * If `time_read` is set, it will be filled with a Unix timestamp for checking if
                 * the mount points have changed since with
                 * {@link GioUnix.mount_points_changed_since}.
                 *
                 * If more mount points have the same mount path, the last matching mount point
                 * is returned.
                 * @since 2.66
                 * @param mount_path path for a possible Unix mount point
                 * @returns a {@link GioUnix.MountPoint}, or `NULL`    if no match is found, return location for a timestamp
                 */
                mount_point_at(mount_path: string): [MountPoint | null, number]
                /**
                 * Checks if the Unix mount points have changed since a given Unix time.
                 *
                 * Unlike {@link GioUnix.mount_entries_changed_since}, this function can work
                 * reliably without a {@link GioUnix.MountMonitor} running, as it accesses the
                 * static mount point information (such as `/etc/fstab` on Linux), which has a
                 * valid modification time.
                 *
                 * It is more efficient to use {@link GioUnix.MountMonitor.SignalSignatures["mountpoints-changed"]}
                 * to be signalled of changes to the mount points, rather than polling using
                 * this function. This function is more appropriate for infrequently determining
                 * cache validity.
                 * @param time a timestamp
                 * @returns true if the mount points have changed since `time`; false otherwise
                 */
                mount_points_changed_since(time: number): boolean
                /**
                 * Gets a list of {@link GioUnix.MountPoint} instances representing the Unix
                 * mount points.
                 *
                 * If `time_read` is set, it will be filled with the mount timestamp, allowing
                 * for checking if the mounts have changed with
                 * {@link GioUnix.mount_points_changed_since}.
                 * @returns a list of the Unix    mount points, return location for a timestamp
                 */
                mount_points_get(): [MountPoint[], number]
                /**
                 * Gets an array of {@link GioUnix.MountPoint}s containing the Unix mount
                 * points listed in `table_path`.
                 *
                 * This is a generalized version of {@link GioUnix.mount_points_get}, mainly
                 * intended for internal testing use. Note that {@link GioUnix.mount_points_get}
                 * may parse multiple hierarchical table files, so this function is not a direct
                 * superset of its functionality.
                 *
                 * If there is an error reading or parsing the file, `NULL` will be returned
                 * and both out parameters will be set to `0`.
                 * @since 2.82
                 * @param table_path path to the mount points table file (for example `/etc/fstab`)
                 * @returns mount   points, or `NULL` if there was an error loading them, return location for the   modification time of `table_path`
                 */
                mount_points_get_from_file(table_path: string): [MountPoint[] | null, number]
                /**
                 * Checks if the Unix mounts have changed since a given Unix time.
                 * @deprecated since 2.84 Use {@link GioUnix.mount_entries_changed_since} instead.
                 * @param time a timestamp
                 * @returns true if the mounts have changed since `time`; false otherwise
                 */
                mounts_changed_since(time: number): boolean
                /**
                 * Gets a list of {@link GioUnix.MountEntry} instances representing the Unix
                 * mounts.
                 *
                 * If `time_read` is set, it will be filled with the mount timestamp, allowing
                 * for checking if the mounts have changed with
                 * {@link GioUnix.mount_entries_changed_since}.
                 * @deprecated since 2.84 Use {@link GioUnix.mount_entries_get} instead.
                 * @returns a list of the    Unix mounts, return location for a timestamp
                 */
                mounts_get(): [MountEntry[], number]
                /**
                 * Gets an array of {@link GioUnix.MountEntry}s containing the Unix mounts
                 * listed in `table_path`.
                 *
                 * This is a generalized version of {@link GioUnix.mount_entries_get}, mainly
                 * intended for internal testing use. Note that {@link GioUnix.mount_entries_get}
                 * may parse multiple hierarchical table files, so this function is not a direct
                 * superset of its functionality.
                 *
                 * If there is an error reading or parsing the file, `NULL` will be returned
                 * and both out parameters will be set to `0`.
                 * @since 2.82
                 * @deprecated since 2.84 Use {@link GioUnix.mount_entries_get_from_file} instead.
                 * @param table_path path to the mounts table file (for example `/proc/self/mountinfo`)
                 * @returns mount   entries, or `NULL` if there was an error loading them, return location for the   modification time of `table_path`
                 */
                mounts_get_from_file(table_path: string): [MountEntry[] | null, number]
            }
        }

        const GioUnix: GioUnix.$Exports
    }

    export default GI.GioUnix
}