
/// <reference path="./GLib-2.0.d.ts" />
/// <reference path="./GObject-2.0.d.ts" />

/**
 * Type Definitions for GJS (https://gjs.guide/), generated by [GirGen](https://github.com/aylur/girgen)
 * If you found a bug, create a bug report on [GirGen's Repository](https://github.com/aylur/girgen/issues/new)
 */
declare module "gi://GModule?version=2.0" {
    import type GLib from "gi://GLib?version=2.0"
    import type GObject from "gi://GObject?version=2.0"

    /**
     * Do **not** import this at runtime.
     * This namespace is only exported for module augmentation.
     */
    export namespace GI {
        

        namespace GModule {
            

            interface ModuleStruct {
                readonly $gtype: GObject.GType<Module>
                [Symbol.hasInstance](instance: unknown): instance is Module
                /**
                 * A portable way to build the filename of a module. The platform-specific
                 * prefix and suffix are added to the filename, if needed, and the result
                 * is added to the directory, using the correct separator character.
                 *
                 * The directory should specify the directory where the module can be found.
                 * It can be %NULL or an empty string to indicate that the module is in a
                 * standard platform-specific directory, though this is not recommended
                 * since the wrong module may be found.
                 *
                 * For example, calling g_module_build_path() on a Linux system with a
                 *  `directory` of `/lib` and a `module_name` of "mylibrary" will return
                 * `/lib/libmylibrary.so`. On a Windows system, using `\Windows` as the
                 * directory it will return `\Windows\mylibrary.dll`.
                 * @deprecated since 2.76 Use g_module_open() instead with `module_name` as the basename of the file_name argument. See %G_MODULE_SUFFIX for why.
                 * @param directory the directory where the module is. This can be     %NULL or the empty string to indicate that the standard platform-specific     directories will be used, though that is not recommended
                 * @param module_name the name of the module
                 * @returns the complete path of the module, including the standard library     prefix and suffix. This should be freed when no longer needed
                 */
                build_path(directory: string | null, module_name: string): string
                /**
                 * Gets a string describing the last module error.
                 * @returns a string describing the last module error
                 */
                error(): string
                
                error_quark(): GLib.Quark
                /**
                 * Checks if modules are supported on the current platform.
                 * @returns %TRUE if modules are supported
                 */
                supported(): boolean
            }

            interface Module {
                /**
                 * Closes a module.
                 * @returns %TRUE on success
                 */
                close(): boolean
                /**
                 * Ensures that a module will never be unloaded.
                 * Any future g_module_close() calls on the module will be ignored.
                 */
                make_resident(): void
                /**
                 * Returns the filename that the module was opened with.
                 *
                 * If `module` refers to the application itself, "main" is returned.
                 * @returns the filename of the module
                 */
                name(): string
                /**
                 * Gets a symbol pointer from a module, such as one exported
                 * by %G_MODULE_EXPORT. Note that a valid symbol can be %NULL.
                 * @param symbol_name the name of the symbol to find
                 * @returns %TRUE on success, returns the pointer to the symbol value
                 */
                symbol(symbol_name: string): [boolean, never | null]
            }

            interface $Exports {
                Module: ModuleStruct
            }
            
            interface ModuleError extends GLib.Error {}

            interface ModuleErrorEnum {
                readonly $gtype: GObject.GType<ModuleError>

                new(props: { message: string, code: number }): ModuleError
                /**
                 * there was an error loading or opening a module file
                 */
                readonly "FAILED": 0
                /**
                 * a module returned an error from its `g_module_check_init()` function
                 */
                readonly "CHECK_FAILED": 1
            }

            interface $Exports {
                /**
                 * Errors returned by g_module_open_full().
                 * @since 2.70
                 */
                ModuleError: ModuleErrorEnum
            }
            
            interface ModuleFlagsBitfield {
                readonly $gtype: GObject.GType<ModuleFlags>
                /**
                 * specifies that symbols are only resolved when
                 *     needed. The default action is to bind all symbols when the module
                 *     is loaded.
                 */
                readonly "LAZY": 1
                /**
                 * specifies that symbols in the module should
                 *     not be added to the global name space. The default action on most
                 *     platforms is to place symbols in the module in the global name space,
                 *     which may cause conflicts with existing symbols.
                 */
                readonly "LOCAL": 2
                /**
                 * mask for all flags.
                 */
                readonly "MASK": 3
            }
            type ModuleFlags = number
            interface $Exports {
                /**
                 * Flags passed to g_module_open().
                 * Note that these flags are not supported on all platforms.
                 */
                ModuleFlags: ModuleFlagsBitfield
            }
            /**
             * Specifies the type of the module initialization function.
             * If a module contains a function named g_module_check_init() it is called
             * automatically when the module is loaded. It is passed the #GModule structure
             * and should return %NULL on success or a string describing the initialization
             * error.
             * @param module the #GModule corresponding to the module which has just been loaded
             * @returns %NULL on success, or a string describing the initialization error
             */
            type ModuleCheckInit = (module: Module) => string
            /**
             * Specifies the type of the module function called when it is unloaded.
             * If a module contains a function named g_module_unload() it is called
             * automatically when the module is unloaded.
             * It is passed the #GModule structure.
             * @param module the #GModule about to be unloaded
             */
            type ModuleUnload = (module: Module) => void

            interface $Exports {
                __name__: "GModule"
                __version__: "2.0"
                MODULE_IMPL_AR: 7
                MODULE_IMPL_DL: 1
                MODULE_IMPL_NONE: 0
                MODULE_IMPL_WIN32: 3
                /**
                 * A portable way to build the filename of a module. The platform-specific
                 * prefix and suffix are added to the filename, if needed, and the result
                 * is added to the directory, using the correct separator character.
                 *
                 * The directory should specify the directory where the module can be found.
                 * It can be %NULL or an empty string to indicate that the module is in a
                 * standard platform-specific directory, though this is not recommended
                 * since the wrong module may be found.
                 *
                 * For example, calling g_module_build_path() on a Linux system with a
                 *  `directory` of `/lib` and a `module_name` of "mylibrary" will return
                 * `/lib/libmylibrary.so`. On a Windows system, using `\Windows` as the
                 * directory it will return `\Windows\mylibrary.dll`.
                 * @deprecated since 2.76 Use g_module_open() instead with `module_name` as the basename of the file_name argument. See %G_MODULE_SUFFIX for why.
                 * @param directory the directory where the module is. This can be     %NULL or the empty string to indicate that the standard platform-specific     directories will be used, though that is not recommended
                 * @param module_name the name of the module
                 * @returns the complete path of the module, including the standard library     prefix and suffix. This should be freed when no longer needed
                 */
                module_build_path(directory: string | null, module_name: string): string
                /**
                 * Gets a string describing the last module error.
                 * @returns a string describing the last module error
                 */
                module_error(): string
                
                module_error_quark(): GLib.Quark
                /**
                 * Checks if modules are supported on the current platform.
                 * @returns %TRUE if modules are supported
                 */
                module_supported(): boolean
            }
        }

        const GModule: GModule.$Exports
    }

    export default GI.GModule
}