
/// <reference path="./GLib-2.0.d.ts" />
/// <reference path="./GModule-2.0.d.ts" />
/// <reference path="./GObject-2.0.d.ts" />
/// <reference path="./Gst-1.0.d.ts" />

/**
 * Type Definitions for GJS (https://gjs.guide/), generated by [GirGen](https://github.com/aylur/girgen)
 * If you found a bug, create a bug report on [GirGen's Repository](https://github.com/aylur/girgen/issues/new)
 */
declare module "gi://GstController?version=1.0" {
    import type GLib from "gi://GLib?version=2.0"
    import type GModule from "gi://GModule?version=2.0"
    import type GObject from "gi://GObject?version=2.0"
    import type Gst from "gi://Gst?version=1.0"

    /**
     * Do **not** import this at runtime.
     * This namespace is only exported for module augmentation.
     */
    export namespace GI {
        

        namespace GstController {
            

            namespace ARGBControlBinding {
                interface SignalSignatures extends Gst.ControlBinding.SignalSignatures {
                }

                interface ReadWriteProperties extends Gst.ControlBinding.ReadWriteProperties {
                    "control-source-a": Gst.ControlSource
                    "control-source-b": Gst.ControlSource
                    "control-source-g": Gst.ControlSource
                    "control-source-r": Gst.ControlSource
                }

                interface ReadableProperties extends ReadWriteProperties, Gst.ControlBinding.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, Gst.ControlBinding.WritableProperties {
                }

                interface ConstructOnlyProperties extends Gst.ControlBinding.ConstructOnlyProperties {
                }
            }

            interface ARGBControlBinding extends Gst.ControlBinding {
                readonly $signals: ARGBControlBinding.SignalSignatures
                readonly $readableProperties: ARGBControlBinding.ReadableProperties
                readonly $writableProperties: ARGBControlBinding.WritableProperties
                readonly $constructOnlyProperties: ARGBControlBinding.ConstructOnlyProperties
                
                get controlSourceA(): Gst.ControlSource
                set controlSourceA(value: Gst.ControlSource)
                
                get controlSourceB(): Gst.ControlSource
                set controlSourceB(value: Gst.ControlSource)
                
                get controlSourceG(): Gst.ControlSource
                set controlSourceG(value: Gst.ControlSource)
                
                get controlSourceR(): Gst.ControlSource
                set controlSourceR(value: Gst.ControlSource)
            }

            interface ARGBControlBindingClass extends Omit<Gst.ControlBindingClass, "new"> {
                readonly $gtype: GObject.GType<ARGBControlBinding>
                readonly prototype: ARGBControlBinding

                new (props?: Partial<GObject.ConstructorProps<ARGBControlBinding>>): ARGBControlBinding
                /**
                 * Create a new control-binding that attaches the given #GstControlSource to the
                 * #GObject property.
                 * @param object the object of the property
                 * @param property_name the property-name to attach the control source
                 * @param cs_a the control source for the alpha channel
                 * @param cs_r the control source for the red channel
                 * @param cs_g the control source for the green channel
                 * @param cs_b the control source for the blue channel
                 * @returns the new #GstARGBControlBinding
                 */
                "new"(object: Gst.Object, property_name: string, cs_a: Gst.ControlSource, cs_r: Gst.ControlSource, cs_g: Gst.ControlSource, cs_b: Gst.ControlSource): ARGBControlBinding
            }

            interface $Exports {
                /**
                 * A value mapping object that attaches multiple control sources to a guint
                 * gobject properties representing a color. A control value of 0.0 will turn the
                 * color component off and a value of 1.0 will be the color level.
                 */
                ARGBControlBinding: ARGBControlBindingClass
            }
            

            namespace DirectControlBinding {
                interface SignalSignatures extends Gst.ControlBinding.SignalSignatures {
                }

                interface ReadWriteProperties extends Gst.ControlBinding.ReadWriteProperties {
                    "control-source": Gst.ControlSource
                }

                interface ReadableProperties extends ReadWriteProperties, Gst.ControlBinding.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, Gst.ControlBinding.WritableProperties {
                }

                interface ConstructOnlyProperties extends Gst.ControlBinding.ConstructOnlyProperties {
                    "absolute": boolean
                }
            }

            interface DirectControlBinding extends Gst.ControlBinding {
                readonly $signals: DirectControlBinding.SignalSignatures
                readonly $readableProperties: DirectControlBinding.ReadableProperties
                readonly $writableProperties: DirectControlBinding.WritableProperties
                readonly $constructOnlyProperties: DirectControlBinding.ConstructOnlyProperties
                /**
                 * @default FALSE
                 */
                get absolute(): boolean
                set absolute(value: boolean)
                
                get controlSource(): Gst.ControlSource
                set controlSource(value: Gst.ControlSource)
            }

            interface DirectControlBindingClass extends Omit<Gst.ControlBindingClass, "new"> {
                readonly $gtype: GObject.GType<DirectControlBinding>
                readonly prototype: DirectControlBinding

                new (props?: Partial<GObject.ConstructorProps<DirectControlBinding>>): DirectControlBinding
                /**
                 * Create a new control-binding that attaches the #GstControlSource to the
                 * #GObject property. It will map the control source range [0.0 ... 1.0] to
                 * the full target property range, and clip all values outside this range.
                 * @param object the object of the property
                 * @param property_name the property-name to attach the control source
                 * @param cs the control source
                 * @returns the new #GstDirectControlBinding
                 */
                "new"(object: Gst.Object, property_name: string, cs: Gst.ControlSource): DirectControlBinding
                /**
                 * Create a new control-binding that attaches the #GstControlSource to the
                 * #GObject property. It will directly map the control source values to the
                 * target property range without any transformations.
                 * @since 1.6
                 * @param object the object of the property
                 * @param property_name the property-name to attach the control source
                 * @param cs the control source
                 * @returns the new #GstDirectControlBinding
                 */
                new_absolute(object: Gst.Object, property_name: string, cs: Gst.ControlSource): DirectControlBinding
            }

            interface $Exports {
                /**
                 * A value mapping object that attaches control sources to gobject properties. It
                 * will map the control values directly to the target property range. If a
                 * non-absolute direct control binding is used, the value range [0.0 ... 1.0]
                 * is mapped to full target property range, and all values outside the range
                 * will be clipped. An absolute control binding will not do any value
                 * transformations.
                 */
                DirectControlBinding: DirectControlBindingClass
            }
            

            namespace InterpolationControlSource {
                interface SignalSignatures extends TimedValueControlSource.SignalSignatures {
                }

                interface ReadWriteProperties extends TimedValueControlSource.ReadWriteProperties {
                    "mode": InterpolationMode
                }

                interface ReadableProperties extends ReadWriteProperties, TimedValueControlSource.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, TimedValueControlSource.WritableProperties {
                }

                interface ConstructOnlyProperties extends TimedValueControlSource.ConstructOnlyProperties {
                }
            }

            interface InterpolationControlSource extends TimedValueControlSource {
                readonly $signals: InterpolationControlSource.SignalSignatures
                readonly $readableProperties: InterpolationControlSource.ReadableProperties
                readonly $writableProperties: InterpolationControlSource.WritableProperties
                readonly $constructOnlyProperties: InterpolationControlSource.ConstructOnlyProperties
                /**
                 * @default GST_INTERPOLATION_MODE_NONE
                 */
                get mode(): InterpolationMode
                set mode(value: InterpolationMode)
            }

            interface InterpolationControlSourceClass extends Omit<TimedValueControlSourceClass, "new"> {
                readonly $gtype: GObject.GType<InterpolationControlSource>
                readonly prototype: InterpolationControlSource

                new (props?: Partial<GObject.ConstructorProps<InterpolationControlSource>>): InterpolationControlSource
                /**
                 * This returns a new, unbound #GstInterpolationControlSource.
                 * @returns a new, unbound #GstInterpolationControlSource.
                 */
                "new"(): InterpolationControlSource
            }

            interface $Exports {
                /**
                 * #GstInterpolationControlSource is a #GstControlSource, that interpolates values between user-given
                 * control points. It supports several interpolation modes and property types.
                 *
                 * To use #GstInterpolationControlSource get a new instance by calling
                 * gst_interpolation_control_source_new(), bind it to a #GParamSpec and set some
                 * control points by calling gst_timed_value_control_source_set().
                 *
                 * All functions are MT-safe.
                 */
                InterpolationControlSource: InterpolationControlSourceClass
            }
            

            namespace LFOControlSource {
                interface SignalSignatures extends Gst.ControlSource.SignalSignatures {
                }

                interface ReadWriteProperties extends Gst.ControlSource.ReadWriteProperties {
                    "amplitude": number
                    "frequency": number
                    "offset": number
                    "timeshift": number
                    "waveform": LFOWaveform
                }

                interface ReadableProperties extends ReadWriteProperties, Gst.ControlSource.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, Gst.ControlSource.WritableProperties {
                }

                interface ConstructOnlyProperties extends Gst.ControlSource.ConstructOnlyProperties {
                }
            }

            interface LFOControlSource extends Gst.ControlSource {
                readonly $signals: LFOControlSource.SignalSignatures
                readonly $readableProperties: LFOControlSource.ReadableProperties
                readonly $writableProperties: LFOControlSource.WritableProperties
                readonly $constructOnlyProperties: LFOControlSource.ConstructOnlyProperties
                /**
                 * Specifies the amplitude for the waveform of this #GstLFOControlSource.
                 * @default 1.000000
                 */
                get amplitude(): number
                set amplitude(value: number)
                /**
                 * Specifies the frequency that should be used for the waveform
                 * of this #GstLFOControlSource. It should be large enough
                 * so that the period is longer than one nanosecond.
                 * @default 1.000000
                 */
                get frequency(): number
                set frequency(value: number)
                /**
                 * Specifies the value offset for the waveform of this #GstLFOControlSource.
                 * @default 1.000000
                 */
                get offset(): number
                set offset(value: number)
                /**
                 * Specifies the timeshift to the right that should be used for the waveform
                 * of this #GstLFOControlSource in nanoseconds.
                 *
                 * To get a n nanosecond shift to the left use
                 * "(GST_SECOND / frequency) - n".
                 * @default 0
                 */
                get timeshift(): number
                set timeshift(value: number)
                /**
                 * Specifies the waveform that should be used for this #GstLFOControlSource.
                 * @default GST_LFO_WAVEFORM_SINE
                 */
                get waveform(): LFOWaveform
                set waveform(value: LFOWaveform)
            }

            interface LFOControlSourceClass extends Omit<Gst.ControlSourceClass, "new"> {
                readonly $gtype: GObject.GType<LFOControlSource>
                readonly prototype: LFOControlSource

                new (props?: Partial<GObject.ConstructorProps<LFOControlSource>>): LFOControlSource
                /**
                 * This returns a new, unbound #GstLFOControlSource.
                 * @returns a new, unbound #GstLFOControlSource.
                 */
                "new"(): LFOControlSource
            }

            interface $Exports {
                /**
                 * #GstLFOControlSource is a #GstControlSource, that provides several periodic
                 * waveforms as control values.
                 *
                 * To use #GstLFOControlSource get a new instance by calling
                 * gst_lfo_control_source_new(), bind it to a #GParamSpec and set the relevant
                 * properties.
                 *
                 * All functions are MT-safe.
                 */
                LFOControlSource: LFOControlSourceClass
            }
            

            namespace ProxyControlBinding {
                interface SignalSignatures extends Gst.ControlBinding.SignalSignatures {
                }

                interface ReadWriteProperties extends Gst.ControlBinding.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, Gst.ControlBinding.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, Gst.ControlBinding.WritableProperties {
                }

                interface ConstructOnlyProperties extends Gst.ControlBinding.ConstructOnlyProperties {
                }
            }

            interface ProxyControlBinding extends Gst.ControlBinding {
                readonly $signals: ProxyControlBinding.SignalSignatures
                readonly $readableProperties: ProxyControlBinding.ReadableProperties
                readonly $writableProperties: ProxyControlBinding.WritableProperties
                readonly $constructOnlyProperties: ProxyControlBinding.ConstructOnlyProperties
            }

            interface ProxyControlBindingClass extends Omit<Gst.ControlBindingClass, "new"> {
                readonly $gtype: GObject.GType<ProxyControlBinding>
                readonly prototype: ProxyControlBinding

                new (props?: Partial<GObject.ConstructorProps<ProxyControlBinding>>): ProxyControlBinding
                /**
                 * #GstProxyControlBinding forwards all access to data or `sync_values()`
                 * requests from `property_name` on `object` to the control binding at
                 *  `ref_property_name` on `ref_object`.
                 * @since 1.12
                 * @param object a #GstObject
                 * @param property_name the property name in `object` to control
                 * @param ref_object a #GstObject to forward all              #GstControlBinding requests to
                 * @param ref_property_name the property_name in `ref_object` to control
                 * @returns a new #GstControlBinding that proxies the control interface between properties on different #GstObject's
                 */
                "new"(object: Gst.Object, property_name: string, ref_object: Gst.Object, ref_property_name: string): ProxyControlBinding
            }

            interface $Exports {
                /**
                 * A #GstControlBinding that forwards requests to another #GstControlBinding
                 */
                ProxyControlBinding: ProxyControlBindingClass
            }
            

            namespace TimedValueControlSource {
                interface SignalSignatures extends Gst.ControlSource.SignalSignatures {
                    /**
                     * Emitted right after the new value has been added to `self`
                     * @since 1.6
                     * @param timed_value The newly added #GstTimedValue
                     */
                    "value-added"(timed_value: ControlPoint): void
                    /**
                     * Emitted right after the new value has been set on `timed_signals`
                     * @since 1.6
                     * @param timed_value The #GstTimedValue where the value changed
                     */
                    "value-changed"(timed_value: ControlPoint): void
                    /**
                     * Emitted when `timed_value` is removed from `self`
                     * @since 1.6
                     * @param timed_value The removed #GstTimedValue
                     */
                    "value-removed"(timed_value: ControlPoint): void
                }

                interface ReadWriteProperties extends Gst.ControlSource.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, Gst.ControlSource.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, Gst.ControlSource.WritableProperties {
                }

                interface ConstructOnlyProperties extends Gst.ControlSource.ConstructOnlyProperties {
                }
            }

            interface TimedValueControlSource extends Gst.ControlSource {
                readonly $signals: TimedValueControlSource.SignalSignatures
                readonly $readableProperties: TimedValueControlSource.ReadableProperties
                readonly $writableProperties: TimedValueControlSource.WritableProperties
                readonly $constructOnlyProperties: TimedValueControlSource.ConstructOnlyProperties
                /**
                 * Find last value before given timestamp in control point list.
                 * If all values in the control point list come after the given
                 * timestamp or no values exist, %NULL is returned.
                 *
                 * For use in control source implementations.
                 * @param timestamp the search key
                 * @returns the found #GSequenceIter or %NULL
                 */
                find_control_point_iter(timestamp: Gst.ClockTime): GLib.SequenceIter | null
                /**
                 * Returns a read-only copy of the list of #GstControlPoint for the given property.
                 * Free the list after done with it.
                 * @deprecated since 1.28 Use gst_timed_value_control_source_list_control_points() instead.
                 * @returns a copy of the list, or %NULL if the property isn't handled by the controller
                 */
                get_all(): ControlPoint[]
                /**
                 * Get the number of control points that are set.
                 * @returns the number of control points that are set.
                 */
                get_count(): number
                /**
                 * Returns an array of #GstTimedValue representing the control points
                 * that have been set on this control source. To modify the value of a
                 * control point, use #gst_timed_value_control_source_set.
                 * @since 1.28
                 * @returns an array of control points, or %NULL if no control points are set.
                 */
                list_control_points(): Gst.TimedValue[] | null
                /**
                 * Set the value of given controller-handled property at a certain time.
                 * @param timestamp the time the control-change is scheduled for
                 * @param value the control-value
                 * @returns FALSE if the values couldn't be set, TRUE otherwise.
                 */
                set(timestamp: Gst.ClockTime, value: number): boolean
                /**
                 * Sets multiple timed values at once.
                 * @param timedvalues a list with #GstTimedValue items
                 * @returns FALSE if the values couldn't be set, TRUE otherwise.
                 */
                set_from_list(timedvalues: Gst.TimedValue[]): boolean
                /**
                 * Used to remove the value of given controller-handled property at a certain
                 * time.
                 * @param timestamp the time the control-change should be removed from
                 * @returns FALSE if the value couldn't be unset (i.e. not found, TRUE otherwise.
                 */
                unset(timestamp: Gst.ClockTime): boolean
                /**
                 * Used to remove all time-stamped values of given controller-handled property
                 */
                unset_all(): void
            }

            interface TimedValueControlSourceClass extends Omit<Gst.ControlSourceClass, "new"> {
                readonly $gtype: GObject.GType<TimedValueControlSource>
                readonly prototype: TimedValueControlSource

                new (props?: Partial<GObject.ConstructorProps<TimedValueControlSource>>): TimedValueControlSource
            }

            interface $Exports {
                /**
                 * Base class for #GstControlSource that use time-stamped values.
                 *
                 * When overriding bind, chain up first to give this bind implementation a
                 * chance to setup things.
                 *
                 * All functions are MT-safe.
                 */
                TimedValueControlSource: TimedValueControlSourceClass
            }
            

            namespace TriggerControlSource {
                interface SignalSignatures extends TimedValueControlSource.SignalSignatures {
                }

                interface ReadWriteProperties extends TimedValueControlSource.ReadWriteProperties {
                    "tolerance": number
                }

                interface ReadableProperties extends ReadWriteProperties, TimedValueControlSource.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, TimedValueControlSource.WritableProperties {
                }

                interface ConstructOnlyProperties extends TimedValueControlSource.ConstructOnlyProperties {
                }
            }

            interface TriggerControlSource extends TimedValueControlSource {
                readonly $signals: TriggerControlSource.SignalSignatures
                readonly $readableProperties: TriggerControlSource.ReadableProperties
                readonly $writableProperties: TriggerControlSource.WritableProperties
                readonly $constructOnlyProperties: TriggerControlSource.ConstructOnlyProperties
                /**
                 * @default 0
                 */
                get tolerance(): number
                set tolerance(value: number)
            }

            interface TriggerControlSourceClass extends Omit<TimedValueControlSourceClass, "new"> {
                readonly $gtype: GObject.GType<TriggerControlSource>
                readonly prototype: TriggerControlSource

                new (props?: Partial<GObject.ConstructorProps<TriggerControlSource>>): TriggerControlSource
                /**
                 * This returns a new, unbound #GstTriggerControlSource.
                 * @returns a new, unbound #GstTriggerControlSource.
                 */
                "new"(): TriggerControlSource
            }

            interface $Exports {
                /**
                 * #GstTriggerControlSource is a #GstControlSource, that returns values from user-given
                 * control points. It allows for a tolerance on the time-stamps.
                 *
                 * To use #GstTriggerControlSource get a new instance by calling
                 * gst_trigger_control_source_new(), bind it to a #GParamSpec and set some
                 * control points by calling gst_timed_value_control_source_set().
                 *
                 * All functions are MT-safe.
                 */
                TriggerControlSource: TriggerControlSourceClass
            }
            

            interface ControlPointStruct {
                readonly $gtype: GObject.GType<ControlPoint>
                new (fields?: {
                    timestamp?: Gst.ClockTime
                    value?: number
                }): ControlPoint
            }

            interface ControlPoint {
                /**
                 * timestamp of the value change
                 */
                timestamp: Gst.ClockTime
                /**
                 * the new value
                 */
                value: number
                /**
                 * Copies a #GstControlPoint
                 * @returns A copy of `cp`
                 */
                copy(): ControlPoint
                /**
                 * Frees all data allocated by a #GstControlPoint instance.
                 */
                free(): void
            }

            interface $Exports {
                ControlPoint: ControlPointStruct
            }
            

            interface InterpolationControlSourcePrivateStruct {
                readonly $gtype: GObject.GType<InterpolationControlSourcePrivate>
                [Symbol.hasInstance](instance: unknown): instance is InterpolationControlSourcePrivate
            }

            interface InterpolationControlSourcePrivate {
            }

            interface $Exports {
                InterpolationControlSourcePrivate: InterpolationControlSourcePrivateStruct
            }
            

            interface LFOControlSourcePrivateStruct {
                readonly $gtype: GObject.GType<LFOControlSourcePrivate>
                [Symbol.hasInstance](instance: unknown): instance is LFOControlSourcePrivate
            }

            interface LFOControlSourcePrivate {
            }

            interface $Exports {
                LFOControlSourcePrivate: LFOControlSourcePrivateStruct
            }
            

            interface TimedValueControlSourcePrivateStruct {
                readonly $gtype: GObject.GType<TimedValueControlSourcePrivate>
                [Symbol.hasInstance](instance: unknown): instance is TimedValueControlSourcePrivate
            }

            interface TimedValueControlSourcePrivate {
            }

            interface $Exports {
                TimedValueControlSourcePrivate: TimedValueControlSourcePrivateStruct
            }
            

            interface TriggerControlSourcePrivateStruct {
                readonly $gtype: GObject.GType<TriggerControlSourcePrivate>
                [Symbol.hasInstance](instance: unknown): instance is TriggerControlSourcePrivate
            }

            interface TriggerControlSourcePrivate {
            }

            interface $Exports {
                TriggerControlSourcePrivate: TriggerControlSourcePrivateStruct
            }
            
            interface InterpolationModeEnum {
                readonly $gtype: GObject.GType<InterpolationMode>
                /**
                 * steps-like interpolation, default
                 */
                readonly "NONE": 0
                /**
                 * linear interpolation
                 */
                readonly "LINEAR": 1
                /**
                 * cubic interpolation (natural), may overshoot
                 *   the min or max values set by the control point, but is more 'curvy'
                 */
                readonly "CUBIC": 2
                /**
                 * monotonic cubic interpolation, will not
                 *   produce any values outside of the min-max range set by the control points
                 *   (Since: 1.8)
                 */
                readonly "CUBIC_MONOTONIC": 3
            }
            type InterpolationMode = InterpolationModeEnum[Exclude<keyof InterpolationModeEnum, "$gtype">]
            interface $Exports {
                /**
                 * The various interpolation modes available.
                 */
                InterpolationMode: InterpolationModeEnum
            }
            
            interface LFOWaveformEnum {
                readonly $gtype: GObject.GType<LFOWaveform>
                /**
                 * sine waveform
                 */
                readonly "SINE": 0
                /**
                 * square waveform
                 */
                readonly "SQUARE": 1
                /**
                 * saw waveform
                 */
                readonly "SAW": 2
                /**
                 * reverse saw waveform
                 */
                readonly "REVERSE_SAW": 3
                /**
                 * triangle waveform
                 */
                readonly "TRIANGLE": 4
            }
            type LFOWaveform = LFOWaveformEnum[Exclude<keyof LFOWaveformEnum, "$gtype">]
            interface $Exports {
                /**
                 * The various waveform modes available.
                 */
                LFOWaveform: LFOWaveformEnum
            }
            /**
             * Function to map a control-value to the target GValue.
             * @param self the #GstDirectControlBinding instance
             * @param src_value the value returned by the cotnrol source
             * @param dest_value the target GValue
             */
            type DirectControlBindingConvertGValue = (self: DirectControlBinding, src_value: number, dest_value: (GObject.Value | unknown)) => void
            /**
             * Function to map a control-value to the target plain data type.
             * @param self the #GstDirectControlBinding instance
             * @param src_value the value returned by the cotnrol source
             * @param dest_value the target location
             */
            type DirectControlBindingConvertValue = (self: DirectControlBinding, src_value: number, dest_value: never | null) => void

            interface $Exports {
                __name__: "GstController"
                __version__: "1.0"
                /**
                 * Reset the controlled value cache.
                 * @param self the #GstTimedValueControlSource
                 */
                timed_value_control_invalidate_cache(self: TimedValueControlSource): void
            }
        }

        const GstController: GstController.$Exports
    }

    export default GI.GstController
}