
/// <reference path="./GLib-2.0.d.ts" />
/// <reference path="./GModule-2.0.d.ts" />
/// <reference path="./GObject-2.0.d.ts" />
/// <reference path="./Gst-1.0.d.ts" />
/// <reference path="./GstBase-1.0.d.ts" />
/// <reference path="./GstVideo-1.0.d.ts" />
/// <reference path="./GstGL-1.0.d.ts" />

/**
 * Type Definitions for GJS (https://gjs.guide/), generated by [GirGen](https://github.com/aylur/girgen)
 * If you found a bug, create a bug report on [GirGen's Repository](https://github.com/aylur/girgen/issues/new)
 */
declare module "gi://GstGLX11?version=1.0" {
    import type GLib from "gi://GLib?version=2.0"
    import type GModule from "gi://GModule?version=2.0"
    import type GObject from "gi://GObject?version=2.0"
    import type Gst from "gi://Gst?version=1.0"
    import type GstBase from "gi://GstBase?version=1.0"
    import type GstVideo from "gi://GstVideo?version=1.0"
    import type GstGL from "gi://GstGL?version=1.0"

    /**
     * Do **not** import this at runtime.
     * This namespace is only exported for module augmentation.
     */
    export namespace GI {
        

        namespace GstGLX11 {
            

            namespace GLDisplayX11 {
                interface SignalSignatures extends GstGL.GLDisplay.SignalSignatures {
                }

                interface ReadWriteProperties extends GstGL.GLDisplay.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, GstGL.GLDisplay.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, GstGL.GLDisplay.WritableProperties {
                }

                interface ConstructOnlyProperties extends GstGL.GLDisplay.ConstructOnlyProperties {
                }
            }

            interface GLDisplayX11 extends GstGL.GLDisplay {
                readonly $signals: GLDisplayX11.SignalSignatures
                readonly $readableProperties: GLDisplayX11.ReadableProperties
                readonly $writableProperties: GLDisplayX11.WritableProperties
                readonly $constructOnlyProperties: GLDisplayX11.ConstructOnlyProperties
            }

            interface GLDisplayX11Class extends Omit<GstGL.GLDisplayClass, "new"> {
                readonly $gtype: GObject.GType<GLDisplayX11>
                readonly prototype: GLDisplayX11

                new (props?: Partial<GObject.ConstructorProps<GLDisplayX11>>): GLDisplayX11
                /**
                 * Create a new #GstGLDisplayX11 from the x11 display name.  See `XOpenDisplay`()
                 * for details on what is a valid name.
                 * @param name a display name
                 * @returns a new #GstGLDisplayX11 or %NULL
                 */
                "new"(name: string | null): GLDisplayX11 | null
            }

            interface $Exports {
                /**
                 * the contents of a #GstGLDisplayX11 are private and should only be accessed
                 * through the provided API
                 */
                GLDisplayX11: GLDisplayX11Class
            }

            interface $Exports {
                __name__: "GstGLX11"
                __version__: "1.0"
            }
        }

        const GstGLX11: GstGLX11.$Exports
    }

    export default GI.GstGLX11
}