
/// <reference path="./GLib-2.0.d.ts" />
/// <reference path="./GModule-2.0.d.ts" />
/// <reference path="./GObject-2.0.d.ts" />
/// <reference path="./Gst-1.0.d.ts" />
/// <reference path="./GstBase-1.0.d.ts" />
/// <reference path="./GstVideo-1.0.d.ts" />
/// <reference path="./GstGL-1.0.d.ts" />

/**
 * Type Definitions for GJS (https://gjs.guide/), generated by [GirGen](https://github.com/aylur/girgen)
 * If you found a bug, create a bug report on [GirGen's Repository](https://github.com/aylur/girgen/issues/new)
 */
declare module "gi://GstGLWayland?version=1.0" {
    import type GLib from "gi://GLib?version=2.0"
    import type GModule from "gi://GModule?version=2.0"
    import type GObject from "gi://GObject?version=2.0"
    import type Gst from "gi://Gst?version=1.0"
    import type GstBase from "gi://GstBase?version=1.0"
    import type GstVideo from "gi://GstVideo?version=1.0"
    import type GstGL from "gi://GstGL?version=1.0"

    /**
     * Do **not** import this at runtime.
     * This namespace is only exported for module augmentation.
     */
    export namespace GI {
        

        namespace GstGLWayland {
            

            namespace GLDisplayWayland {
                interface SignalSignatures extends GstGL.GLDisplay.SignalSignatures {
                }

                interface ReadWriteProperties extends GstGL.GLDisplay.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, GstGL.GLDisplay.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, GstGL.GLDisplay.WritableProperties {
                }

                interface ConstructOnlyProperties extends GstGL.GLDisplay.ConstructOnlyProperties {
                }
            }

            interface GLDisplayWayland extends GstGL.GLDisplay {
                readonly $signals: GLDisplayWayland.SignalSignatures
                readonly $readableProperties: GLDisplayWayland.ReadableProperties
                readonly $writableProperties: GLDisplayWayland.WritableProperties
                readonly $constructOnlyProperties: GLDisplayWayland.ConstructOnlyProperties
            }

            interface GLDisplayWaylandClass extends Omit<GstGL.GLDisplayClass, "new"> {
                readonly $gtype: GObject.GType<GLDisplayWayland>
                readonly prototype: GLDisplayWayland

                new (props?: Partial<GObject.ConstructorProps<GLDisplayWayland>>): GLDisplayWayland
                /**
                 * Create a new #GstGLDisplayWayland from the wayland display name.  See `wl_display_connect`()
                 * for details on what is a valid name.
                 * @param name a display name
                 * @returns a new #GstGLDisplayWayland or %NULL
                 */
                "new"(name: string | null): GLDisplayWayland | null
                /**
                 * Creates a new display connection from a wl_display Display.
                 * @param display an existing, wayland display
                 * @returns a new #GstGLDisplayWayland
                 */
                new_with_display(display: never | null): GLDisplayWayland
            }

            interface $Exports {
                /**
                 * the contents of a #GstGLDisplayWayland are private and should only be accessed
                 * through the provided API
                 */
                GLDisplayWayland: GLDisplayWaylandClass
            }

            interface $Exports {
                __name__: "GstGLWayland"
                __version__: "1.0"
            }
        }

        const GstGLWayland: GstGLWayland.$Exports
    }

    export default GI.GstGLWayland
}