
/// <reference path="./GLib-2.0.d.ts" />
/// <reference path="./GModule-2.0.d.ts" />
/// <reference path="./GObject-2.0.d.ts" />
/// <reference path="./Gst-1.0.d.ts" />
/// <reference path="./GstBase-1.0.d.ts" />
/// <reference path="./GstVideo-1.0.d.ts" />

/**
 * Type Definitions for GJS (https://gjs.guide/), generated by [GirGen](https://github.com/aylur/girgen)
 * If you found a bug, create a bug report on [GirGen's Repository](https://github.com/aylur/girgen/issues/new)
 */
declare module "gi://GstHip?version=1.0" {
    import type GLib from "gi://GLib?version=2.0"
    import type GModule from "gi://GModule?version=2.0"
    import type GObject from "gi://GObject?version=2.0"
    import type Gst from "gi://Gst?version=1.0"
    import type GstBase from "gi://GstBase?version=1.0"
    import type GstVideo from "gi://GstVideo?version=1.0"

    /**
     * Do **not** import this at runtime.
     * This namespace is only exported for module augmentation.
     */
    export namespace GI {
        

        namespace GstHip {
            

            namespace HipAllocator {
                interface SignalSignatures extends Gst.Allocator.SignalSignatures {
                }

                interface ReadWriteProperties extends Gst.Allocator.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, Gst.Allocator.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, Gst.Allocator.WritableProperties {
                }

                interface ConstructOnlyProperties extends Gst.Allocator.ConstructOnlyProperties {
                }
            }

            interface HipAllocator extends Gst.Allocator {
                readonly $signals: HipAllocator.SignalSignatures
                readonly $readableProperties: HipAllocator.ReadableProperties
                readonly $writableProperties: HipAllocator.WritableProperties
                readonly $constructOnlyProperties: HipAllocator.ConstructOnlyProperties
                /**
                 * Allocates a new GstHipMemory
                 * @since 1.28
                 * @param device a #GstHipDevice
                 * @param info a #GstVideoInfo
                 * @returns a newly allocated #GstHipMemory or %NULL if allocation failed
                 */
                alloc(device: HipDevice, info: GstVideo.VideoInfo): Gst.Memory | null
                /**
                 * Controls the active state of `allocator`.
                 * @since 1.28
                 * @param active the new active state
                 * @returns %TRUE if active state of `allocator` was successfully updated.
                 */
                set_active(active: boolean): boolean
                /**
                 * Controls the active state of `allocator`.
                 * @since 1.28
                 * @param active the new active state
                 * @returns %TRUE if active state of `allocator` was successfully updated.
                 */
                vfunc_set_active(active: boolean): boolean
            }

            interface HipAllocatorClass extends Omit<Gst.AllocatorClass, "new"> {
                readonly $gtype: GObject.GType<HipAllocator>
                readonly prototype: HipAllocator

                new (props?: Partial<GObject.ConstructorProps<HipAllocator>>): HipAllocator
            }

            interface $Exports {
                /**
                 * Opaque GstHipAllocator struct
                 * @since 1.28
                 */
                HipAllocator: HipAllocatorClass
            }
            

            namespace HipBufferPool {
                interface SignalSignatures extends Gst.BufferPool.SignalSignatures {
                }

                interface ReadWriteProperties extends Gst.BufferPool.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, Gst.BufferPool.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, Gst.BufferPool.WritableProperties {
                }

                interface ConstructOnlyProperties extends Gst.BufferPool.ConstructOnlyProperties {
                }
            }

            interface HipBufferPool extends Gst.BufferPool {
                readonly $signals: HipBufferPool.SignalSignatures
                readonly $readableProperties: HipBufferPool.ReadableProperties
                readonly $writableProperties: HipBufferPool.WritableProperties
                readonly $constructOnlyProperties: HipBufferPool.ConstructOnlyProperties
            }

            interface HipBufferPoolClass extends Omit<Gst.BufferPoolClass, "new"> {
                readonly $gtype: GObject.GType<HipBufferPool>
                readonly prototype: HipBufferPool

                new (props?: Partial<GObject.ConstructorProps<HipBufferPool>>): HipBufferPool
                /**
                 * Creates new #GstHipBufferPool instance
                 * @since 1.28
                 * @param device a #GstHipDevice
                 * @returns a #GstBufferPool that allocates buffers with #GstHipMemory
                 */
                "new"(device: HipDevice): HipBufferPool
            }

            interface $Exports {
                /**
                 * Opaque GstHipBufferPool struct
                 * @since 1.28
                 */
                HipBufferPool: HipBufferPoolClass
            }
            

            namespace HipDevice {
                interface SignalSignatures extends Gst.Object.SignalSignatures {
                }

                interface ReadWriteProperties extends Gst.Object.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, Gst.Object.ReadableProperties {
                    "device-id": number
                    "texture2d-support": boolean
                    "vendor": HipVendor
                }

                interface WritableProperties extends ReadWriteProperties, Gst.Object.WritableProperties {
                }

                interface ConstructOnlyProperties extends Gst.Object.ConstructOnlyProperties {
                }
            }

            interface HipDevice extends Gst.Object {
                readonly $signals: HipDevice.SignalSignatures
                readonly $readableProperties: HipDevice.ReadableProperties
                readonly $writableProperties: HipDevice.WritableProperties
                readonly $constructOnlyProperties: HipDevice.ConstructOnlyProperties
                /**
                 * @default 0
                 */
                get deviceId(): number
                /**
                 * @default FALSE
                 */
                get texture2DSupport(): boolean
                /**
                 * @default Unknown
                 */
                get vendor(): HipVendor
                /**
                 * Gets numeric device identifier of `device`
                 * @since 1.28
                 * @returns the device identifier
                 */
                get_device_id(): number
                /**
                 * Gets per #GstHipDevice default #GstHipStream owned by `device`
                 * @since 1.28
                 * @returns a #GstHipStream
                 */
                get_stream(): HipStream
                /**
                 * Gets vendor of `device`
                 * @since 1.28
                 * @returns #GstHipVendor
                 */
                get_vendor(): HipVendor
                /**
                 * Checks equality of `device1` and `device2`
                 * @since 1.28
                 * @param device2 a #GstHipDevice
                 * @returns %TRUE if both devices are associated with the same hardware device
                 */
                is_equal(device2: HipDevice): boolean
                /**
                 * Sets `device` to current stack via hipSetDevice
                 * @since 1.28
                 * @returns %TRUE if hipSetDevice call succeeded
                 */
                set_current(): boolean
            }

            interface HipDeviceClass extends Omit<Gst.ObjectClass, "new"> {
                readonly $gtype: GObject.GType<HipDevice>
                readonly prototype: HipDevice

                new (props?: Partial<GObject.ConstructorProps<HipDevice>>): HipDevice
                /**
                 * Creates a new device instance with `vendor` and `device_id`.
                 * @since 1.28
                 * @param vendor a #GstHipVendor
                 * @param device_id device identifier
                 * @returns a #GstHipDevice if succeeded, otherwise %NULL
                 */
                "new"(vendor: HipVendor, device_id: number): HipDevice | null
            }

            interface $Exports {
                /**
                 * Opaque GstHipDevice struct
                 * @since 1.28
                 */
                HipDevice: HipDeviceClass
            }
            

            namespace HipEventPool {
                interface SignalSignatures extends Gst.Object.SignalSignatures {
                }

                interface ReadWriteProperties extends Gst.Object.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, Gst.Object.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, Gst.Object.WritableProperties {
                }

                interface ConstructOnlyProperties extends Gst.Object.ConstructOnlyProperties {
                }
            }

            interface HipEventPool extends Gst.Object {
                readonly $signals: HipEventPool.SignalSignatures
                readonly $readableProperties: HipEventPool.ReadableProperties
                readonly $writableProperties: HipEventPool.WritableProperties
                readonly $constructOnlyProperties: HipEventPool.ConstructOnlyProperties
                /**
                 * Acquires #GstHipEvent from `pool`
                 * @since 1.28
                 * @returns %TRUE if succeeded, a location to store #GstHipEvent
                 */
                acquire(): [boolean, HipEvent | null]
            }

            interface HipEventPoolClass extends Omit<Gst.ObjectClass, "new"> {
                readonly $gtype: GObject.GType<HipEventPool>
                readonly prototype: HipEventPool

                new (props?: Partial<GObject.ConstructorProps<HipEventPool>>): HipEventPool
                /**
                 * Creates a new event pool instance with `vendor` and `device_id`.
                 * @since 1.28
                 * @param vendor a #GstHipVendor
                 * @param device_id device identifier
                 * @returns a #GstHipEventPool if succeeded, otherwise %NULL
                 */
                "new"(vendor: HipVendor, device_id: number): HipEventPool | null
            }

            interface $Exports {
                /**
                 * Opaque GstHipEventPool struct
                 * @since 1.28
                 */
                HipEventPool: HipEventPoolClass
            }
            

            namespace HipPoolAllocator {
                interface SignalSignatures extends HipAllocator.SignalSignatures {
                }

                interface ReadWriteProperties extends HipAllocator.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, HipAllocator.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, HipAllocator.WritableProperties {
                }

                interface ConstructOnlyProperties extends HipAllocator.ConstructOnlyProperties {
                }
            }

            interface HipPoolAllocator extends HipAllocator {
                readonly $signals: HipPoolAllocator.SignalSignatures
                readonly $readableProperties: HipPoolAllocator.ReadableProperties
                readonly $writableProperties: HipPoolAllocator.WritableProperties
                readonly $constructOnlyProperties: HipPoolAllocator.ConstructOnlyProperties
                /**
                 * Acquires a #GstMemory from `allocator`. `memory` should point to a memory
                 * location that can hold a pointer to the new #GstMemory.
                 * @since 1.28
                 * @returns a #GstFlowReturn such as %GST_FLOW_FLUSHING when the allocator is inactive., a #GstMemory
                 */
                acquire_memory(): [Gst.FlowReturn, Gst.Memory | null]
            }

            interface HipPoolAllocatorClass extends Omit<HipAllocatorClass, "new"> {
                readonly $gtype: GObject.GType<HipPoolAllocator>
                readonly prototype: HipPoolAllocator

                new (props?: Partial<GObject.ConstructorProps<HipPoolAllocator>>): HipPoolAllocator
                /**
                 * Creates a new #GstHipPoolAllocator instance
                 * @since 1.28
                 * @param device a #GstHipDevice
                 * @param info a #GstVideoInfo
                 * @returns a #GstHipPoolAllocator
                 */
                "new"(device: HipDevice, info: GstVideo.VideoInfo): HipPoolAllocator
            }

            interface $Exports {
                /**
                 * Opaque GstHipPoolAllocator struct
                 * @since 1.28
                 */
                HipPoolAllocator: HipPoolAllocatorClass
            }
            

            interface HipAllocatorPrivateStruct {
                readonly $gtype: GObject.GType<HipAllocatorPrivate>
                [Symbol.hasInstance](instance: unknown): instance is HipAllocatorPrivate
            }

            interface HipAllocatorPrivate {
            }

            interface $Exports {
                HipAllocatorPrivate: HipAllocatorPrivateStruct
            }
            

            interface HipBufferPoolPrivateStruct {
                readonly $gtype: GObject.GType<HipBufferPoolPrivate>
                [Symbol.hasInstance](instance: unknown): instance is HipBufferPoolPrivate
            }

            interface HipBufferPoolPrivate {
            }

            interface $Exports {
                HipBufferPoolPrivate: HipBufferPoolPrivateStruct
            }
            

            interface HipDevicePrivateStruct {
                readonly $gtype: GObject.GType<HipDevicePrivate>
                [Symbol.hasInstance](instance: unknown): instance is HipDevicePrivate
            }

            interface HipDevicePrivate {
            }

            interface $Exports {
                HipDevicePrivate: HipDevicePrivateStruct
            }
            

            interface HipEventStruct {
                readonly $gtype: GObject.GType<HipEvent>
                [Symbol.hasInstance](instance: unknown): instance is HipEvent
            }

            interface HipEvent {
                /**
                 * Gets numeric device identifier of `event` object
                 * @since 1.28
                 * @returns device identifier
                 */
                get_device_id(): number
                /**
                 * Gets device vendor of `event` object
                 * @since 1.28
                 * @returns #GstHipVendor
                 */
                get_vendor(): HipVendor
                /**
                 * Increments the reference count on `event`
                 * @since 1.28
                 * @returns a pointer to `event`
                 */
                ref(): HipEvent
                /**
                 * Decrements the reference count on `event`
                 * @since 1.28
                 */
                unref(): void
            }

            interface $Exports {
                HipEvent: HipEventStruct
            }
            

            interface HipEventPoolPrivateStruct {
                readonly $gtype: GObject.GType<HipEventPoolPrivate>
                [Symbol.hasInstance](instance: unknown): instance is HipEventPoolPrivate
            }

            interface HipEventPoolPrivate {
            }

            interface $Exports {
                HipEventPoolPrivate: HipEventPoolPrivateStruct
            }
            

            interface HipGraphicsResourceStruct {
                readonly $gtype: GObject.GType<HipGraphicsResource>
                [Symbol.hasInstance](instance: unknown): instance is HipGraphicsResource
            }

            interface HipGraphicsResource {
                /**
                 * Increments the reference count on `resource`
                 * @since 1.28
                 * @returns a pointer to `resource`
                 */
                ref(): HipGraphicsResource
                /**
                 * Decrements the reference count on `resource`
                 * @since 1.28
                 */
                unref(): void
            }

            interface $Exports {
                HipGraphicsResource: HipGraphicsResourceStruct
            }
            

            interface HipMemoryStruct {
                readonly $gtype: GObject.GType<HipMemory>
                new (fields?: {
                    mem?: Gst.Memory
                    device?: HipDevice
                    info?: GstVideo.VideoInfo
                }): HipMemory
            }

            interface HipMemory {
                
                mem: Gst.Memory
                
                device: HipDevice
                
                info: GstVideo.VideoInfo
                /**
                 * Gets HIP stream object associated with `mem`
                 * @since 1.28
                 * @returns a #GstHipStream or %NULL if default HIP stream is in use
                 */
                get_stream(): HipStream | null
                /**
                 * Creates hipTextureObject_t with given parameters
                 * @since 1.28
                 * @param plane the plane index
                 * @param filter_mode filter mode
                 * @param address_mode address mode
                 * @returns %TRUE if succeeded, a pointer to hipTextureObject_t object
                 */
                get_texture(plane: number, filter_mode: number, address_mode: number): [boolean, never | null]
                /**
                 * Sets `event` to `mem` for later synchronization operation
                 * @since 1.28
                 * @param event a #GstHipEvent
                 */
                set_event(event: HipEvent | null): void
                /**
                 * Waits for device synchronization by using previously configured #GstHipEvent
                 * via gst_hip_memory_set_event()
                 * @since 1.28
                 */
                sync(): void
            }

            interface $Exports {
                HipMemory: HipMemoryStruct
            }
            

            interface HipMemoryPrivateStruct {
                readonly $gtype: GObject.GType<HipMemoryPrivate>
                [Symbol.hasInstance](instance: unknown): instance is HipMemoryPrivate
            }

            interface HipMemoryPrivate {
            }

            interface $Exports {
                HipMemoryPrivate: HipMemoryPrivateStruct
            }
            

            interface HipPoolAllocatorPrivateStruct {
                readonly $gtype: GObject.GType<HipPoolAllocatorPrivate>
                [Symbol.hasInstance](instance: unknown): instance is HipPoolAllocatorPrivate
            }

            interface HipPoolAllocatorPrivate {
            }

            interface $Exports {
                HipPoolAllocatorPrivate: HipPoolAllocatorPrivateStruct
            }
            

            interface HipStreamStruct {
                readonly $gtype: GObject.GType<HipStream>
                /**
                 * Creates a new #GstHipStream object
                 * @since 1.28
                 * @param vendor a #GstHipVendor
                 * @param device_id device identifier
                 * @returns a #GstHipStream object or %NULL if failed
                 */
                new (vendor: HipVendor, device_id: number): HipStream | null
                /**
                 * Creates a new #GstHipStream object
                 * @since 1.28
                 * @param vendor a #GstHipVendor
                 * @param device_id device identifier
                 * @returns a #GstHipStream object or %NULL if failed
                 */
                "new"(vendor: HipVendor, device_id: number): HipStream | null
            }

            interface HipStream {
                /**
                 * Gets numeric device identifier of `stream` object
                 * @since 1.28
                 * @returns device identifier
                 */
                get_device_id(): number
                /**
                 * Gets hipStream_t handle owned by `stream`
                 * @since 1.28
                 * @returns hipStream_t handle
                 */
                get_handle(): never | null
                /**
                 * Gets device vendor of `stream` object
                 * @since 1.28
                 * @returns #GstHipVendor
                 */
                get_vendor(): HipVendor
                /**
                 * Records currently scheduled operations in `stream` to #GstHipEvent
                 * @since 1.28
                 * @returns %TRUE if succeeded, a location to store #GstHipEvent
                 */
                record_event(): [boolean, HipEvent | null]
                /**
                 * Increments the reference count on `stream`
                 * @since 1.28
                 * @returns a pointer to `stream`
                 */
                ref(): HipStream
                /**
                 * Decrements the reference count on `stream`
                 * @since 1.28
                 */
                unref(): void
            }

            interface $Exports {
                HipStream: HipStreamStruct
            }
            
            interface HipVendorEnum {
                readonly $gtype: GObject.GType<HipVendor>
                
                readonly "UNKNOWN": 0
                
                readonly "AMD": 1
                
                readonly "NVIDIA": 2
            }
            type HipVendor = HipVendorEnum[Exclude<keyof HipVendorEnum, "$gtype">]
            interface $Exports {
                /**
                 * @since 1.28
                 */
                HipVendor: HipVendorEnum
            }
            
            interface HipMemoryTransferBitfield {
                readonly $gtype: GObject.GType<HipMemoryTransfer>
                
                readonly "DOWNLOAD": 1048576
                
                readonly "UPLOAD": 2097152
            }
            type HipMemoryTransfer = number
            interface $Exports {
                
                HipMemoryTransfer: HipMemoryTransferBitfield
            }

            interface $Exports {
                __name__: "GstHip"
                __version__: "1.0"
                CAPS_FEATURE_MEMORY_HIP_MEMORY: "memory:HIPMemory"
                HIP_DEVICE_CONTEXT_TYPE: "gst.hip.device"
                HIP_MEMORY_NAME: "HIPMemory"
                MAP_HIP: Gst.MapFlags
                MAP_READ_HIP: Gst.MapFlags
                MAP_WRITE_HIP: Gst.MapFlags
                /**
                 * @since 1.28
                 * @param device a #GstHipDevice
                 * @returns a new #GstContext embedding the `device`
                 */
                context_new_hip_device(device: HipDevice): Gst.Context
                /**
                 * Perform the steps necessary for retrieving a #GstHipDevice from the
                 * surrounding elements or from the application using the #GstContext mechanism.
                 *
                 * If the content of `device` is not %NULL, then no #GstContext query is
                 * necessary for #GstHipDevice.
                 * @since 1.28
                 * @param element the #GstElement running the query
                 * @param vendor a #GstHipVendor
                 * @param device_id preferred device-id, pass device_id >=0 when             the device_id explicitly required. Otherwise, set -1.
                 * @returns whether a #GstHipDevice exists in `device`, the resulting #GstHipDevice
                 */
                hip_ensure_element_data(element: Gst.Element, vendor: HipVendor, device_id: number, device: HipDevice): [boolean, HipDevice]
                /**
                 * @since 1.28
                 * @param element a #GstElement
                 * @param query a #GstQuery of type %GST_QUERY_CONTEXT
                 * @param device a #GstHipDevice
                 * @returns Whether the `query` was successfully responded to from the passed          `context`.
                 */
                hip_handle_context_query(element: Gst.Element, query: Gst.Query, device: HipDevice | null): boolean
                /**
                 * Helper function for implementing #GstElementClass.set_context() in
                 * HIP capable elements.
                 *
                 * Retrieves the #GstHipDevice in `context` and places the result in `device`.
                 * @since 1.28
                 * @param element a #GstElement
                 * @param context a #GstContext
                 * @param vendor a #GstHipVendor
                 * @param device_id preferred device-id, pass device_id >=0 when             the device_id explicitly required. Otherwise, set -1.
                 * @returns whether the `device` could be set successfully, location of a #GstHipDevice
                 */
                hip_handle_set_context(element: Gst.Element, context: Gst.Context, vendor: HipVendor, device_id: number, device: HipDevice): [boolean, HipDevice]
                /**
                 * Opens `vendor` specific runtime libraries
                 * @since 1.28
                 * @param vendor a #GstHipVendor
                 * @returns %TRUE if succeeded
                 */
                hip_load_library(vendor: HipVendor): boolean
                /**
                 * Compiles `source` with given compile options
                 * @since 1.28
                 * @param device a #GstHipDevice
                 * @param source HIP kernel source
                 * @param options array of compile option string
                 * @param num_options option array size
                 * @returns Compiled kernel blob or %NULL if failed.  *
                 */
                hip_rtc_compile(device: HipDevice, source: string, options: string, num_options: number): string | null
                /**
                 * Opens `vendor` specific runtime compiler libraries
                 * @since 1.28
                 * @param vendor a #GstHipVendor
                 * @returns %TRUE if succeeded
                 */
                hip_rtc_load_library(vendor: HipVendor): boolean
                /**
                 * @since 1.28
                 * @param mem a #GstMemory
                 * @returns %TRUE if `mem` is a #GstHipMemory
                 */
                is_hip_memory(mem: Gst.Memory): boolean
            }
        }

        const GstHip: GstHip.$Exports
    }

    export default GI.GstHip
}