
/// <reference path="./GLib-2.0.d.ts" />
/// <reference path="./GModule-2.0.d.ts" />
/// <reference path="./GObject-2.0.d.ts" />
/// <reference path="./Gst-1.0.d.ts" />
/// <reference path="./GstBase-1.0.d.ts" />
/// <reference path="./GstAudio-1.0.d.ts" />
/// <reference path="./GstVideo-1.0.d.ts" />
/// <reference path="./GstPbutils-1.0.d.ts" />
/// <reference path="./GstTag-1.0.d.ts" />

/**
 * Type Definitions for GJS (https://gjs.guide/), generated by [GirGen](https://github.com/aylur/girgen)
 * If you found a bug, create a bug report on [GirGen's Repository](https://github.com/aylur/girgen/issues/new)
 */
declare module "gi://GstPlay?version=1.0" {
    import type GLib from "gi://GLib?version=2.0"
    import type GModule from "gi://GModule?version=2.0"
    import type GObject from "gi://GObject?version=2.0"
    import type Gst from "gi://Gst?version=1.0"
    import type GstBase from "gi://GstBase?version=1.0"
    import type GstAudio from "gi://GstAudio?version=1.0"
    import type GstVideo from "gi://GstVideo?version=1.0"
    import type GstPbutils from "gi://GstPbutils?version=1.0"
    import type GstTag from "gi://GstTag?version=1.0"

    /**
     * Do **not** import this at runtime.
     * This namespace is only exported for module augmentation.
     */
    export namespace GI {
        

        namespace GstPlay {
            

            namespace Play {
                interface SignalSignatures extends Gst.Object.SignalSignatures {
                }

                interface ReadWriteProperties extends Gst.Object.ReadWriteProperties {
                    "audio-video-offset": number
                    "mute": boolean
                    "rate": number
                    "subtitle-video-offset": number
                    "suburi": string
                    "uri": string | null
                    "video-multiview-flags": GstVideo.VideoMultiviewFlags
                    "video-multiview-mode": GstVideo.VideoMultiviewFramePacking
                    "video-renderer": PlayVideoRenderer
                    "volume": number
                }

                interface ReadableProperties extends ReadWriteProperties, Gst.Object.ReadableProperties {
                    "current-audio-track": PlayAudioInfo | null
                    "current-subtitle-track": PlaySubtitleInfo | null
                    "current-video-track": PlayVideoInfo | null
                    "duration": number
                    "media-info": PlayMediaInfo | null
                    "pipeline": Gst.Element
                    "position": number
                }

                interface WritableProperties extends ReadWriteProperties, Gst.Object.WritableProperties {
                }

                interface ConstructOnlyProperties extends Gst.Object.ConstructOnlyProperties {
                }
            }

            interface Play extends Gst.Object {
                readonly $signals: Play.SignalSignatures
                readonly $readableProperties: Play.ReadableProperties
                readonly $writableProperties: Play.WritableProperties
                readonly $constructOnlyProperties: Play.ConstructOnlyProperties
                /**
                 * @default 0
                 */
                get audioVideoOffset(): number
                set audioVideoOffset(value: number)
                
                get currentAudioTrack(): PlayAudioInfo | null
                
                get currentSubtitleTrack(): PlaySubtitleInfo | null
                
                get currentVideoTrack(): PlayVideoInfo | null
                /**
                 * @default 18446744073709551615
                 */
                get duration(): number
                
                get mediaInfo(): PlayMediaInfo | null
                /**
                 * @default FALSE
                 */
                get mute(): boolean
                set mute(value: boolean)
                
                get pipeline(): Gst.Element
                /**
                 * @default 18446744073709551615
                 */
                get position(): number
                /**
                 * @default 1.000000
                 */
                get rate(): number
                set rate(value: number)
                /**
                 * @default 0
                 */
                get subtitleVideoOffset(): number
                set subtitleVideoOffset(value: number)
                /**
                 * @default NULL
                 */
                get suburi(): string
                set suburi(value: string)
                /**
                 * @default NULL
                 */
                get uri(): string | null
                set uri(value: string | null)
                /**
                 * @default GST_VIDEO_MULTIVIEW_FLAGS_NONE
                 */
                get videoMultiviewFlags(): GstVideo.VideoMultiviewFlags
                set videoMultiviewFlags(value: GstVideo.VideoMultiviewFlags)
                /**
                 * @default GST_VIDEO_MULTIVIEW_FRAME_PACKING_NONE
                 */
                get videoMultiviewMode(): GstVideo.VideoMultiviewFramePacking
                set videoMultiviewMode(value: GstVideo.VideoMultiviewFramePacking)
                
                get videoRenderer(): PlayVideoRenderer
                set videoRenderer(value: PlayVideoRenderer)
                /**
                 * @default 1.000000
                 */
                get volume(): number
                set volume(value: number)
                /**
                 * Retrieve the current value of audio-video-offset property
                 * @since 1.20
                 * @returns The current value of audio-video-offset in nanoseconds
                 */
                get_audio_video_offset(): number
                /**
                 * Retrieve the current value of the indicated `type`.
                 * @since 1.20
                 * @param type #GstPlayColorBalanceType
                 * @returns The current value of `type`, between [0,1]. In case of   error -1 is returned.
                 */
                get_color_balance(type: PlayColorBalanceType): number
                /**
                 * Get a copy of the current configuration of the play. This configuration
                 * can either be modified and used for the gst_play_set_config() call
                 * or it must be freed after usage.
                 * @since 1.20
                 * @returns a copy of the current configuration of `play`. Use gst_structure_free() after usage or gst_play_set_config().
                 */
                get_config(): Gst.Structure
                /**
                 * A Function to get current audio #GstPlayAudioInfo instance.
                 * @since 1.20
                 * @returns current audio track.  The caller should free it with g_object_unref()
                 */
                get_current_audio_track(): PlayAudioInfo | null
                /**
                 * A Function to get current subtitle #GstPlaySubtitleInfo instance.
                 * @since 1.20
                 * @returns current subtitle track.  The caller should free it with g_object_unref()
                 */
                get_current_subtitle_track(): PlaySubtitleInfo | null
                /**
                 * A Function to get current video #GstPlayVideoInfo instance.
                 * @since 1.20
                 * @returns current video track.  The caller should free it with g_object_unref()
                 */
                get_current_video_track(): PlayVideoInfo | null
                /**
                 * @since 1.20
                 * @returns Name of the currently enabled   visualization.   g_free() after usage.
                 */
                get_current_visualization(): string | null
                /**
                 * Retrieves the duration of the media stream that self represents.
                 * @since 1.20
                 * @returns the duration of the currently-playing media stream, in nanoseconds.
                 */
                get_duration(): Gst.ClockTime
                /**
                 * A Function to get the current media info #GstPlayMediaInfo instance.
                 * @since 1.20
                 * @returns media info instance.  The caller should free it with g_object_unref()
                 */
                get_media_info(): PlayMediaInfo | null
                /**
                 * GstPlay API exposes a #GstBus instance which purpose is to provide data
                 * structures representing play-internal events in form of #GstMessage<!-- -->s of
                 * type GST_MESSAGE_APPLICATION.
                 *
                 * Each message carries a "play-message" field of type #GstPlayMessage.
                 * Further fields of the message data are specific to each possible value of
                 * that enumeration.
                 *
                 * Applications can consume the messages asynchronously within their own
                 * event-loop / UI-thread etc. Note that in case the application does not
                 * consume the messages, the bus will accumulate these internally and eventually
                 * fill memory. To avoid that, the bus has to be set "flushing".
                 * @since 1.20
                 * @returns The play message bus instance
                 */
                get_message_bus(): Gst.Bus
                /**
                 * Retrieve the current value of the indicated `type`.
                 * @since 1.20
                 * @returns The current value of `type`, Default: 0x00000000 "none
                 */
                get_multiview_flags(): GstVideo.VideoMultiviewFlags
                /**
                 * Retrieve the current value of the indicated `type`.
                 * @since 1.20
                 * @returns The current value of `type`, Default: -1 "none"
                 */
                get_multiview_mode(): GstVideo.VideoMultiviewFramePacking
                /**
                 * @since 1.20
                 * @returns %TRUE if the currently-playing stream is muted.
                 */
                get_mute(): boolean
                /**
                 * @since 1.20
                 * @returns The internal playbin instance.  The caller should free it with g_object_unref()
                 */
                get_pipeline(): Gst.Element
                /**
                 * @since 1.20
                 * @returns the absolute position time, in nanoseconds, of the currently-playing stream.
                 */
                get_position(): Gst.ClockTime
                /**
                 * @since 1.20
                 * @returns current playback rate
                 */
                get_rate(): number
                /**
                 * Current subtitle URI
                 * @since 1.20
                 * @returns URI of the current external subtitle.   g_free() after usage.
                 */
                get_subtitle_uri(): string | null
                /**
                 * Retrieve the current value of subtitle-video-offset property
                 * @since 1.20
                 * @returns The current value of subtitle-video-offset in nanoseconds
                 */
                get_subtitle_video_offset(): number
                /**
                 * Gets the URI of the currently-playing stream.
                 * @since 1.20
                 * @returns a string containing the URI of the currently-playing stream. g_free() after usage.
                 */
                get_uri(): string | null
                /**
                 * Get a snapshot of the currently selected video stream, if any. The format can be
                 * selected with `format` and optional configuration is possible with `config`.
                 * Currently supported settings are:
                 * - width, height of type G_TYPE_INT
                 * - pixel-aspect-ratio of type GST_TYPE_FRACTION
                 *  Except for GST_PLAY_THUMBNAIL_RAW_NATIVE format, if no config is set, pixel-aspect-ratio would be 1/1
                 * @since 1.20
                 * @param format output format of the video snapshot
                 * @param config Additional configuration
                 * @returns Current video snapshot sample or %NULL on failure
                 */
                get_video_snapshot(format: PlaySnapshotFormat, config: Gst.Structure | null): Gst.Sample | null
                /**
                 * Returns the current volume level, as a percentage between 0 and 1.
                 * @since 1.20
                 * @returns the volume as percentage between 0 and 1.
                 */
                get_volume(): number
                /**
                 * Checks whether the `play` has color balance support available.
                 * @since 1.20
                 * @returns %TRUE if `play` has color balance support. Otherwise,   %FALSE.
                 */
                has_color_balance(): boolean
                /**
                 * Pauses the current stream.
                 * @since 1.20
                 */
                pause(): void
                /**
                 * Request to play the loaded stream.
                 * @since 1.20
                 */
                play(): void
                /**
                 * Seeks the currently-playing stream to the absolute `position` time
                 * in nanoseconds.
                 * @since 1.20
                 * @param position position to seek in nanoseconds
                 */
                seek(position: Gst.ClockTime): void
                /**
                 * @since 1.20
                 * @deprecated since 1.26 Use gst_play_set_audio_track_id() instead.
                 * @param stream_index stream index
                 * @returns %TRUE or %FALSE  Sets the audio track `stream_index`.
                 */
                set_audio_track(stream_index: number): boolean
                /**
                 * Enable or disable the current audio track.
                 * @since 1.20
                 * @param enabled TRUE or FALSE
                 */
                set_audio_track_enabled(enabled: boolean): void
                /**
                 * @since 1.26
                 * @param stream_id stream id
                 * @returns %TRUE or %FALSE  Sets the audio track `stream_id`.
                 */
                set_audio_track_id(stream_id: string | null): boolean
                /**
                 * Sets audio-video-offset property by value of `offset`
                 * @since 1.20
                 * @param offset #gint64 in nanoseconds
                 */
                set_audio_video_offset(offset: number): void
                /**
                 * Sets the current value of the indicated channel `type` to the passed
                 * value.
                 * @since 1.20
                 * @param type #GstPlayColorBalanceType
                 * @param value The new value for the `type`, ranged [0,1]
                 */
                set_color_balance(type: PlayColorBalanceType, value: number): void
                /**
                 * Set the configuration of the play. If the play is already configured, and
                 * the configuration hasn't changed, this function will return %TRUE. If the
                 * play is not in the GST_PLAY_STATE_STOPPED, this method will return %FALSE
                 * and active configuration will remain.
                 *
                 *  `config` is a #GstStructure that contains the configuration parameters for
                 * the play.
                 *
                 * This function takes ownership of `config`.
                 * @since 1.20
                 * @param config a #GstStructure
                 * @returns %TRUE when the configuration could be set.
                 */
                set_config(config: Gst.Structure): boolean
                /**
                 * Sets the current value of the indicated mode `type` to the passed
                 * value.
                 * @since 1.20
                 * @param flags The new value for the `type`
                 */
                set_multiview_flags(flags: GstVideo.VideoMultiviewFlags): void
                /**
                 * Sets the current value of the indicated mode `type` to the passed
                 * value.
                 * @since 1.20
                 * @param mode The new value for the `type`
                 */
                set_multiview_mode(mode: GstVideo.VideoMultiviewFramePacking): void
                /**
                 * %TRUE if the currently-playing stream should be muted.
                 * @since 1.20
                 * @param val Mute state the should be set
                 */
                set_mute(val: boolean): void
                /**
                 * Playback at specified rate
                 * @since 1.20
                 * @param rate playback rate
                 */
                set_rate(rate: number): void
                /**
                 * @since 1.20
                 * @deprecated since 1.26 Use gst_play_set_subtitle_track_id() instead.
                 * @param stream_index stream index
                 * @returns %TRUE or %FALSE  Sets the subtitle stack `stream_index`.
                 */
                set_subtitle_track(stream_index: number): boolean
                /**
                 * Enable or disable the current subtitle track.
                 * @since 1.20
                 * @param enabled TRUE or FALSE
                 */
                set_subtitle_track_enabled(enabled: boolean): void
                /**
                 * @since 1.26
                 * @param stream_id stream id
                 * @returns %TRUE or %FALSE  Sets the subtitle track `stream_id`.
                 */
                set_subtitle_track_id(stream_id: string | null): boolean
                /**
                 * Sets the external subtitle URI. This should be combined with a call to
                 * gst_play_set_subtitle_track_enabled(@play, TRUE) so the subtitles are actually
                 * rendered.
                 * @since 1.20
                 * @param uri subtitle URI
                 */
                set_subtitle_uri(uri: string | null): void
                /**
                 * Sets subtitle-video-offset property by value of `offset`
                 * @since 1.20
                 * @param offset #gint64 in nanoseconds
                 */
                set_subtitle_video_offset(offset: number): void
                /**
                 * @since 1.26
                 * @param audio_stream_id audio stream id
                 * @param video_stream_id video stream id
                 * @param subtitle_stream_id subtitle stream id
                 * @returns %TRUE or %FALSE  Sets the selected track stream ids. Setting %NULL as stream id disables the corresponding track.
                 */
                set_track_ids(audio_stream_id: string | null, video_stream_id: string | null, subtitle_stream_id: string | null): boolean
                /**
                 * Sets the next URI to play.
                 * @since 1.20
                 * @param uri next URI to play.
                 */
                set_uri(uri: string | null): void
                /**
                 * @since 1.20
                 * @deprecated since 1.26 Use gst_play_set_video_track_id() instead.
                 * @param stream_index stream index
                 * @returns %TRUE or %FALSE  Sets the video track `stream_index`.
                 */
                set_video_track(stream_index: number): boolean
                /**
                 * Enable or disable the current video track.
                 * @since 1.20
                 * @param enabled TRUE or FALSE
                 */
                set_video_track_enabled(enabled: boolean): void
                /**
                 * @since 1.26
                 * @param stream_id stream id
                 * @returns %TRUE or %FALSE  Sets the video track `stream_id`.
                 */
                set_video_track_id(stream_id: string | null): boolean
                /**
                 * @since 1.20
                 * @param name visualization element obtained from #gst_play_visualizations_get()
                 * @returns %TRUE if the visualization was set correctly. Otherwise, %FALSE.
                 */
                set_visualization(name: string | null): boolean
                /**
                 * Enable or disable the visualization.
                 * @since 1.20
                 * @param enabled TRUE or FALSE
                 */
                set_visualization_enabled(enabled: boolean): void
                /**
                 * Sets the volume level of the stream as a percentage between 0 and 1.
                 * @since 1.20
                 * @param val the new volume level, as a percentage between 0 and 1
                 */
                set_volume(val: number): void
                /**
                 * Stops playing the current stream and resets to the first position
                 * in the stream.
                 * @since 1.20
                 */
                stop(): void
            }

            interface PlayClass extends Omit<Gst.ObjectClass, "new"> {
                readonly $gtype: GObject.GType<Play>
                readonly prototype: Play

                new (props?: Partial<GObject.ConstructorProps<Play>>): Play
                /**
                 * Creates a new #GstPlay instance.
                 *
                 * Video is going to be rendered by `video_renderer`, or if %NULL is provided
                 * no special video set up will be done and some default handling will be
                 * performed.
                 *
                 * This also initializes GStreamer via `gst_init()` on the first call if this
                 * didn't happen before.
                 * @since 1.20
                 * @param video_renderer GstPlayVideoRenderer to use
                 * @returns a new #GstPlay instance
                 */
                "new"(video_renderer: PlayVideoRenderer | null): Play
                /**
                 * @since 1.28
                 * @param config a #GstPlay configuration
                 * @returns The looping mode.
                 */
                config_get_loop(config: Gst.Structure): PlayLoop
                /**
                 * @since 1.24
                 * @param config a #GstPlay configuration
                 * @returns %TRUE if pipeline dumps are included in #GstPlay error message details.
                 */
                config_get_pipeline_dump_in_error_details(config: Gst.Structure): boolean
                /**
                 * @since 1.20
                 * @param config a #GstPlay configuration
                 * @returns current position update interval in milliseconds
                 */
                config_get_position_update_interval(config: Gst.Structure): number
                /**
                 * @since 1.20
                 * @param config a #GstPlay configuration
                 * @returns %TRUE if accurate seeking is enabled
                 */
                config_get_seek_accurate(config: Gst.Structure): boolean
                /**
                 * Return the user agent which has been configured using
                 * gst_play_config_set_user_agent() if any.
                 * @since 1.20
                 * @param config a #GstPlay configuration
                 * @returns the configured agent, or %NULL
                 */
                config_get_user_agent(config: Gst.Structure): string | null
                /**
                 * Sets the looping mode.
                 *
                 * Looping is disabled by default.
                 * @since 1.28
                 * @param config a #GstPlay configuration
                 * @param loop #GstPlayLoop
                 */
                config_set_loop(config: Gst.Structure, loop: PlayLoop): void
                /**
                 * When enabled, the error message emitted by #GstPlay will include a pipeline
                 * dump (in Graphviz DOT format) in the error details #GstStructure. The field
                 * name is `pipeline-dump`.
                 *
                 * This option is disabled by default.
                 * @since 1.24
                 * @param config a #GstPlay configuration
                 * @param value Include pipeline dumps in error details, or not.
                 */
                config_set_pipeline_dump_in_error_details(config: Gst.Structure, value: boolean): void
                /**
                 * Set desired interval in milliseconds between two position-updated messages.
                 * Pass 0 to stop updating the position.
                 * @since 1.20
                 * @param config a #GstPlay configuration
                 * @param interval interval in ms
                 */
                config_set_position_update_interval(config: Gst.Structure, interval: number): void
                /**
                 * Enable or disable accurate seeking. When enabled, elements will try harder
                 * to seek as accurately as possible to the requested seek position. Generally
                 * it will be slower especially for formats that don't have any indexes or
                 * timestamp markers in the stream.
                 *
                 * If accurate seeking is disabled, elements will seek as close as the request
                 * position without slowing down seeking too much.
                 *
                 * Accurate seeking is disabled by default.
                 * @since 1.20
                 * @param config a #GstPlay configuration
                 * @param accurate accurate seek or not
                 */
                config_set_seek_accurate(config: Gst.Structure, accurate: boolean): void
                /**
                 * Set the user agent to pass to the server if `play` needs to connect
                 * to a server during playback. This is typically used when playing HTTP
                 * or RTSP streams.
                 * @since 1.20
                 * @param config a #GstPlay configuration
                 * @param agent the string to use as user agent
                 */
                config_set_user_agent(config: Gst.Structure, agent: string | null): void
                /**
                 * @since 1.20
                 * @param info a #GstPlayMediaInfo
                 * @returns A #GList of matching #GstPlayAudioInfo.
                 */
                get_audio_streams(info: PlayMediaInfo): PlayAudioInfo[]
                /**
                 * @since 1.20
                 * @param info a #GstPlayMediaInfo
                 * @returns A #GList of matching #GstPlaySubtitleInfo.
                 */
                get_subtitle_streams(info: PlayMediaInfo): PlaySubtitleInfo[]
                /**
                 * @since 1.20
                 * @param info a #GstPlayMediaInfo
                 * @returns A #GList of matching #GstPlayVideoInfo.
                 */
                get_video_streams(info: PlayMediaInfo): PlayVideoInfo[]
                /**
                 * @since 1.20
                 * @param msg A #GstMessage
                 * @returns A #gboolean indicating whether the passed message represents a #GstPlay message or not.
                 */
                is_play_message(msg: Gst.Message): boolean
                /**
                 * Frees a %NULL terminated array of #GstPlayVisualization.
                 * @since 1.20
                 * @param viss a %NULL terminated array of #GstPlayVisualization to free
                 */
                visualizations_free(viss: PlayVisualization): void
                /**
                 * @since 1.20
                 * @returns   a %NULL terminated array containing all available  visualizations. Use gst_play_visualizations_free() after  usage.
                 */
                visualizations_get(): PlayVisualization[]
            }

            interface $Exports {
                /**
                 * The goal of the GstPlay library is to ease the integration of multimedia
                 * playback features in applications. Thus, if you need to build a media player
                 * from the ground-up, GstPlay provides the features you will most likely need.
                 *
                 * An example player is available in gst-examples/playback/player/gst-play/.
                 *
                 * Internally the GstPlay makes use of the `playbin3` element. The legacy
                 * `playbin2` can be selected if the `GST_PLAY_USE_PLAYBIN3=0` environment
                 * variable has been set.
                 *
                 * **Important note**: If your application relies on the GstBus to get
                 * notifications from GstPlay, you need to add some explicit clean-up code in
                 * order to prevent the GstPlay object from leaking. See below for the details.
                 * If you use the GstPlaySignalAdapter, no special clean-up is required.
                 *
                 * When the GstPlaySignalAdapter is not used, the GstBus owned by GstPlay should
                 * be set to flushing state before any attempt to drop the last reference of the
                 * GstPlay object. An example in C:
                 *
                 * ```c
                 * ...
                 * GstBus *bus = gst_play_get_message_bus (player);
                 * gst_bus_set_flushing (bus, TRUE);
                 * gst_object_unref (bus);
                 * gst_object_unref (player);
                 * ```
                 *
                 * The messages managed by the player contain a reference to itself, and if the
                 * bus watch is just removed together with dropping the player then the bus will
                 * simply keep them around forever (and the bus never goes away because the
                 * player has a strong reference to it, so there's a reference cycle as long as
                 * there are messages). Setting the bus to flushing state forces it to get rid
                 * of its queued messages, thus breaking any possible reference cycle.
                 * @since 1.20
                 */
                Play: PlayClass
            }
            

            namespace PlayAudioInfo {
                interface SignalSignatures extends PlayStreamInfo.SignalSignatures {
                }

                interface ReadWriteProperties extends PlayStreamInfo.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, PlayStreamInfo.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, PlayStreamInfo.WritableProperties {
                }

                interface ConstructOnlyProperties extends PlayStreamInfo.ConstructOnlyProperties {
                }
            }

            interface PlayAudioInfo extends PlayStreamInfo {
                readonly $signals: PlayAudioInfo.SignalSignatures
                readonly $readableProperties: PlayAudioInfo.ReadableProperties
                readonly $writableProperties: PlayAudioInfo.WritableProperties
                readonly $constructOnlyProperties: PlayAudioInfo.ConstructOnlyProperties
                /**
                 * @since 1.20
                 * @returns the audio bitrate in #GstPlayAudioInfo or -1 if unknown.
                 */
                get_bitrate(): number
                /**
                 * @since 1.20
                 * @returns the number of audio channels in #GstPlayAudioInfo or 0 if unknown.
                 */
                get_channels(): number
                /**
                 * @since 1.20
                 * @returns the language of the stream, or %NULL if unknown.
                 */
                get_language(): string | null
                /**
                 * @since 1.20
                 * @returns the audio maximum bitrate in #GstPlayAudioInfo or -1 if unknown.
                 */
                get_max_bitrate(): number
                /**
                 * @since 1.20
                 * @returns the audio sample rate in #GstPlayAudioInfo or 0 if unknown.
                 */
                get_sample_rate(): number
            }

            interface PlayAudioInfoClass extends Omit<PlayStreamInfoClass, "new"> {
                readonly $gtype: GObject.GType<PlayAudioInfo>
                readonly prototype: PlayAudioInfo

                new (props?: Partial<GObject.ConstructorProps<PlayAudioInfo>>): PlayAudioInfo
            }

            interface $Exports {
                /**
                 * #GstPlayStreamInfo specific to audio streams.
                 * @since 1.20
                 */
                PlayAudioInfo: PlayAudioInfoClass
            }
            

            namespace PlayMediaInfo {
                interface SignalSignatures extends GObject.Object.SignalSignatures {
                }

                interface ReadWriteProperties extends GObject.Object.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, GObject.Object.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, GObject.Object.WritableProperties {
                }

                interface ConstructOnlyProperties extends GObject.Object.ConstructOnlyProperties {
                }
            }

            interface PlayMediaInfo extends GObject.Object {
                readonly $signals: PlayMediaInfo.SignalSignatures
                readonly $readableProperties: PlayMediaInfo.ReadableProperties
                readonly $writableProperties: PlayMediaInfo.WritableProperties
                readonly $constructOnlyProperties: PlayMediaInfo.ConstructOnlyProperties
                /**
                 * @since 1.20
                 * @returns A #GList of matching #GstPlayAudioInfo.
                 */
                get_audio_streams(): PlayAudioInfo[]
                /**
                 * @since 1.20
                 * @returns the container format or %NULL if unknown.
                 */
                get_container_format(): string | null
                /**
                 * @since 1.20
                 * @returns duration of the media.
                 */
                get_duration(): Gst.ClockTime
                /**
                 * Function to get the image (or preview-image) stored in taglist.
                 * Application can use `gst_sample_*_()` API's to get caps, buffer etc.
                 * @since 1.20
                 * @returns GstSample or %NULL.
                 */
                get_image_sample(): Gst.Sample | null
                /**
                 * @since 1.20
                 * @returns number of audio streams.
                 */
                get_number_of_audio_streams(): number
                /**
                 * @since 1.20
                 * @returns number of total streams.
                 */
                get_number_of_streams(): number
                /**
                 * @since 1.20
                 * @returns number of subtitle streams.
                 */
                get_number_of_subtitle_streams(): number
                /**
                 * @since 1.20
                 * @returns number of video streams.
                 */
                get_number_of_video_streams(): number
                /**
                 * @since 1.20
                 * @returns A #GList of matching #GstPlayStreamInfo.
                 */
                get_stream_list(): PlayStreamInfo[]
                /**
                 * @since 1.20
                 * @returns A #GList of matching #GstPlaySubtitleInfo.
                 */
                get_subtitle_streams(): PlaySubtitleInfo[]
                /**
                 * @since 1.20
                 * @returns the tags contained in media info.
                 */
                get_tags(): Gst.TagList | null
                /**
                 * @since 1.20
                 * @returns the media title or %NULL if unknown.
                 */
                get_title(): string | null
                /**
                 * @since 1.20
                 * @returns the URI associated with #GstPlayMediaInfo.
                 */
                get_uri(): string
                /**
                 * @since 1.20
                 * @returns A #GList of matching #GstPlayVideoInfo.
                 */
                get_video_streams(): PlayVideoInfo[]
                /**
                 * @since 1.20
                 * @returns %TRUE if the media is live.
                 */
                is_live(): boolean
                /**
                 * @since 1.20
                 * @returns %TRUE if the media is seekable.
                 */
                is_seekable(): boolean
            }

            interface PlayMediaInfoClass extends Omit<GObject.ObjectClass, "new"> {
                readonly $gtype: GObject.GType<PlayMediaInfo>
                readonly prototype: PlayMediaInfo

                new (props?: Partial<GObject.ConstructorProps<PlayMediaInfo>>): PlayMediaInfo
            }

            interface $Exports {
                /**
                 * Structure containing the media information of a URI.
                 * @since 1.20
                 */
                PlayMediaInfo: PlayMediaInfoClass
            }
            

            namespace PlaySignalAdapter {
                interface SignalSignatures extends GObject.Object.SignalSignatures {
                    /**
                     * @param object
                     */
                    "buffering"(object: number): void
                    /**
                     * @param object
                     */
                    "duration-changed"(object: number): void
                    
                    "end-of-stream"(): void
                    /**
                     * Emitted on errors.
                     * @param error The error
                     * @param details Additional error details
                     */
                    "error"(error: GLib.Error, details: Gst.Structure | null): void
                    /**
                     * @param object
                     */
                    "media-info-updated"(object: PlayMediaInfo): void
                    /**
                     * @param object
                     */
                    "mute-changed"(object: boolean): void
                    /**
                     * @param object
                     */
                    "position-updated"(object: number): void
                    /**
                     * @param object
                     */
                    "seek-done"(object: number): void
                    /**
                     * @param object
                     */
                    "state-changed"(object: PlayState): void
                    /**
                     * @param object
                     */
                    "uri-loaded"(object: string): void
                    /**
                     * @param object
                     * @param p0
                     */
                    "video-dimensions-changed"(object: number, p0: number): void
                    /**
                     * @param object
                     */
                    "volume-changed"(object: number): void
                    /**
                     * Emitted on warnings.
                     * @param error The warning
                     * @param details Additional warning details
                     */
                    "warning"(error: GLib.Error, details: Gst.Structure | null): void
                }

                interface ReadWriteProperties extends GObject.Object.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, GObject.Object.ReadableProperties {
                    "play": Play
                }

                interface WritableProperties extends ReadWriteProperties, GObject.Object.WritableProperties {
                }

                interface ConstructOnlyProperties extends GObject.Object.ConstructOnlyProperties {
                }
            }

            interface PlaySignalAdapter extends GObject.Object {
                readonly $signals: PlaySignalAdapter.SignalSignatures
                readonly $readableProperties: PlaySignalAdapter.ReadableProperties
                readonly $writableProperties: PlaySignalAdapter.WritableProperties
                readonly $constructOnlyProperties: PlaySignalAdapter.ConstructOnlyProperties
                
                get play(): Play
                /**
                 * @since 1.20
                 * @returns The #GstPlay owning this signal adapter.
                 */
                get_play(): Play
            }

            interface PlaySignalAdapterClass extends Omit<GObject.ObjectClass, "new"> {
                readonly $gtype: GObject.GType<PlaySignalAdapter>
                readonly prototype: PlaySignalAdapter

                new (props?: Partial<GObject.ConstructorProps<PlaySignalAdapter>>): PlaySignalAdapter
                /**
                 * A bus-watching #GSource will be created and attached to the the
                 * thread-default #GMainContext. The attached callback will emit the
                 * corresponding signal for the message received. Matching signals for play
                 * messages from the bus will be emitted by it on the created adapter object.
                 * @since 1.20
                 * @param play #GstPlay instance to emit signals for.
                 * @returns A new #GstPlaySignalAdapter to connect signal handlers to.
                 */
                "new"(play: Play): PlaySignalAdapter
                /**
                 * Create an adapter that synchronously emits its signals, from the thread in
                 * which the messages have been posted.
                 * @since 1.20
                 * @param play #GstPlay instance to emit signals for.
                 * @returns A new #GstPlaySignalAdapter to connect signal handlers to.
                 */
                new_sync_emit(play: Play): PlaySignalAdapter
                /**
                 * A bus-watching #GSource will be created and attached to the `context`. The
                 * attached callback will emit the corresponding signal for the message
                 * received. Matching signals for play messages from the bus will be emitted by
                 * it on the created adapter object.
                 * @since 1.20
                 * @param play #GstPlay instance to emit signals for.
                 * @param context A #GMainContext on which the main-loop will process play bus messages on.
                 * @returns A new #GstPlaySignalAdapter to connect signal handlers to.
                 */
                new_with_main_context(play: Play, context: GLib.MainContext): PlaySignalAdapter
            }

            interface $Exports {
                /**
                 * @since 1.20
                 */
                PlaySignalAdapter: PlaySignalAdapterClass
            }
            

            namespace PlayStreamInfo {
                interface SignalSignatures extends GObject.Object.SignalSignatures {
                }

                interface ReadWriteProperties extends GObject.Object.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, GObject.Object.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, GObject.Object.WritableProperties {
                }

                interface ConstructOnlyProperties extends GObject.Object.ConstructOnlyProperties {
                }
            }

            interface PlayStreamInfo extends GObject.Object {
                readonly $signals: PlayStreamInfo.SignalSignatures
                readonly $readableProperties: PlayStreamInfo.ReadableProperties
                readonly $writableProperties: PlayStreamInfo.WritableProperties
                readonly $constructOnlyProperties: PlayStreamInfo.ConstructOnlyProperties
                /**
                 * @since 1.20
                 * @returns the #GstCaps of the stream or %NULL if unknown.
                 */
                get_caps(): Gst.Caps | null
                /**
                 * A string describing codec used in #GstPlayStreamInfo.
                 * @since 1.20
                 * @returns codec string or %NULL on unknown.
                 */
                get_codec(): string | null
                /**
                 * Function to get stream index from #GstPlayStreamInfo instance or -1 if
                 * unknown.
                 * @since 1.20
                 * @deprecated since 1.26 Use gst_play_stream_info_get_stream_id().
                 * @returns the stream index of this stream.
                 */
                get_index(): number
                /**
                 * A string stream id identifying this #GstPlayStreamInfo.
                 * @since 1.26
                 * @returns stream id string.
                 */
                get_stream_id(): string
                /**
                 * Function to return human readable name for the stream type
                 * of the given `info` (ex: "audio", "video", "subtitle")
                 * @since 1.20
                 * @returns a human readable name
                 */
                get_stream_type(): string
                /**
                 * @since 1.20
                 * @returns the tags contained in this stream.
                 */
                get_tags(): Gst.TagList | null
            }

            interface PlayStreamInfoClass extends Omit<GObject.ObjectClass, "new"> {
                readonly $gtype: GObject.GType<PlayStreamInfo>
                readonly prototype: PlayStreamInfo

                new (props?: Partial<GObject.ConstructorProps<PlayStreamInfo>>): PlayStreamInfo
            }

            interface $Exports {
                /**
                 * Base structure for information concerning a media stream. Depending on
                 * the stream type, one can find more media-specific information in
                 * #GstPlayVideoInfo, #GstPlayAudioInfo, #GstPlaySubtitleInfo.
                 * @since 1.20
                 */
                PlayStreamInfo: PlayStreamInfoClass
            }
            

            namespace PlaySubtitleInfo {
                interface SignalSignatures extends PlayStreamInfo.SignalSignatures {
                }

                interface ReadWriteProperties extends PlayStreamInfo.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, PlayStreamInfo.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, PlayStreamInfo.WritableProperties {
                }

                interface ConstructOnlyProperties extends PlayStreamInfo.ConstructOnlyProperties {
                }
            }

            interface PlaySubtitleInfo extends PlayStreamInfo {
                readonly $signals: PlaySubtitleInfo.SignalSignatures
                readonly $readableProperties: PlaySubtitleInfo.ReadableProperties
                readonly $writableProperties: PlaySubtitleInfo.WritableProperties
                readonly $constructOnlyProperties: PlaySubtitleInfo.ConstructOnlyProperties
                /**
                 * @since 1.20
                 * @returns the language of the stream, or %NULL if unknown.
                 */
                get_language(): string | null
            }

            interface PlaySubtitleInfoClass extends Omit<PlayStreamInfoClass, "new"> {
                readonly $gtype: GObject.GType<PlaySubtitleInfo>
                readonly prototype: PlaySubtitleInfo

                new (props?: Partial<GObject.ConstructorProps<PlaySubtitleInfo>>): PlaySubtitleInfo
            }

            interface $Exports {
                /**
                 * #GstPlayStreamInfo specific to subtitle streams.
                 * @since 1.20
                 */
                PlaySubtitleInfo: PlaySubtitleInfoClass
            }
            

            namespace PlayVideoInfo {
                interface SignalSignatures extends PlayStreamInfo.SignalSignatures {
                }

                interface ReadWriteProperties extends PlayStreamInfo.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, PlayStreamInfo.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, PlayStreamInfo.WritableProperties {
                }

                interface ConstructOnlyProperties extends PlayStreamInfo.ConstructOnlyProperties {
                }
            }

            interface PlayVideoInfo extends PlayStreamInfo {
                readonly $signals: PlayVideoInfo.SignalSignatures
                readonly $readableProperties: PlayVideoInfo.ReadableProperties
                readonly $writableProperties: PlayVideoInfo.WritableProperties
                readonly $constructOnlyProperties: PlayVideoInfo.ConstructOnlyProperties
                /**
                 * @since 1.20
                 * @returns the current bitrate of video in #GstPlayVideoInfo or -1 if unknown.
                 */
                get_bitrate(): number
                /**
                 * @since 1.20
                 * @returns , Numerator of frame rate, Denominator of frame rate
                 */
                get_framerate(): [number, number]
                /**
                 * @since 1.20
                 * @returns the height of video in #GstPlayVideoInfo or -1 if unknown.
                 */
                get_height(): number
                /**
                 * @since 1.20
                 * @returns the maximum bitrate of video in #GstPlayVideoInfo or -1 if unknown.
                 */
                get_max_bitrate(): number
                /**
                 * Returns the pixel aspect ratio in `par_n` and `par_d`
                 * @since 1.20
                 * @returns , numerator, denominator
                 */
                get_pixel_aspect_ratio(): [number, number]
                /**
                 * @since 1.20
                 * @returns the width of video in #GstPlayVideoInfo or -1 if unknown.
                 */
                get_width(): number
            }

            interface PlayVideoInfoClass extends Omit<PlayStreamInfoClass, "new"> {
                readonly $gtype: GObject.GType<PlayVideoInfo>
                readonly prototype: PlayVideoInfo

                new (props?: Partial<GObject.ConstructorProps<PlayVideoInfo>>): PlayVideoInfo
            }

            interface $Exports {
                /**
                 * #GstPlayStreamInfo specific to video streams.
                 * @since 1.20
                 */
                PlayVideoInfo: PlayVideoInfoClass
            }
            

            namespace PlayVideoOverlayVideoRenderer {
                interface SignalSignatures extends GObject.Object.SignalSignatures, PlayVideoRenderer.SignalSignatures {
                }

                interface ReadWriteProperties extends GObject.Object.ReadWriteProperties, PlayVideoRenderer.ReadWriteProperties {
                    "video-sink": Gst.Element
                    "window-handle": never | null
                }

                interface ReadableProperties extends ReadWriteProperties, GObject.Object.ReadableProperties, PlayVideoRenderer.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, GObject.Object.WritableProperties, PlayVideoRenderer.WritableProperties {
                }

                interface ConstructOnlyProperties extends GObject.Object.ConstructOnlyProperties, PlayVideoRenderer.ConstructOnlyProperties {
                }
            }

            interface PlayVideoOverlayVideoRenderer extends GObject.Object, PlayVideoRenderer {
                readonly $signals: PlayVideoOverlayVideoRenderer.SignalSignatures
                readonly $readableProperties: PlayVideoOverlayVideoRenderer.ReadableProperties
                readonly $writableProperties: PlayVideoOverlayVideoRenderer.WritableProperties
                readonly $constructOnlyProperties: PlayVideoOverlayVideoRenderer.ConstructOnlyProperties
                
                get videoSink(): Gst.Element
                set videoSink(value: Gst.Element)
                
                get windowHandle(): never | null
                set windowHandle(value: never | null)
                /**
                 * Tell an overlay that it has been exposed. This will redraw the current frame
                 * in the drawable even if the pipeline is PAUSED.
                 * @since 1.20
                 */
                expose(): void
                /**
                 * Return the currently configured render rectangle. See gst_play_video_overlay_video_renderer_set_render_rectangle()
                 * for details.
                 * @since 1.20
                 * @returns , the horizontal offset of the render area inside the window, the vertical offset of the render area inside the window, the width of the render area inside the window, the height of the render area inside the window
                 */
                get_render_rectangle(): [number, number, number, number]
                /**
                 * @since 1.20
                 * @returns The currently set, platform specific window handle
                 */
                get_window_handle(): never | null
                /**
                 * Configure a subregion as a video target within the window set by
                 * gst_play_video_overlay_video_renderer_set_window_handle(). If this is not
                 * used or not supported the video will fill the area of the window set as the
                 * overlay to 100%. By specifying the rectangle, the video can be overlaid to
                 * a specific region of that window only. After setting the new rectangle one
                 * should call gst_play_video_overlay_video_renderer_expose() to force a
                 * redraw. To unset the region pass -1 for the `width` and `height` parameters.
                 *
                 * This method is needed for non fullscreen video overlay in UI toolkits that
                 * do not support subwindows.
                 * @since 1.20
                 * @param x the horizontal offset of the render area inside the window
                 * @param y the vertical offset of the render area inside the window
                 * @param width the width of the render area inside the window
                 * @param height the height of the render area inside the window
                 */
                set_render_rectangle(x: number, y: number, width: number, height: number): void
                /**
                 * Sets the platform specific window handle into which the video
                 * should be rendered
                 * @since 1.20
                 * @param window_handle handle referencing to the platform specific window
                 */
                set_window_handle(window_handle: never | null): void
            }

            interface PlayVideoOverlayVideoRendererClass extends Omit<GObject.ObjectClass, "new"> {
                readonly $gtype: GObject.GType<PlayVideoOverlayVideoRenderer>
                readonly prototype: PlayVideoOverlayVideoRenderer

                new (props?: Partial<GObject.ConstructorProps<PlayVideoOverlayVideoRenderer>>): PlayVideoOverlayVideoRenderer
                /**
                 * @since 1.20
                 * @param window_handle Window handle to use or %NULL
                 */
                "new"(window_handle: never | null): PlayVideoRenderer
                /**
                 * @since 1.20
                 * @param window_handle Window handle to use or %NULL
                 * @param video_sink the custom video_sink element to be set for the video renderer
                 */
                new_with_sink(window_handle: never | null, video_sink: Gst.Element): PlayVideoRenderer
            }

            interface $Exports {
                /**
                 * @since 1.20
                 */
                PlayVideoOverlayVideoRenderer: PlayVideoOverlayVideoRendererClass
            }
            

            namespace PlayVideoRenderer {
                interface SignalSignatures extends GObject.Object.SignalSignatures {
                }

                interface ReadWriteProperties extends GObject.Object.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, GObject.Object.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, GObject.Object.WritableProperties {
                }

                interface ConstructOnlyProperties extends GObject.Object.ConstructOnlyProperties {
                }

                interface Interface extends GObject.Object {
                }
            }

            interface PlayVideoRenderer extends GObject.Object, PlayVideoRenderer.Interface {
                readonly $signals: PlayVideoRenderer.SignalSignatures
                readonly $readableProperties: PlayVideoRenderer.ReadableProperties
                readonly $writableProperties: PlayVideoRenderer.WritableProperties
                readonly $constructOnlyProperties: PlayVideoRenderer.ConstructOnlyProperties
            }

            interface PlayVideoRendererInterface {
                readonly $gtype: GObject.GType<PlayVideoRenderer>
                readonly prototype: PlayVideoRenderer
                [Symbol.hasInstance](instance: unknown): instance is PlayVideoRenderer
            }

            interface $Exports {
                /**
                 * @since 1.20
                 */
                PlayVideoRenderer: PlayVideoRendererInterface
            }
            

            interface PlayVisualizationStruct {
                readonly $gtype: GObject.GType<PlayVisualization>
                new (fields?: {
                    name?: string
                    description?: string
                }): PlayVisualization
            }

            interface PlayVisualization {
                /**
                 * name of the visualization.
                 */
                name: string
                /**
                 * description of the visualization.
                 */
                description: string
                /**
                 * Makes a copy of the #GstPlayVisualization. The result must be
                 * freed using gst_play_visualization_free().
                 * @since 1.20
                 * @returns an allocated copy of `vis`.
                 */
                copy(): PlayVisualization
                /**
                 * Frees a #GstPlayVisualization.
                 * @since 1.20
                 */
                free(): void
            }

            interface $Exports {
                PlayVisualization: PlayVisualizationStruct
            }
            
            interface PlayColorBalanceTypeEnum {
                readonly $gtype: GObject.GType<PlayColorBalanceType>
                /**
                 * hue or color balance.
                 */
                readonly "HUE": 3
                /**
                 * brightness or black level.
                 */
                readonly "BRIGHTNESS": 0
                /**
                 * color saturation or chroma
                 * gain.
                 */
                readonly "SATURATION": 2
                /**
                 * contrast or luma gain.
                 */
                readonly "CONTRAST": 1
            }
            type PlayColorBalanceType = PlayColorBalanceTypeEnum[Exclude<keyof PlayColorBalanceTypeEnum, "$gtype">]
            interface $Exports {
                /**
                 * @since 1.20
                 */
                PlayColorBalanceType: PlayColorBalanceTypeEnum
                /**
             * Gets a string representing the given color balance type.
             * @since 1.20
             * @param type a #GstPlayColorBalanceType
             * @returns a string with the name of the color   balance type.
             */
            get_name: (type: PlayColorBalanceType) => string
            }
            
            interface PlayError extends GLib.Error {}

            interface PlayErrorEnum {
                readonly $gtype: GObject.GType<PlayError>

                new(props: { message: string, code: number }): PlayError
                /**
                 * generic error.
                 */
                readonly "FAILED": 0
                /**
             * Gets a string representing the given error.
             * @since 1.20
             * @param error a #GstPlayError
             * @returns a string with the given error.
             */
            get_name: (error: PlayError) => string
                /**
             * @since 1.20
             */
            quark: () => GLib.Quark
            }

            interface $Exports {
                /**
                 * @since 1.20
                 */
                PlayError: PlayErrorEnum
            }
            
            interface PlayLoopEnum {
                readonly $gtype: GObject.GType<PlayLoop>
                /**
                 * Don't loop.
                 */
                readonly "NONE": 0
                /**
                 * Loop over the current track.
                 */
                readonly "TRACK": 1
            }
            type PlayLoop = PlayLoopEnum[Exclude<keyof PlayLoopEnum, "$gtype">]
            interface $Exports {
                /**
                 * @since 1.28
                 */
                PlayLoop: PlayLoopEnum
                /**
             * @since 1.28
             * @param loop a #GstPlayLoop
             * @returns a string with the name of the loop.
             */
            get_name: (loop: PlayLoop) => string
            }
            
            interface PlayMessageEnum {
                readonly $gtype: GObject.GType<PlayMessage>
                /**
                 * Source element was initalized for set URI
                 */
                readonly "URI_LOADED": 0
                /**
                 * Sink position changed
                 */
                readonly "POSITION_UPDATED": 1
                /**
                 * Duration of stream changed
                 */
                readonly "DURATION_CHANGED": 2
                /**
                 * State changed, see #GstPlayState
                 */
                readonly "STATE_CHANGED": 3
                /**
                 * Pipeline is in buffering state, message contains the percentage value of the decoding buffer
                 */
                readonly "BUFFERING": 4
                /**
                 * Sink has received EOS
                 */
                readonly "END_OF_STREAM": 5
                /**
                 * Message contains an error
                 */
                readonly "ERROR": 6
                /**
                 * Message contains an error
                 */
                readonly "WARNING": 7
                /**
                 * Video sink received format in different dimensions than before
                 */
                readonly "VIDEO_DIMENSIONS_CHANGED": 8
                /**
                 * A media-info property has changed, message contains current #GstPlayMediaInfo
                 */
                readonly "MEDIA_INFO_UPDATED": 9
                /**
                 * The volume of the audio ouput has changed
                 */
                readonly "VOLUME_CHANGED": 10
                /**
                 * Audio muting flag has been toggled
                 */
                readonly "MUTE_CHANGED": 11
                /**
                 * Any pending seeking operation has been completed
                 */
                readonly "SEEK_DONE": 12
            }
            type PlayMessage = PlayMessageEnum[Exclude<keyof PlayMessageEnum, "$gtype">]
            interface $Exports {
                /**
                 * @since 1.20
                 */
                PlayMessage: PlayMessageEnum
                /**
             * @since 1.20
             * @param message_type a #GstPlayMessage
             * @returns a string with the name of the message.
             */
            get_name: (message_type: PlayMessage) => string
                /**
             * Reads the stream ID the play message `msg` applies to, if any.
             * @since 1.26
             * @param msg A #GstMessage
             * @returns The stream ID this message applies to
             */
            get_stream_id: (msg: Gst.Message) => string | null
                /**
             * Reads the URI the play message `msg` applies to.
             * @since 1.26
             * @param msg A #GstMessage
             * @returns The URI this message applies to
             */
            get_uri: (msg: Gst.Message) => string
                /**
             * Parse the given buffering `msg` and extract the corresponding value
             * @since 1.26
             * @param msg A #GstMessage
             * @returns , the resulting buffering percent
             */
            parse_buffering: (msg: Gst.Message) => number
                /**
             * Parse the given buffering `msg` and extract the corresponding value
             * @since 1.20
             * @deprecated since 1.26 Use gst_play_message_parse_buffering().
             * @param msg A #GstMessage
             * @returns , the resulting buffering percent
             */
            parse_buffering_percent: (msg: Gst.Message) => number
                /**
             * Parse the given duration-changed `msg` and extract the corresponding #GstClockTime
             * @since 1.26
             * @param msg A #GstMessage
             * @returns , the resulting duration
             */
            parse_duration_changed: (msg: Gst.Message) => Gst.ClockTime
                /**
             * Parse the given duration-changed `msg` and extract the corresponding #GstClockTime
             * @since 1.20
             * @deprecated since 1.26 Use gst_play_message_parse_duration_changed().
             * @param msg A #GstMessage
             * @returns , the resulting duration
             */
            parse_duration_updated: (msg: Gst.Message) => Gst.ClockTime
                /**
             * Parse the given error `msg` and extract the corresponding #GError.
             *
             * Since 1.26 the details will always contain the URI this refers to in an
             * "uri" field of type string, and (if known) the string "stream-id" it is
             * referring to.
             * @since 1.20
             * @param msg A #GstMessage
             * @returns , the resulting error, A #GstStructure containing additional details about the error
             */
            parse_error: (msg: Gst.Message) => [GLib.Error, Gst.Structure | null]
                /**
             * Parses missing plugin descriptions and installer details from a
             * GST_PLAY_ERROR_MISSING_PLUGIN error message.
             *
             * Both arrays will have the same length, and strings at the same index
             * correspond to each other.
             *
             * The installer details can be passed to gst_install_plugins_sync() or
             * gst_install_plugins_async().
             * @since 1.26
             * @param msg A #GstMessage
             * @returns %TRUE if the message contained a missing-plugin error., a %NULL-terminated array of descriptions, a %NULL-terminated array of installer details
             */
            parse_error_missing_plugin: (msg: Gst.Message) => [boolean, string[], string[]]
                /**
             * Parse the given media-info-updated `msg` and extract the corresponding media information
             * @since 1.20
             * @param msg A #GstMessage
             * @returns , the resulting media info
             */
            parse_media_info_updated: (msg: Gst.Message) => PlayMediaInfo
                /**
             * Parse the given mute-changed `msg` and extract the corresponding audio muted state
             * @since 1.20
             * @param msg A #GstMessage
             * @returns , the resulting audio muted state
             */
            parse_muted_changed: (msg: Gst.Message) => boolean
                /**
             * Parse the given position-updated `msg` and extract the corresponding #GstClockTime
             * @since 1.20
             * @param msg A #GstMessage
             * @returns , the resulting position
             */
            parse_position_updated: (msg: Gst.Message) => Gst.ClockTime
                /**
             * Parse the given seek-done `msg` and extract the corresponding #GstClockTime
             * @since 1.26
             * @param msg A #GstMessage
             * @returns , the resulting position
             */
            parse_seek_done: (msg: Gst.Message) => Gst.ClockTime
                /**
             * Parse the given state-changed `msg` and extract the corresponding #GstPlayState
             * @since 1.20
             * @param msg A #GstMessage
             * @returns , the resulting play state
             */
            parse_state_changed: (msg: Gst.Message) => PlayState
                /**
             * Parse the given `msg` and extract its #GstPlayMessage type.
             * @since 1.20
             * @param msg A #GstMessage
             * @returns , the resulting message type
             */
            parse_type: (msg: Gst.Message) => PlayMessage
                /**
             * Parse the given uri-loaded `msg` and extract the corresponding value
             * @since 1.26
             * @param msg A #GstMessage
             * @returns , the resulting URI
             */
            parse_uri_loaded: (msg: Gst.Message) => string
                /**
             * Parse the given video-dimensions-changed `msg` and extract the corresponding video dimensions
             * @since 1.20
             * @param msg A #GstMessage
             * @returns , the resulting video width, the resulting video height
             */
            parse_video_dimensions_changed: (msg: Gst.Message) => [number, number]
                /**
             * Parse the given volume-changed `msg` and extract the corresponding audio volume
             * @since 1.20
             * @param msg A #GstMessage
             * @returns , the resulting audio volume
             */
            parse_volume_changed: (msg: Gst.Message) => number
                /**
             * Parse the given warning `msg` and extract the corresponding #GError.
             *
             * Since 1.26 the details will always contain the URI this refers to in an
             * "uri" field of type string, and (if known) the string "stream-id" it is
             * referring to.
             * @since 1.20
             * @param msg A #GstMessage
             * @returns , the resulting warning, A #GstStructure containing additional details about the warning
             */
            parse_warning: (msg: Gst.Message) => [GLib.Error, Gst.Structure | null]
                /**
             * Parses missing plugin descriptions and installer details from a
             * GST_PLAY_ERROR_MISSING_PLUGIN warning message.
             *
             * Both arrays will have the same length, and strings at the same index
             * correspond to each other.
             *
             * The installer details can be passed to gst_install_plugins_sync() or
             * gst_install_plugins_async().
             * @since 1.26
             * @param msg A #GstMessage
             * @returns %TRUE if the message contained a missing-plugin error., a %NULL-terminated array of descriptions, a %NULL-terminated array of installer details
             */
            parse_warning_missing_plugin: (msg: Gst.Message) => [boolean, string[], string[]]
            }
            
            interface PlaySnapshotFormatEnum {
                readonly $gtype: GObject.GType<PlaySnapshotFormat>
                /**
                 * raw native format.
                 */
                readonly "RAW_NATIVE": 0
                /**
                 * raw xRGB format.
                 */
                readonly "RAW_XRGB": 1
                /**
                 * raw BGRx format.
                 */
                readonly "RAW_BGRX": 2
                /**
                 * jpeg format.
                 */
                readonly "JPG": 3
                /**
                 * png format.
                 */
                readonly "PNG": 4
            }
            type PlaySnapshotFormat = PlaySnapshotFormatEnum[Exclude<keyof PlaySnapshotFormatEnum, "$gtype">]
            interface $Exports {
                /**
                 * @since 1.20
                 */
                PlaySnapshotFormat: PlaySnapshotFormatEnum
            }
            
            interface PlayStateEnum {
                readonly $gtype: GObject.GType<PlayState>
                /**
                 * the play is stopped.
                 */
                readonly "STOPPED": 0
                /**
                 * the play is buffering.
                 */
                readonly "BUFFERING": 1
                /**
                 * the play is paused.
                 */
                readonly "PAUSED": 2
                /**
                 * the play is currently playing a
                 * stream.
                 */
                readonly "PLAYING": 3
            }
            type PlayState = PlayStateEnum[Exclude<keyof PlayStateEnum, "$gtype">]
            interface $Exports {
                /**
                 * @since 1.20
                 */
                PlayState: PlayStateEnum
                /**
             * Gets a string representing the given state.
             * @since 1.20
             * @param state a #GstPlayState
             * @returns a string with the name of the state.
             */
            get_name: (state: PlayState) => string
            }

            interface $Exports {
                __name__: "GstPlay"
                __version__: "1.0"
                /**
                 * Gets a string representing the given color balance type.
                 * @since 1.20
                 * @param type a #GstPlayColorBalanceType
                 * @returns a string with the name of the color   balance type.
                 */
                play_color_balance_type_get_name(type: PlayColorBalanceType): string
                /**
                 * Gets a string representing the given error.
                 * @since 1.20
                 * @param error a #GstPlayError
                 * @returns a string with the given error.
                 */
                play_error_get_name(error: PlayError): string
                /**
                 * @since 1.20
                 */
                play_error_quark(): GLib.Quark
                /**
                 * @since 1.28
                 * @param loop a #GstPlayLoop
                 * @returns a string with the name of the loop.
                 */
                play_loop_get_name(loop: PlayLoop): string
                /**
                 * @since 1.20
                 * @param message_type a #GstPlayMessage
                 * @returns a string with the name of the message.
                 */
                play_message_get_name(message_type: PlayMessage): string
                /**
                 * Reads the stream ID the play message `msg` applies to, if any.
                 * @since 1.26
                 * @param msg A #GstMessage
                 * @returns The stream ID this message applies to
                 */
                play_message_get_stream_id(msg: Gst.Message): string | null
                /**
                 * Reads the URI the play message `msg` applies to.
                 * @since 1.26
                 * @param msg A #GstMessage
                 * @returns The URI this message applies to
                 */
                play_message_get_uri(msg: Gst.Message): string
                /**
                 * Parse the given buffering `msg` and extract the corresponding value
                 * @since 1.26
                 * @param msg A #GstMessage
                 * @returns , the resulting buffering percent
                 */
                play_message_parse_buffering(msg: Gst.Message): number
                /**
                 * Parse the given buffering `msg` and extract the corresponding value
                 * @since 1.20
                 * @deprecated since 1.26 Use gst_play_message_parse_buffering().
                 * @param msg A #GstMessage
                 * @returns , the resulting buffering percent
                 */
                play_message_parse_buffering_percent(msg: Gst.Message): number
                /**
                 * Parse the given duration-changed `msg` and extract the corresponding #GstClockTime
                 * @since 1.26
                 * @param msg A #GstMessage
                 * @returns , the resulting duration
                 */
                play_message_parse_duration_changed(msg: Gst.Message): Gst.ClockTime
                /**
                 * Parse the given duration-changed `msg` and extract the corresponding #GstClockTime
                 * @since 1.20
                 * @deprecated since 1.26 Use gst_play_message_parse_duration_changed().
                 * @param msg A #GstMessage
                 * @returns , the resulting duration
                 */
                play_message_parse_duration_updated(msg: Gst.Message): Gst.ClockTime
                /**
                 * Parse the given error `msg` and extract the corresponding #GError.
                 *
                 * Since 1.26 the details will always contain the URI this refers to in an
                 * "uri" field of type string, and (if known) the string "stream-id" it is
                 * referring to.
                 * @since 1.20
                 * @param msg A #GstMessage
                 * @returns , the resulting error, A #GstStructure containing additional details about the error
                 */
                play_message_parse_error(msg: Gst.Message): [GLib.Error, Gst.Structure | null]
                /**
                 * Parses missing plugin descriptions and installer details from a
                 * GST_PLAY_ERROR_MISSING_PLUGIN error message.
                 *
                 * Both arrays will have the same length, and strings at the same index
                 * correspond to each other.
                 *
                 * The installer details can be passed to gst_install_plugins_sync() or
                 * gst_install_plugins_async().
                 * @since 1.26
                 * @param msg A #GstMessage
                 * @returns %TRUE if the message contained a missing-plugin error., a %NULL-terminated array of descriptions, a %NULL-terminated array of installer details
                 */
                play_message_parse_error_missing_plugin(msg: Gst.Message): [boolean, string[], string[]]
                /**
                 * Parse the given media-info-updated `msg` and extract the corresponding media information
                 * @since 1.20
                 * @param msg A #GstMessage
                 * @returns , the resulting media info
                 */
                play_message_parse_media_info_updated(msg: Gst.Message): PlayMediaInfo
                /**
                 * Parse the given mute-changed `msg` and extract the corresponding audio muted state
                 * @since 1.20
                 * @param msg A #GstMessage
                 * @returns , the resulting audio muted state
                 */
                play_message_parse_muted_changed(msg: Gst.Message): boolean
                /**
                 * Parse the given position-updated `msg` and extract the corresponding #GstClockTime
                 * @since 1.20
                 * @param msg A #GstMessage
                 * @returns , the resulting position
                 */
                play_message_parse_position_updated(msg: Gst.Message): Gst.ClockTime
                /**
                 * Parse the given seek-done `msg` and extract the corresponding #GstClockTime
                 * @since 1.26
                 * @param msg A #GstMessage
                 * @returns , the resulting position
                 */
                play_message_parse_seek_done(msg: Gst.Message): Gst.ClockTime
                /**
                 * Parse the given state-changed `msg` and extract the corresponding #GstPlayState
                 * @since 1.20
                 * @param msg A #GstMessage
                 * @returns , the resulting play state
                 */
                play_message_parse_state_changed(msg: Gst.Message): PlayState
                /**
                 * Parse the given `msg` and extract its #GstPlayMessage type.
                 * @since 1.20
                 * @param msg A #GstMessage
                 * @returns , the resulting message type
                 */
                play_message_parse_type(msg: Gst.Message): PlayMessage
                /**
                 * Parse the given uri-loaded `msg` and extract the corresponding value
                 * @since 1.26
                 * @param msg A #GstMessage
                 * @returns , the resulting URI
                 */
                play_message_parse_uri_loaded(msg: Gst.Message): string
                /**
                 * Parse the given video-dimensions-changed `msg` and extract the corresponding video dimensions
                 * @since 1.20
                 * @param msg A #GstMessage
                 * @returns , the resulting video width, the resulting video height
                 */
                play_message_parse_video_dimensions_changed(msg: Gst.Message): [number, number]
                /**
                 * Parse the given volume-changed `msg` and extract the corresponding audio volume
                 * @since 1.20
                 * @param msg A #GstMessage
                 * @returns , the resulting audio volume
                 */
                play_message_parse_volume_changed(msg: Gst.Message): number
                /**
                 * Parse the given warning `msg` and extract the corresponding #GError.
                 *
                 * Since 1.26 the details will always contain the URI this refers to in an
                 * "uri" field of type string, and (if known) the string "stream-id" it is
                 * referring to.
                 * @since 1.20
                 * @param msg A #GstMessage
                 * @returns , the resulting warning, A #GstStructure containing additional details about the warning
                 */
                play_message_parse_warning(msg: Gst.Message): [GLib.Error, Gst.Structure | null]
                /**
                 * Parses missing plugin descriptions and installer details from a
                 * GST_PLAY_ERROR_MISSING_PLUGIN warning message.
                 *
                 * Both arrays will have the same length, and strings at the same index
                 * correspond to each other.
                 *
                 * The installer details can be passed to gst_install_plugins_sync() or
                 * gst_install_plugins_async().
                 * @since 1.26
                 * @param msg A #GstMessage
                 * @returns %TRUE if the message contained a missing-plugin error., a %NULL-terminated array of descriptions, a %NULL-terminated array of installer details
                 */
                play_message_parse_warning_missing_plugin(msg: Gst.Message): [boolean, string[], string[]]
                /**
                 * Gets a string representing the given state.
                 * @since 1.20
                 * @param state a #GstPlayState
                 * @returns a string with the name of the state.
                 */
                play_state_get_name(state: PlayState): string
            }
        }

        const GstPlay: GstPlay.$Exports
    }

    export default GI.GstPlay
}