
/// <reference path="./GLib-2.0.d.ts" />
/// <reference path="./GModule-2.0.d.ts" />
/// <reference path="./GObject-2.0.d.ts" />
/// <reference path="./Gst-1.0.d.ts" />
/// <reference path="./GstBase-1.0.d.ts" />
/// <reference path="./GstVideo-1.0.d.ts" />
/// <reference path="./Vulkan-1.0.d.ts" />
/// <reference path="./GstVulkan-1.0.d.ts" />

/**
 * Type Definitions for GJS (https://gjs.guide/), generated by [GirGen](https://github.com/aylur/girgen)
 * If you found a bug, create a bug report on [GirGen's Repository](https://github.com/aylur/girgen/issues/new)
 */
declare module "gi://GstVulkanWayland?version=1.0" {
    import type GLib from "gi://GLib?version=2.0"
    import type GModule from "gi://GModule?version=2.0"
    import type GObject from "gi://GObject?version=2.0"
    import type Gst from "gi://Gst?version=1.0"
    import type GstBase from "gi://GstBase?version=1.0"
    import type GstVideo from "gi://GstVideo?version=1.0"
    import type Vulkan from "gi://Vulkan?version=1.0"
    import type GstVulkan from "gi://GstVulkan?version=1.0"

    /**
     * Do **not** import this at runtime.
     * This namespace is only exported for module augmentation.
     */
    export namespace GI {
        

        namespace GstVulkanWayland {
            

            namespace VulkanDisplayWayland {
                interface SignalSignatures extends GstVulkan.VulkanDisplay.SignalSignatures {
                }

                interface ReadWriteProperties extends GstVulkan.VulkanDisplay.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, GstVulkan.VulkanDisplay.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, GstVulkan.VulkanDisplay.WritableProperties {
                }

                interface ConstructOnlyProperties extends GstVulkan.VulkanDisplay.ConstructOnlyProperties {
                }
            }

            interface VulkanDisplayWayland extends GstVulkan.VulkanDisplay {
                readonly $signals: VulkanDisplayWayland.SignalSignatures
                readonly $readableProperties: VulkanDisplayWayland.ReadableProperties
                readonly $writableProperties: VulkanDisplayWayland.WritableProperties
                readonly $constructOnlyProperties: VulkanDisplayWayland.ConstructOnlyProperties
            }

            interface VulkanDisplayWaylandClass extends Omit<GstVulkan.VulkanDisplayClass, "new"> {
                readonly $gtype: GObject.GType<VulkanDisplayWayland>
                readonly prototype: VulkanDisplayWayland

                new (props?: Partial<GObject.ConstructorProps<VulkanDisplayWayland>>): VulkanDisplayWayland
                /**
                 * Create a new #GstVulkanDisplayWayland from the wayland display name.  See `wl_display_connect`()
                 * for details on what is a valid name.
                 * @since 1.18
                 * @param name a display name
                 * @returns a new #GstVulkanDisplayWayland or %NULL
                 */
                "new"(name: string | null): VulkanDisplayWayland | null
                /**
                 * Creates a new display connection from a wl_display Display.
                 * @since 1.18
                 * @param display an existing, wayland display
                 * @returns a new #GstVulkanDisplayWayland
                 */
                new_with_display(display: never | null): VulkanDisplayWayland
            }

            interface $Exports {
                /**
                 * the contents of a #GstVulkanDisplayWayland are private and should only be accessed
                 * through the provided API
                 * @since 1.18
                 */
                VulkanDisplayWayland: VulkanDisplayWaylandClass
            }

            interface $Exports {
                __name__: "GstVulkanWayland"
                __version__: "1.0"
            }
        }

        const GstVulkanWayland: GstVulkanWayland.$Exports
    }

    export default GI.GstVulkanWayland
}