
/// <reference path="./GLib-2.0.d.ts" />
/// <reference path="./GModule-2.0.d.ts" />
/// <reference path="./GObject-2.0.d.ts" />
/// <reference path="./freetype2-2.0.d.ts" />
/// <reference path="./Gio-2.0.d.ts" />
/// <reference path="./HarfBuzz-0.0.d.ts" />
/// <reference path="./cairo-1.0.d.ts" />
/// <reference path="./Pango-1.0.d.ts" />
/// <reference path="./fontconfig-2.0.d.ts" />
/// <reference path="./PangoFc-1.0.d.ts" />

/**
 * Type Definitions for GJS (https://gjs.guide/), generated by [GirGen](https://github.com/aylur/girgen)
 * If you found a bug, create a bug report on [GirGen's Repository](https://github.com/aylur/girgen/issues/new)
 */
declare module "gi://PangoOT?version=1.0" {
    import type GLib from "gi://GLib?version=2.0"
    import type GModule from "gi://GModule?version=2.0"
    import type GObject from "gi://GObject?version=2.0"
    import type freetype2 from "gi://freetype2?version=2.0"
    import type Gio from "gi://Gio?version=2.0"
    import type HarfBuzz from "gi://HarfBuzz?version=0.0"
    import type cairo from "gi://cairo?version=1.0"
    import type Pango from "gi://Pango?version=1.0"
    import type fontconfig from "gi://fontconfig?version=2.0"
    import type PangoFc from "gi://PangoFc?version=1.0"

    /**
     * Do **not** import this at runtime.
     * This namespace is only exported for module augmentation.
     */
    export namespace GI {
        

        namespace PangoOT {
            

            namespace Info {
                interface SignalSignatures extends GObject.Object.SignalSignatures {
                }

                interface ReadWriteProperties extends GObject.Object.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, GObject.Object.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, GObject.Object.WritableProperties {
                }

                interface ConstructOnlyProperties extends GObject.Object.ConstructOnlyProperties {
                }
            }

            interface Info extends GObject.Object {
                readonly $signals: Info.SignalSignatures
                readonly $readableProperties: Info.ReadableProperties
                readonly $writableProperties: Info.WritableProperties
                readonly $constructOnlyProperties: Info.ConstructOnlyProperties
                /**
                 * Finds the index of a feature.
                 *
                 * If the feature is not found, sets `feature_index` to PANGO_OT_NO_FEATURE,
                 * which is safe to pass to {@link PangoOT.Ruleset.add_feature} and similar
                 * functions.
                 *
                 * In the future, this may set `feature_index` to an special value that if
                 * used in {@link PangoOT.Ruleset.add_feature} will ask Pango to synthesize
                 * the requested feature based on Unicode properties and data. However, this
                 * function will still return %FALSE in those cases. So, users may want to
                 * ignore the return value of this function in certain cases.
                 * @param table_type the table type to obtain information about
                 * @param feature_tag the tag of the feature to find
                 * @param script_index the index of the script
                 * @param language_index the index of the language whose features are searched,   or %PANGO_OT_DEFAULT_LANGUAGE to use the default language of the script
                 * @returns %TRUE if the feature was found, location to store the index of   the feature
                 */
                find_feature(table_type: TableType, feature_tag: Tag, script_index: number, language_index: number): [boolean, number]
                /**
                 * Finds the index of a language and its required feature index.
                 *
                 * If the language is not found, sets `language_index` to %PANGO_OT_DEFAULT_LANGUAGE
                 * and the required feature of the default language system is returned in
                 * required_feature_index. For best compatibility with some fonts, also
                 * searches the language system tag 'dflt' before falling back to the default
                 * language system, but that is transparent to the user. The user can simply
                 * ignore the return value of this function to automatically fall back to the
                 * default language system.
                 * @param table_type the table type to obtain information about
                 * @param script_index the index of the script whose languages are searched
                 * @param language_tag the tag of the language to find
                 * @returns %TRUE if the language was found, location to store the index of the language, location to store the   required feature index of the language
                 */
                find_language(table_type: TableType, script_index: number, language_tag: Tag): [boolean, number, number]
                /**
                 * Finds the index of a script.
                 *
                 * If not found, tries to find the 'DFLT' and then 'dflt' scripts and
                 * return the index of that in `script_index`. If none of those is found
                 * either, %PANGO_OT_NO_SCRIPT is placed in `script_index`.
                 *
                 * All other functions taking an input script_index parameter know
                 * how to handle %PANGO_OT_NO_SCRIPT, so one can ignore the return
                 * value of this function completely and proceed, to enjoy the automatic
                 * fallback to the 'DFLT'/'dflt' script.
                 * @param table_type the table type to obtain information about
                 * @param script_tag the tag of the script to find
                 * @returns %TRUE if the script was found, location to store the index of the script
                 */
                find_script(table_type: TableType, script_tag: Tag): [boolean, number]
                /**
                 * Obtains the list of features for the given language of the given script.
                 * @param table_type the table type to obtain information about
                 * @param tag unused parameter
                 * @param script_index the index of the script to obtain information about
                 * @param language_index the index of the language to list features for, or   %PANGO_OT_DEFAULT_LANGUAGE, to list features for the default   language of the script
                 * @returns a newly-allocated zero-terminated   array containing the tags of the available features
                 */
                list_features(table_type: TableType, tag: Tag, script_index: number, language_index: number): Tag
                /**
                 * Obtains the list of available languages for a given script.
                 * @param table_type the table type to obtain information about
                 * @param script_index the index of the script to list languages for
                 * @param language_tag unused parameter
                 * @returns a newly-allocated zero-terminated   array containing the tags of the available languages
                 */
                list_languages(table_type: TableType, script_index: number, language_tag: Tag): Tag
                /**
                 * Obtains the list of available scripts.
                 * @param table_type the table type to obtain information about
                 * @returns a newly-allocated zero-terminated   array containing the tags of the available scripts
                 */
                list_scripts(table_type: TableType): Tag
            }

            interface InfoClass extends Omit<GObject.ObjectClass, "new"> {
                readonly $gtype: GObject.GType<Info>
                readonly prototype: Info

                new (props?: Partial<GObject.ConstructorProps<Info>>): Info
                /**
                 * Returns the `PangoOTInfo` structure for the given FreeType font face.
                 * @since 1.2
                 * @param face a `FT_Face`
                 * @returns the `PangoOTInfo` for `face`.   This object will have the same lifetime as `face`.
                 */
                get(face: freetype2.Face): Info
            }

            interface $Exports {
                
                Info: InfoClass
            }
            

            namespace Ruleset {
                interface SignalSignatures extends GObject.Object.SignalSignatures {
                }

                interface ReadWriteProperties extends GObject.Object.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, GObject.Object.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, GObject.Object.WritableProperties {
                }

                interface ConstructOnlyProperties extends GObject.Object.ConstructOnlyProperties {
                }
            }

            interface Ruleset extends GObject.Object {
                readonly $signals: Ruleset.SignalSignatures
                readonly $readableProperties: Ruleset.ReadableProperties
                readonly $writableProperties: Ruleset.WritableProperties
                readonly $constructOnlyProperties: Ruleset.ConstructOnlyProperties
                /**
                 * Adds a feature to the ruleset.
                 * @param table_type the table type to add a feature to
                 * @param feature_index the index of the feature to add
                 * @param property_bit the property bit to use for this feature. Used to   identify the glyphs that this feature should be applied to, or   %PANGO_OT_ALL_GLYPHS if it should be applied to all glyphs.
                 */
                add_feature(table_type: TableType, feature_index: number, property_bit: number): void
                /**
                 * Gets the number of GSUB and GPOS features in the ruleset.
                 * @since 1.18
                 * @returns Total number of features in the `ruleset`, location to store number of GSUB features, location to store number of GPOS features
                 */
                get_feature_count(): [number, number, number]
                /**
                 * This is a convenience function that first tries to find the feature
                 * using {@link PangoOT.Info.find_feature} and the ruleset script and
                 * language passed to {@link PangoOT.Ruleset.new_for} and if the feature
                 * is found, adds it to the ruleset.
                 *
                 * If `ruleset` was not created using {@link PangoOT.Ruleset.new_for},
                 * this function does nothing.
                 * @since 1.18
                 * @param table_type the table type to add a feature to
                 * @param feature_tag the tag of the feature to add
                 * @param property_bit the property bit to use for this feature. Used to   identify the glyphs that this feature should be applied to, or   %PANGO_OT_ALL_GLYPHS if it should be applied to all glyphs.
                 * @returns %TRUE if the feature was found and added to ruleset,   %FALSE otherwise
                 */
                maybe_add_feature(table_type: TableType, feature_tag: Tag, property_bit: number): boolean
                /**
                 * This is a convenience function that for each feature in the feature map
                 * array `features` converts the feature name to a `PangoOTTag` feature tag
                 * using PANGO_OT_TAG_MAKE() and calls {@link PangoOT.Ruleset.maybe_add_feature}
                 * on it.
                 * @since 1.18
                 * @param table_type the table type to add features to
                 * @param features array of feature name and property bits to add
                 * @param n_features number of feature records in `features` array
                 * @returns The number of features in `features` that were found   and added to `ruleset`
                 */
                maybe_add_features(table_type: TableType, features: FeatureMap, n_features: number): number
                /**
                 * Performs the OpenType GPOS positioning on `buffer` using
                 * the features in `ruleset`.
                 * @since 1.4
                 * @param buffer a `PangoOTBuffer`
                 */
                position(buffer: Buffer): void
                /**
                 * Performs the OpenType GSUB substitution on `buffer` using
                 * the features in `ruleset`.
                 * @since 1.4
                 * @param buffer a `PangoOTBuffer`
                 */
                substitute(buffer: Buffer): void
            }

            interface RulesetClass extends Omit<GObject.ObjectClass, "new"> {
                readonly $gtype: GObject.GType<Ruleset>
                readonly prototype: Ruleset

                new (props?: Partial<GObject.ConstructorProps<Ruleset>>): Ruleset
                /**
                 * Creates a new `PangoOTRuleset` for the given OpenType info.
                 * @param info a `PangoOTInfo`
                 * @returns the newly allocated `PangoOTRuleset`
                 */
                "new"(info: Info): Ruleset
                /**
                 * Creates a new `PangoOTRuleset` for the given OpenType info, script, and
                 * language.
                 *
                 * This function is part of a convenience scheme that highly simplifies
                 * using a `PangoOTRuleset` to represent features for a specific pair of script
                 * and language.  So one can use this function passing in the script and
                 * language of interest, and later try to add features to the ruleset by just
                 * specifying the feature name or tag, without having to deal with finding
                 * script, language, or feature indices manually.
                 *
                 * In addition to what {@link PangoOT.Ruleset.new} does, this function will:
                 *
                 * * Find the `PangoOTTag` script and language tags associated with
                 *   `script` and `language` using {@link PangoOT.tag_from_script} and
                 *   {@link PangoOT.tag_from_language},
                 *
                 * * For each of table types %PANGO_OT_TABLE_GSUB and %PANGO_OT_TABLE_GPOS,
                 *   find the script index of the script tag found and the language
                 *   system index of the language tag found in that script system, using
                 *   {@link PangoOT.Info.find_script} and {@link PangoOT.Info.find_language},
                 *
                 * * For found language-systems, if they have required feature index,
                 *   add that feature to the ruleset using {@link PangoOT.Ruleset.add_feature},
                 *
                 * * Remember found script and language indices for both table types,
                 *   and use them in future {@link PangoOT.Ruleset.maybe_add_feature} and
                 *   {@link PangoOT.Ruleset.maybe_add_features}.
                 *
                 * Because of the way return values of {@link PangoOT.Info.find_script} and
                 * {@link PangoOT.Info.find_language} are ignored, this function automatically
                 * finds and uses the 'DFLT' script and the default language-system.
                 * @since 1.18
                 * @param info a `PangoOTInfo`
                 * @param script a `PangoScript`
                 * @param language a `PangoLanguage`
                 * @returns the newly allocated `PangoOTRuleset`
                 */
                new_for(info: Info, script: Pango.Script, language: Pango.Language): Ruleset
                /**
                 * Creates a new `PangoOTRuleset` for the given OpenType info and
                 * matching the given ruleset description.
                 *
                 * This is a convenience function that calls {@link PangoOT.Ruleset.new_for}
                 * and adds the static GSUB/GPOS features to the resulting ruleset,
                 * followed by adding other features to both GSUB and GPOS.
                 *
                 * The static feature map members of `desc` should be alive as
                 * long as `info` is.
                 * @since 1.18
                 * @param info a `PangoOTInfo`
                 * @param desc a `PangoOTRulesetDescription`
                 * @returns the newly allocated `PangoOTRuleset`
                 */
                new_from_description(info: Info, desc: RulesetDescription): Ruleset
                /**
                 * Returns a ruleset for the given OpenType info and ruleset
                 * description.
                 *
                 * Rulesets are created on demand using
                 * {@link PangoOT.Ruleset.new_from_description}.
                 * The returned ruleset should not be modified or destroyed.
                 *
                 * The static feature map members of `desc` should be alive as
                 * long as `info` is.
                 * @since 1.18
                 * @param info a `PangoOTInfo`
                 * @param desc a `PangoOTRulesetDescription`
                 * @returns the `PangoOTRuleset` for `desc`. This object will have   the same lifetime as `info`.
                 */
                get_for_description(info: Info, desc: RulesetDescription): Ruleset
            }

            interface $Exports {
                /**
                 * The `PangoOTRuleset` structure holds a set of features selected
                 * from the tables in an OpenType font.
                 *
                 * A feature is an operation such as adjusting glyph positioning
                 * that should be applied to a text feature such as a certain
                 * type of accent.
                 *
                 * A `PangoOTRuleset` is created with {@link PangoOT.Ruleset.new},
                 * features are added to it with {@link PangoOT.Ruleset.add_feature},
                 * then it is applied to a `PangoGlyphString` with
                 * {@link PangoOT.Ruleset.position}.
                 */
                Ruleset: RulesetClass
            }
            

            interface BufferStruct {
                readonly $gtype: GObject.GType<Buffer>
                /**
                 * Creates a new `PangoOTBuffer` for the given OpenType font.
                 * @since 1.4
                 * @param font a `PangoFcFont`
                 * @returns the newly allocated `PangoOTBuffer`, which should   be freed with {@link PangoOT.Buffer.destroy}.
                 */
                new (font: PangoFc.Font): Buffer
                /**
                 * Creates a new `PangoOTBuffer` for the given OpenType font.
                 * @since 1.4
                 * @param font a `PangoFcFont`
                 * @returns the newly allocated `PangoOTBuffer`, which should   be freed with {@link PangoOT.Buffer.destroy}.
                 */
                "new"(font: PangoFc.Font): Buffer
            }

            interface Buffer {
                /**
                 * Appends a glyph to a `PangoOTBuffer`, with `properties` identifying which
                 * features should be applied on this glyph.
                 *
                 * See {@link PangoOT.Ruleset.add_feature}.
                 * @since 1.4
                 * @param glyph the glyph index to add, like a `PangoGlyph`
                 * @param properties the glyph properties
                 * @param cluster the cluster that this glyph belongs to
                 */
                add_glyph(glyph: number, properties: number, cluster: number): void
                /**
                 * Empties a `PangoOTBuffer`, make it ready to add glyphs to.
                 * @since 1.4
                 */
                clear(): void
                /**
                 * Destroys a `PangoOTBuffer` and free all associated memory.
                 * @since 1.4
                 */
                destroy(): void
                /**
                 * Gets the glyph array contained in a `PangoOTBuffer`.
                 *
                 * The glyphs are owned by the buffer and should not be freed,
                 * and are only valid as long as buffer is not modified.
                 * @since 1.4
                 * @returns , location to   store the array of glyphs
                 */
                get_glyphs(): Glyph[]
                /**
                 * Exports the glyphs in a `PangoOTBuffer` into a `PangoGlyphString`.
                 *
                 * This is typically used after the OpenType layout processing
                 * is over, to convert the resulting glyphs into a generic Pango
                 * glyph string.
                 * @since 1.4
                 * @param glyphs a `PangoGlyphString`
                 */
                output(glyphs: Pango.GlyphString): void
                /**
                 * Sets whether glyphs will be rendered right-to-left.
                 *
                 * This setting is needed for proper horizontal positioning
                 * of right-to-left scripts.
                 * @since 1.4
                 * @param rtl %TRUE for right-to-left text
                 */
                set_rtl(rtl: boolean): void
                /**
                 * Sets whether characters with a mark class should be forced to zero width.
                 *
                 * This setting is needed for proper positioning of Arabic accents,
                 * but will produce incorrect results with standard OpenType Indic
                 * fonts.
                 * @since 1.6
                 * @param zero_width_marks %TRUE if characters with a mark class should   be forced to zero width
                 */
                set_zero_width_marks(zero_width_marks: boolean): void
            }

            interface $Exports {
                Buffer: BufferStruct
            }
            

            interface FeatureMapStruct {
                readonly $gtype: GObject.GType<FeatureMap>
                new (fields?: {
                    feature_name?: number[]
                    property_bit?: number
                }): FeatureMap
            }

            interface FeatureMap {
                /**
                 * feature tag in represented as four-letter ASCII string.
                 */
                feature_name: number[]
                /**
                 * the property bit to use for this feature.  See
                 * pango_ot_ruleset_add_feature() for details.
                 */
                property_bit: number
            }

            interface $Exports {
                FeatureMap: FeatureMapStruct
            }
            

            interface GlyphStruct {
                readonly $gtype: GObject.GType<Glyph>
                new (fields?: {
                    glyph?: number
                    properties?: number
                    cluster?: number
                    component?: number
                    lig_id?: number
                    internal?: number
                }): Glyph
            }

            interface Glyph {
                /**
                 * the glyph itself.
                 */
                glyph: number
                /**
                 * the properties value, identifying which features should be
                 * applied on this glyph.  See pango_ot_ruleset_add_feature().
                 */
                properties: number
                /**
                 * the cluster that this glyph belongs to.
                 */
                cluster: number
                /**
                 * a component value, set by the OpenType layout engine.
                 */
                component: number
                /**
                 * a ligature index value, set by the OpenType layout engine.
                 */
                lig_id: number
                /**
                 * for Pango internal use
                 */
                internal: number
            }

            interface $Exports {
                Glyph: GlyphStruct
            }
            

            interface RulesetDescriptionStruct {
                readonly $gtype: GObject.GType<RulesetDescription>
                new (fields?: {
                    script?: Pango.Script
                    language?: Pango.Language
                    static_gsub_features?: FeatureMap
                    n_static_gsub_features?: number
                    static_gpos_features?: FeatureMap
                    n_static_gpos_features?: number
                    other_features?: FeatureMap
                    n_other_features?: number
                }): RulesetDescription
            }

            interface RulesetDescription {
                /**
                 * a `PangoScript`
                 */
                script: Pango.Script
                /**
                 * a `PangoLanguage`
                 */
                language: Pango.Language
                /**
                 * static map of GSUB features
                 */
                static_gsub_features: FeatureMap
                /**
                 * length of `static_gsub_features`, or 0.
                 */
                n_static_gsub_features: number
                /**
                 * static map of GPOS features
                 */
                static_gpos_features: FeatureMap
                /**
                 * length of `static_gpos_features`, or 0.
                 */
                n_static_gpos_features: number
                /**
                 * map of extra features to add to both
                 *   GSUB and GPOS. Unlike the static maps, this pointer need not
                 *   live beyond the life of function calls taking this struct.
                 */
                other_features: FeatureMap
                /**
                 * length of `other_features`, or 0.
                 */
                n_other_features: number
                /**
                 * Creates a copy of `desc`, which should be freed with
                 * {@link PangoOT.RulesetDescription.free}.
                 *
                 * Primarily used internally by {@link PangoOT.Ruleset.get_for_description}
                 * to cache rulesets for ruleset descriptions.
                 * @since 1.18
                 * @returns the newly allocated `PangoOTRulesetDescription`
                 */
                copy(): RulesetDescription
                /**
                 * Compares two ruleset descriptions for equality.
                 *
                 * Two ruleset descriptions are considered equal if the rulesets
                 * they describe are provably identical. This means that their
                 * script, language, and all feature sets should be equal.
                 *
                 * For static feature sets, the array addresses are compared directly,
                 * while for other features, the list of features is compared one by
                 * one.(Two ruleset descriptions may result in identical rulesets
                 * being created, but still compare %FALSE.)
                 * @since 1.18
                 * @param desc2 a ruleset description
                 * @returns %TRUE if two ruleset descriptions are identical,   %FALSE otherwise
                 */
                equal(desc2: RulesetDescription): boolean
                /**
                 * Frees a ruleset description allocated by
                 * pango_ot_ruleset_description_copy().
                 * @since 1.18
                 */
                free(): void
                /**
                 * Computes a hash of a `PangoOTRulesetDescription` structure suitable
                 * to be used, for example, as an argument to g_hash_table_new().
                 * @since 1.18
                 * @returns the hash value
                 */
                hash(): number
            }

            interface $Exports {
                RulesetDescription: RulesetDescriptionStruct
            }
            
            interface TableTypeEnum {
                readonly $gtype: GObject.GType<TableType>
                /**
                 * The GSUB table.
                 */
                readonly "GSUB": 0
                /**
                 * The GPOS table.
                 */
                readonly "GPOS": 1
            }
            type TableType = TableTypeEnum[Exclude<keyof TableTypeEnum, "$gtype">]
            interface $Exports {
                /**
                 * The PangoOTTableType enumeration values are used to
                 * identify the various OpenType tables in the
                 * pango_ot_info_… functions.
                 */
                TableType: TableTypeEnum
            }
            /**
             * The `PangoOTTag` typedef is used to represent TrueType and OpenType
             * four letter tags inside Pango. Use PANGO_OT_TAG_MAKE()
             * or PANGO_OT_TAG_MAKE_FROM_STRING() macros to create PangoOTTags manually.
             */
            type Tag = number

            interface $Exports {
                __name__: "PangoOT"
                __version__: "1.0"
                ALL_GLYPHS: 65535
                DEFAULT_LANGUAGE: 65535
                NO_FEATURE: 65535
                NO_SCRIPT: 65535
                /**
                 * Finds the OpenType language-system tag best describing `language`.
                 * @since 1.18
                 * @param language A `PangoLanguage`
                 * @returns `PangoOTTag` best matching `language` or %PANGO_OT_TAG_DEFAULT_LANGUAGE if none found or if `language` is %NULL.
                 */
                tag_from_language(language: Pango.Language | null): Tag
                /**
                 * Finds the OpenType script tag corresponding to `script`.
                 *
                 * The %PANGO_SCRIPT_COMMON, %PANGO_SCRIPT_INHERITED, and
                 * %PANGO_SCRIPT_UNKNOWN scripts are mapped to the OpenType
                 * 'DFLT' script tag that is also defined as
                 * %PANGO_OT_TAG_DEFAULT_SCRIPT.
                 *
                 * Note that multiple `PangoScript` values may map to the same
                 * OpenType script tag.  In particular, %PANGO_SCRIPT_HIRAGANA
                 * and %PANGO_SCRIPT_KATAKANA both map to the OT tag 'kana'.
                 * @since 1.18
                 * @param script A `PangoScript`
                 * @returns `PangoOTTag` corresponding to `script` or %PANGO_OT_TAG_DEFAULT_SCRIPT if none found.
                 */
                tag_from_script(script: Pango.Script): Tag
                /**
                 * Finds a `PangoLanguage` corresponding to `language_tag`.
                 * @since 1.18
                 * @param language_tag A `PangoOTTag` OpenType language-system tag
                 * @returns `PangoLanguage` best matching `language_tag` or `PangoLanguage` corresponding to the string "xx" if none found.
                 */
                tag_to_language(language_tag: Tag): Pango.Language
                /**
                 * Finds the `PangoScript` corresponding to `script_tag`.
                 *
                 * The 'DFLT' script tag is mapped to %PANGO_SCRIPT_COMMON.
                 *
                 * Note that an OpenType script tag may correspond to multiple
                 * `PangoScript` values.  In such cases, the `PangoScript` value
                 * with the smallest value is returned.
                 * In particular, %PANGO_SCRIPT_HIRAGANA
                 * and %PANGO_SCRIPT_KATAKANA both map to the OT tag 'kana'.
                 * This function will return %PANGO_SCRIPT_HIRAGANA for
                 * 'kana'.
                 * @since 1.18
                 * @param script_tag A `PangoOTTag` OpenType script tag
                 * @returns `PangoScript` corresponding to `script_tag` or %PANGO_SCRIPT_UNKNOWN if none found.
                 */
                tag_to_script(script_tag: Tag): Pango.Script
            }
        }

        const PangoOT: PangoOT.$Exports
    }

    export default GI.PangoOT
}