
/// <reference path="./GLib-2.0.d.ts" />
/// <reference path="./GModule-2.0.d.ts" />
/// <reference path="./GObject-2.0.d.ts" />
/// <reference path="./freetype2-2.0.d.ts" />
/// <reference path="./Gio-2.0.d.ts" />
/// <reference path="./HarfBuzz-0.0.d.ts" />
/// <reference path="./cairo-1.0.d.ts" />
/// <reference path="./Pango-1.0.d.ts" />
/// <reference path="./fontconfig-2.0.d.ts" />

/**
 * Type Definitions for GJS (https://gjs.guide/), generated by [GirGen](https://github.com/aylur/girgen)
 * If you found a bug, create a bug report on [GirGen's Repository](https://github.com/aylur/girgen/issues/new)
 */
declare module "gi://PangoFc?version=1.0" {
    import type GLib from "gi://GLib?version=2.0"
    import type GModule from "gi://GModule?version=2.0"
    import type GObject from "gi://GObject?version=2.0"
    import type freetype2 from "gi://freetype2?version=2.0"
    import type Gio from "gi://Gio?version=2.0"
    import type HarfBuzz from "gi://HarfBuzz?version=0.0"
    import type cairo from "gi://cairo?version=1.0"
    import type Pango from "gi://Pango?version=1.0"
    import type fontconfig from "gi://fontconfig?version=2.0"

    /**
     * Do **not** import this at runtime.
     * This namespace is only exported for module augmentation.
     */
    export namespace GI {
        

        namespace PangoFc {
            

            namespace Decoder {
                interface SignalSignatures extends GObject.Object.SignalSignatures {
                }

                interface ReadWriteProperties extends GObject.Object.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, GObject.Object.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, GObject.Object.WritableProperties {
                }

                interface ConstructOnlyProperties extends GObject.Object.ConstructOnlyProperties {
                }
            }

            interface Decoder extends GObject.Object {
                readonly $signals: Decoder.SignalSignatures
                readonly $readableProperties: Decoder.ReadableProperties
                readonly $writableProperties: Decoder.WritableProperties
                readonly $constructOnlyProperties: Decoder.ConstructOnlyProperties
                /**
                 * Generates an `FcCharSet` of supported characters for the `fcfont`
                 * given.
                 *
                 * The returned `FcCharSet` will be a reference to an
                 * internal value stored by the `PangoFcDecoder` and must not
                 * be modified or freed.
                 * @since 1.6
                 * @param fcfont the `PangoFcFont` to query.
                 * @returns the `FcCharset` for `fcfont`; must not   be modified or freed.
                 */
                get_charset(fcfont: Font): fontconfig.CharSet
                /**
                 * Generates a `PangoGlyph` for the given Unicode point using the
                 * custom decoder.
                 *
                 * For complex scripts where there can be multiple
                 * glyphs for a single character, the decoder will return whatever
                 * glyph is most convenient for it. (Usually whatever glyph is directly
                 * in the fonts character map table.)
                 * @since 1.6
                 * @param fcfont a `PangoFcFont` to query.
                 * @param wc the Unicode code point to convert to a single `PangoGlyph`.
                 * @returns the glyph index, or 0 if the glyph isn't covered by the font.
                 */
                get_glyph(fcfont: Font, wc: number): Pango.Glyph
                /**
                 * Generates an `FcCharSet` of supported characters for the `fcfont`
                 * given.
                 *
                 * The returned `FcCharSet` will be a reference to an
                 * internal value stored by the `PangoFcDecoder` and must not
                 * be modified or freed.
                 * @since 1.6
                 * @param fcfont the `PangoFcFont` to query.
                 * @returns the `FcCharset` for `fcfont`; must not   be modified or freed.
                 */
                vfunc_get_charset(fcfont: Font): fontconfig.CharSet
                /**
                 * Generates a `PangoGlyph` for the given Unicode point using the
                 * custom decoder.
                 *
                 * For complex scripts where there can be multiple
                 * glyphs for a single character, the decoder will return whatever
                 * glyph is most convenient for it. (Usually whatever glyph is directly
                 * in the fonts character map table.)
                 * @since 1.6
                 * @param fcfont a `PangoFcFont` to query.
                 * @param wc the Unicode code point to convert to a single `PangoGlyph`.
                 * @returns the glyph index, or 0 if the glyph isn't covered by the font.
                 */
                vfunc_get_glyph(fcfont: Font, wc: number): Pango.Glyph
            }

            interface DecoderClass extends Omit<GObject.ObjectClass, "new"> {
                readonly $gtype: GObject.GType<Decoder>
                readonly prototype: Decoder

                new (props?: Partial<GObject.ConstructorProps<Decoder>>): Decoder
            }

            interface $Exports {
                /**
                 * `PangoFcDecoder` is a virtual base class that implementations will
                 * inherit from.
                 *
                 * It's the interface that is used to define a custom encoding for a font.
                 * These objects are created in your code from a function callback that was
                 * originally registered with {@link PangoFc.FontMap.add_decoder_find_func}.
                 * Pango requires information about the supported charset for a font as well
                 * as the individual character to glyph conversions. Pango gets that
                 * information via the #get_charset and #get_glyph callbacks into your
                 * object implementation.
                 * @since 1.6
                 */
                Decoder: DecoderClass
            }
            

            namespace Font {
                interface SignalSignatures extends Pango.Font.SignalSignatures {
                }

                interface ReadWriteProperties extends Pango.Font.ReadWriteProperties {
                    "fontmap": FontMap
                }

                interface ReadableProperties extends ReadWriteProperties, Pango.Font.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, Pango.Font.WritableProperties {
                }

                interface ConstructOnlyProperties extends Pango.Font.ConstructOnlyProperties {
                    "pattern": never
                }
            }

            interface Font extends Pango.Font {
                readonly $signals: Font.SignalSignatures
                readonly $readableProperties: Font.ReadableProperties
                readonly $writableProperties: Font.WritableProperties
                readonly $constructOnlyProperties: Font.ConstructOnlyProperties
                /**
                 * The PangoFc font map this font is associated with.
                 */
                get fontmap(): FontMap
                set fontmap(value: FontMap)
                /**
                 * The fontconfig pattern for this font.
                 */
                get pattern(): never
                set pattern(value: never)
                /**
                 * Gets the glyph index for a given Unicode character
                 * for `font`.
                 *
                 * If you only want to determine whether the font has
                 * the glyph, use {@link PangoFc.Font.has_char}.
                 * @since 1.4
                 * @param wc Unicode character to look up
                 * @returns the glyph index, or 0, if the Unicode   character doesn't exist in the font.
                 */
                get_glyph(wc: string): number
                /**
                 * Returns the languages that are supported by `font`.
                 *
                 * This corresponds to the FC_LANG member of the FcPattern.
                 *
                 * The returned array is only valid as long as the font
                 * and its fontmap are valid.
                 * @since 1.48
                 * @deprecated since 1.50 Use pango_font_get_language()
                 * @returns a   %NULL-terminated array of `PangoLanguage`*
                 */
                get_languages(): Pango.Language[] | null
                /**
                 * Returns the index of a glyph suitable for drawing `wc`
                 * as an unknown character.
                 *
                 * Use PANGO_GET_UNKNOWN_GLYPH() instead.
                 * @since 1.4
                 * @param wc the Unicode character for which a glyph is needed.
                 * @returns a glyph index into `font`.
                 */
                get_unknown_glyph(wc: string): Pango.Glyph
                /**
                 * Determines whether `font` has a glyph for the codepoint `wc`.
                 * @since 1.4
                 * @deprecated since 1.44 Use {@link Pango.Font.has_char}
                 * @param wc Unicode codepoint to look up
                 * @returns %TRUE if `font` has the requested codepoint.
                 */
                has_char(wc: string): boolean
                /**
                 * This function used to adjust each adjacent pair of glyphs
                 * in `glyphs` according to kerning information in `font`.
                 *
                 * Since 1.44, it does nothing.
                 * @since 1.4
                 * @deprecated since 1.32
                 * @param glyphs a `PangoGlyphString`
                 */
                kern_glyphs(glyphs: Pango.GlyphString): void
                /**
                 * Releases a font previously obtained with
                 * {@link PangoFc.Font.lock_face}.
                 * @since 1.4
                 * @deprecated since 1.44 Use pango_font_get_hb_font() instead
                 */
                unlock_face(): void
            }

            interface FontClass extends Omit<Pango.FontClass, "new"> {
                readonly $gtype: GObject.GType<Font>
                readonly prototype: Font

                new (props?: Partial<GObject.ConstructorProps<Font>>): Font
                /**
                 * Creates a `PangoFontDescription` that matches the specified
                 * Fontconfig pattern as closely as possible.
                 *
                 * Many possible Fontconfig pattern values, such as %FC_RASTERIZER
                 * or %FC_DPI, don't make sense in the context of `PangoFontDescription`,
                 * so will be ignored.
                 * @since 1.4
                 * @param pattern a `FcPattern`
                 * @param include_size if %TRUE, the pattern will include the size from   the `pattern`; otherwise the resulting pattern will be unsized.   (only %FC_SIZE is examined, not %FC_PIXEL_SIZE)
                 * @returns a new `PangoFontDescription`. Free with   pango_font_description_free().
                 */
                description_from_pattern(pattern: fontconfig.Pattern, include_size: boolean): Pango.FontDescription
            }

            interface $Exports {
                /**
                 * `PangoFcFont` is a base class for font implementations
                 * using the Fontconfig and FreeType libraries.
                 *
                 * It is used in onjunction with {@link PangoFc.FontMap}.
                 * When deriving from this class, you need to implement all
                 * of its virtual functions other than shutdown() along with
                 * the get_glyph_extents() virtual function from `PangoFont`.
                 */
                Font: FontClass
            }
            

            namespace FontMap {
                interface SignalSignatures extends Pango.FontMap.SignalSignatures, Gio.ListModel.SignalSignatures {
                }

                interface ReadWriteProperties extends Pango.FontMap.ReadWriteProperties, Gio.ListModel.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, Pango.FontMap.ReadableProperties, Gio.ListModel.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, Pango.FontMap.WritableProperties, Gio.ListModel.WritableProperties {
                }

                interface ConstructOnlyProperties extends Pango.FontMap.ConstructOnlyProperties, Gio.ListModel.ConstructOnlyProperties {
                }
            }

            interface FontMap extends Pango.FontMap, Gio.ListModel {
                readonly $signals: FontMap.SignalSignatures
                readonly $readableProperties: FontMap.ReadableProperties
                readonly $writableProperties: FontMap.WritableProperties
                readonly $constructOnlyProperties: FontMap.ConstructOnlyProperties
                /**
                 * Clear all cached information and fontsets for this font map.
                 *
                 * This should be called whenever there is a change in the
                 * output of the default_substitute() virtual function of the
                 * font map, or if fontconfig has been reinitialized to new
                 * configuration.
                 * @since 1.4
                 */
                cache_clear(): void
                /**
                 * Informs font map that the fontconfig configuration (i.e.,
                 * the `FcConfig` object) used by this font map has changed.
                 *
                 * This currently calls {@link PangoFc.FontMap.cache_clear} which
                 * ensures that list of fonts, etc will be regenerated using the
                 * updated configuration.
                 * @since 1.38
                 */
                config_changed(): void
                /**
                 * Creates a new context for this fontmap.
                 *
                 * This function is intended only for backend implementations deriving
                 * from `PangoFcFontMap`; it is possible that a backend will store
                 * additional information needed for correct operation on the `PangoContext`
                 * after calling this function.
                 * @since 1.4
                 * @deprecated since 1.22 Use pango_font_map_create_context() instead.
                 * @returns a new `PangoContext`
                 */
                create_context(): Pango.Context
                /**
                 * Finds the decoder to use for `pattern`.
                 *
                 * Decoders can be added to a font map using
                 * {@link PangoFc.FontMap.add_decoder_find_func}.
                 * @since 1.26
                 * @param pattern The `FcPattern` to find the decoder for.
                 * @returns a newly created `PangoFcDecoder`   object or %NULL if no decoder is set for `pattern`.
                 */
                find_decoder(pattern: fontconfig.Pattern): Decoder | null
                /**
                 * Sets a function that will be called to do final configuration
                 * substitution on a `FcPattern` before it is used to load
                 * the font.
                 *
                 * This function can be used to do things like set
                 * hinting and antialiasing options.
                 * @since 1.48
                 * @param func function to call to to do final config tweaking on `FcPattern` objects
                 */
                set_default_substitute(func: SubstituteFunc): void
                /**
                 * Clears all cached information for the fontmap and marks
                 * all fonts open for the fontmap as dead.
                 *
                 * See the shutdown() virtual function of `PangoFcFont`.
                 *
                 * This function might be used by a backend when the underlying
                 * windowing system for the font map exits. This function is only
                 * intended to be called only for backend implementations deriving
                 * from `PangoFcFontMap`.
                 * @since 1.4
                 */
                shutdown(): void
                /**
                 * Call this function any time the results of the default
                 * substitution function set with
                 * {@link PangoFc.FontMap.set_default_substitute} change.
                 *
                 * That is, if your substitution function will return different
                 * results for the same input pattern, you must call this function.
                 * @since 1.48
                 */
                substitute_changed(): void
            }

            interface FontMapClass extends Omit<Pango.FontMapClass, "new"> {
                readonly $gtype: GObject.GType<FontMap>
                readonly prototype: FontMap

                new (props?: Partial<GObject.ConstructorProps<FontMap>>): FontMap
            }

            interface $Exports {
                /**
                 * `PangoFcFontMap` is a base class for font map implementations using the
                 * Fontconfig and FreeType libraries.
                 *
                 * It is used in the Xft and FreeType backends shipped with Pango,
                 * but can also be used when creating new backends. Any backend
                 * deriving from this base class will take advantage of the wide
                 * range of shapers implemented using FreeType that come with Pango.
                 */
                FontMap: FontMapClass
            }
            

            interface FontMapPrivateStruct {
                readonly $gtype: GObject.GType<FontMapPrivate>
                [Symbol.hasInstance](instance: unknown): instance is FontMapPrivate
            }

            interface FontMapPrivate {
            }

            interface $Exports {
                FontMapPrivate: FontMapPrivateStruct
            }
            /**
             * Function type for doing final config tweaking on prepared `FcPattern`s.
             * @param pattern the FcPattern to tweak.
             * @param data user data.
             */
            type SubstituteFunc = (pattern: fontconfig.Pattern, data: never | null) => void

            interface $Exports {
                __name__: "PangoFc"
                __version__: "1.0"
                FONT_FEATURES: "fontfeatures"
                FONT_VARIATIONS: "fontvariations"
                GRAVITY: "pangogravity"
                PRGNAME: "prgname"
                VERSION: "pangoversion"
            }
        }

        const PangoFc: PangoFc.$Exports
    }

    export default GI.PangoFc
}