
/// <reference path="./GLib-2.0.d.ts" />
/// <reference path="./GModule-2.0.d.ts" />
/// <reference path="./GObject-2.0.d.ts" />
/// <reference path="./Gio-2.0.d.ts" />
/// <reference path="./freetype2-2.0.d.ts" />
/// <reference path="./HarfBuzz-0.0.d.ts" />
/// <reference path="./cairo-1.0.d.ts" />
/// <reference path="./Pango-1.0.d.ts" />
/// <reference path="./GdkPixbuf-2.0.d.ts" />
/// <reference path="./PangoCairo-1.0.d.ts" />
/// <reference path="./Gdk-4.0.d.ts" />
/// <reference path="./Graphene-1.0.d.ts" />
/// <reference path="./Gsk-4.0.d.ts" />
/// <reference path="./Gtk-4.0.d.ts" />
/// <reference path="./JavaScriptCore-6.0.d.ts" />
/// <reference path="./Soup-3.0.d.ts" />

/**
 * Type Definitions for GJS (https://gjs.guide/), generated by [GirGen](https://github.com/aylur/girgen)
 * If you found a bug, create a bug report on [GirGen's Repository](https://github.com/aylur/girgen/issues/new)
 */
declare module "gi://WebKitWebProcessExtension?version=6.0" {
    import type GLib from "gi://GLib?version=2.0"
    import type GModule from "gi://GModule?version=2.0"
    import type GObject from "gi://GObject?version=2.0"
    import type Gio from "gi://Gio?version=2.0"
    import type freetype2 from "gi://freetype2?version=2.0"
    import type HarfBuzz from "gi://HarfBuzz?version=0.0"
    import type cairo from "gi://cairo?version=1.0"
    import type Pango from "gi://Pango?version=1.0"
    import type GdkPixbuf from "gi://GdkPixbuf?version=2.0"
    import type PangoCairo from "gi://PangoCairo?version=1.0"
    import type Gdk from "gi://Gdk?version=4.0"
    import type Graphene from "gi://Graphene?version=1.0"
    import type Gsk from "gi://Gsk?version=4.0"
    import type Gtk from "gi://Gtk?version=4.0"
    import type JavaScriptCore from "gi://JavaScriptCore?version=6.0"
    import type Soup from "gi://Soup?version=3.0"

    /**
     * Do **not** import this at runtime.
     * This namespace is only exported for module augmentation.
     */
    export namespace GI {
        

        namespace WebKitWebProcessExtension {
            

            namespace ContextMenu {
                interface SignalSignatures extends GObject.Object.SignalSignatures {
                }

                interface ReadWriteProperties extends GObject.Object.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, GObject.Object.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, GObject.Object.WritableProperties {
                }

                interface ConstructOnlyProperties extends GObject.Object.ConstructOnlyProperties {
                }
            }

            interface ContextMenu extends GObject.Object {
                readonly $signals: ContextMenu.SignalSignatures
                readonly $readableProperties: ContextMenu.ReadableProperties
                readonly $writableProperties: ContextMenu.WritableProperties
                readonly $constructOnlyProperties: ContextMenu.ConstructOnlyProperties
                /**
                 * Adds `item` at the end of the `menu`.
                 * @param item the #WebKitContextMenuItem to add
                 */
                append(item: ContextMenuItem): void
                /**
                 * Gets the first item in the `menu`.
                 * @returns the first #WebKitContextMenuItem of `menu`,    or %NULL if the #WebKitContextMenu is empty.
                 */
                first(): ContextMenuItem
                /**
                 * Gets the #GdkEvent that triggered the context menu. This function only returns a valid
                 * #GdkEvent when called for a #WebKitContextMenu passed to #WebKitWebView::context-menu
                 * signal; in all other cases, %NULL is returned.
                 *
                 * The returned #GdkEvent is expected to be one of the following types:
                 * <itemizedlist>
                 * <listitem><para>
                 * a #GdkEventButton of type %GDK_BUTTON_PRESS when the context menu was triggered with mouse.
                 * </para></listitem>
                 * <listitem><para>
                 * a #GdkEventKey of type %GDK_KEY_PRESS if the keyboard was used to show the menu.
                 * </para></listitem>
                 * <listitem><para>
                 * a generic #GdkEvent of type %GDK_NOTHING when the #GtkWidget::popup-menu signal was used to show the context menu.
                 * </para></listitem>
                 * </itemizedlist>
                 * @since 2.40
                 * @returns the menu event or %NULL.
                 */
                get_event(): Gdk.Event
                /**
                 * Gets the item at the given position in the `menu`.
                 * @param position the position of the item, counting from 0
                 * @returns the #WebKitContextMenuItem at position `position` in `menu`,    or %NULL if the position is off the end of the `menu`.
                 */
                get_item_at_position(position: number): ContextMenuItem
                /**
                 * Returns the item list of `menu`.
                 * @returns a #GList of    #WebKitContextMenuItem<!-- -->s
                 */
                get_items(): ContextMenuItem[]
                /**
                 * Gets the length of the `menu`.
                 * @returns the number of #WebKitContextMenuItem<!-- -->s in `menu`
                 */
                get_n_items(): number
                /**
                 * Gets the position in view coordinates where the context menu was triggered.
                 *
                 * This function only returns valid coordinates when called for a #WebKitContextMenu
                 * passed to #WebKitWebView::context-menu signal.
                 * @since 2.52
                 * @returns %TRUE if valid position coordinates are available, %FALSE otherwise, return location for the x coordinate, return location for the y coordinate
                 */
                get_position(): [boolean, number, number]
                /**
                 * Gets the user data of `menu`.
                 *
                 * This function can be used from the UI Process to get user data previously set
                 * from the Web Process with webkit_context_menu_set_user_data().
                 * @since 2.8
                 * @returns the user data of `menu`, or %NULL if `menu` doesn't have user data
                 */
                get_user_data(): GLib.Variant
                /**
                 * Inserts `item` into the `menu` at the given position.
                 *
                 * If `position` is negative, or is larger than the number of items
                 * in the #WebKitContextMenu, the item is added on to the end of
                 * the `menu`. The first position is 0.
                 * @param item the #WebKitContextMenuItem to add
                 * @param position the position to insert the item
                 */
                insert(item: ContextMenuItem, position: number): void
                /**
                 * Gets the last item in the `menu`.
                 * @returns the last #WebKitContextMenuItem of `menu`,    or %NULL if the #WebKitContextMenu is empty.
                 */
                last(): ContextMenuItem
                /**
                 * Moves `item` to the given position in the `menu`.
                 *
                 * If `position` is negative, or is larger than the number of items
                 * in the #WebKitContextMenu, the item is added on to the end of
                 * the `menu`.
                 * The first position is 0.
                 * @param item the #WebKitContextMenuItem to add
                 * @param position the new position to move the item
                 */
                move_item(item: ContextMenuItem, position: number): void
                /**
                 * Adds `item` at the beginning of the `menu`.
                 * @param item the #WebKitContextMenuItem to add
                 */
                prepend(item: ContextMenuItem): void
                /**
                 * Removes `item` from the `menu`.
                 *
                 * See also webkit_context_menu_remove_all() to remove all items.
                 * @param item the #WebKitContextMenuItem to remove
                 */
                remove(item: ContextMenuItem): void
                /**
                 * Removes all items of the `menu`.
                 */
                remove_all(): void
                /**
                 * Sets user data to `menu`.
                 *
                 * This function can be used from a Web Process extension to set user data
                 * that can be retrieved from the UI Process using webkit_context_menu_get_user_data().
                 * If the `user_data` #GVariant is floating, it is consumed.
                 * @since 2.8
                 * @param user_data a #GVariant
                 */
                set_user_data(user_data: GLib.Variant): void
            }

            interface ContextMenuClass extends Omit<GObject.ObjectClass, "new"> {
                readonly $gtype: GObject.GType<ContextMenu>
                readonly prototype: ContextMenu

                new (props?: Partial<GObject.ConstructorProps<ContextMenu>>): ContextMenu
                /**
                 * Creates a new #WebKitContextMenu object.
                 *
                 * Creates a new #WebKitContextMenu object to be used as a submenu of an existing
                 * #WebKitContextMenu. The context menu of a #WebKitWebView is created by the view
                 * and passed as an argument of #WebKitWebView::context-menu signal.
                 * To add items to the menu use webkit_context_menu_prepend(),
                 * webkit_context_menu_append() or webkit_context_menu_insert().
                 * See also webkit_context_menu_new_with_items() to create a #WebKitContextMenu with
                 * a list of initial items.
                 * @returns The newly created #WebKitContextMenu object
                 */
                "new"(): ContextMenu
                /**
                 * Creates a new #WebKitContextMenu object with the given items.
                 *
                 * Creates a new #WebKitContextMenu object to be used as a submenu of an existing
                 * #WebKitContextMenu with the given initial items.
                 * See also webkit_context_menu_new()
                 * @param items a #GList of #WebKitContextMenuItem
                 * @returns The newly created #WebKitContextMenu object
                 */
                new_with_items(items: ContextMenuItem[]): ContextMenu
            }

            interface $Exports {
                /**
                 * Represents the context menu in a #WebKitWebView.
                 *
                 * #WebKitContextMenu represents a context menu containing
                 * #WebKitContextMenuItem<!-- -->s in a #WebKitWebView.
                 *
                 * When a #WebKitWebView is about to display the context menu, it
                 * emits the #WebKitWebView::context-menu signal, which has the
                 * #WebKitContextMenu as an argument. You can modify it, adding new
                 * submenus that you can create with webkit_context_menu_new(), adding
                 * new #WebKitContextMenuItem<!-- -->s with
                 * webkit_context_menu_prepend(), webkit_context_menu_append() or
                 * webkit_context_menu_insert(), maybe after having removed the
                 * existing ones with webkit_context_menu_remove_all().
                 */
                ContextMenu: ContextMenuClass
            }
            

            namespace ContextMenuItem {
                interface SignalSignatures extends GObject.InitiallyUnowned.SignalSignatures {
                }

                interface ReadWriteProperties extends GObject.InitiallyUnowned.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, GObject.InitiallyUnowned.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, GObject.InitiallyUnowned.WritableProperties {
                }

                interface ConstructOnlyProperties extends GObject.InitiallyUnowned.ConstructOnlyProperties {
                }
            }

            interface ContextMenuItem extends GObject.InitiallyUnowned {
                readonly $signals: ContextMenuItem.SignalSignatures
                readonly $readableProperties: ContextMenuItem.ReadableProperties
                readonly $writableProperties: ContextMenuItem.WritableProperties
                readonly $constructOnlyProperties: ContextMenuItem.ConstructOnlyProperties
                /**
                 * Gets the action associated to `item` as a #GAction.
                 * @since 2.18
                 * @returns the #GAction associated to the #WebKitContextMenuItem,    or %NULL if `item` is a separator.
                 */
                get_gaction(): Gio.Action
                /**
                 * Gets the target #GVariant associated with `item`.
                 * @since 2.52
                 * @returns the target #GVariant of the #WebKitContextMenuItem,    or %NULL if `item` was not created with webkit_context_menu_item_new_from_gaction()    or if no target was specified.
                 */
                get_gaction_target(): GLib.Variant | null
                /**
                 * Gets the #WebKitContextMenuAction of `item`.
                 *
                 * If the #WebKitContextMenuItem was not
                 * created for a stock action %WEBKIT_CONTEXT_MENU_ACTION_CUSTOM will be
                 * returned. If the #WebKitContextMenuItem is a separator %WEBKIT_CONTEXT_MENU_ACTION_NO_ACTION
                 * will be returned.
                 * @returns the #WebKitContextMenuAction of `item`
                 */
                get_stock_action(): ContextMenuAction
                /**
                 * Gets the submenu of `item`.
                 * @returns the #WebKitContextMenu representing the submenu of    `item` or %NULL if `item` doesn't have a submenu.
                 */
                get_submenu(): ContextMenu
                /**
                 * Gets the title of `item`.
                 * @since 2.52
                 * @returns the title of `item`, or %NULL if `item` is a separator.
                 */
                get_title(): string
                /**
                 * Checks whether `item` is a separator.
                 * @returns %TRUE is `item` is a separator or %FALSE otherwise
                 */
                is_separator(): boolean
                /**
                 * Sets or replaces the `item` submenu.
                 *
                 * If `submenu` is %NULL the current
                 * submenu of `item` is removed.
                 * @param submenu a #WebKitContextMenu
                 */
                set_submenu(submenu: ContextMenu | null): void
            }

            interface ContextMenuItemClass extends Omit<GObject.InitiallyUnownedClass, "new"> {
                readonly $gtype: GObject.GType<ContextMenuItem>
                readonly prototype: ContextMenuItem

                new (props?: Partial<GObject.ConstructorProps<ContextMenuItem>>): ContextMenuItem
                /**
                 * Creates a new #WebKitContextMenuItem for the given `action` and `label`.
                 *
                 * On activation
                 *  `target` will be passed as parameter to the callback.
                 * @since 2.18
                 * @param action a #GAction
                 * @param label the menu item label text
                 * @param target a #GVariant to use as the action target
                 * @returns the newly created #WebKitContextMenuItem object.
                 */
                new_from_gaction(action: Gio.Action, label: string, target: GLib.Variant | null): ContextMenuItem
                /**
                 * Creates a new #WebKitContextMenuItem for the given stock action.
                 *
                 * Stock actions are handled automatically by WebKit so that, for example,
                 * when a menu item created with a %WEBKIT_CONTEXT_MENU_ACTION_STOP is
                 * activated the action associated will be handled by WebKit and the current
                 * load operation will be stopped. You can get the #GAction of a
                 * #WebKitContextMenuItem created with a #WebKitContextMenuAction with
                 * webkit_context_menu_item_get_gaction() and connect to the #GSimpleAction::activate signal
                 * to be notified when the item is activated, but you can't prevent the associated
                 * action from being performed.
                 * @param action a #WebKitContextMenuAction stock action
                 * @returns the newly created #WebKitContextMenuItem object.
                 */
                new_from_stock_action(action: ContextMenuAction): ContextMenuItem
                /**
                 * Creates a new #WebKitContextMenuItem for the given stock action using the given `label`.
                 *
                 * Stock actions have a predefined label, this method can be used to create a
                 * #WebKitContextMenuItem for a #WebKitContextMenuAction but using a custom label.
                 * @param action a #WebKitContextMenuAction stock action
                 * @param label a custom label text to use instead of the predefined one
                 * @returns the newly created #WebKitContextMenuItem object.
                 */
                new_from_stock_action_with_label(action: ContextMenuAction, label: string): ContextMenuItem
                /**
                 * Creates a new #WebKitContextMenuItem representing a separator.
                 * @returns the newly created #WebKitContextMenuItem object.
                 */
                new_separator(): ContextMenuItem
                /**
                 * Creates a new #WebKitContextMenuItem using the given `label` with a submenu.
                 * @param label the menu item label text
                 * @param submenu a #WebKitContextMenu to set
                 * @returns the newly created #WebKitContextMenuItem object.
                 */
                new_with_submenu(label: string, submenu: ContextMenu): ContextMenuItem
            }

            interface $Exports {
                /**
                 * One item of a #WebKitContextMenu.
                 *
                 * The #WebKitContextMenu is composed of #WebKitContextMenuItem<!--
                 * -->s. These items can be created from a #GtkAction, from a
                 * #WebKitContextMenuAction or from a #WebKitContextMenuAction and a
                 * label. These #WebKitContextMenuAction<!-- -->s denote stock actions
                 * for the items. You can also create separators and submenus.
                 */
                ContextMenuItem: ContextMenuItemClass
            }
            

            namespace Frame {
                interface SignalSignatures extends GObject.Object.SignalSignatures {
                }

                interface ReadWriteProperties extends GObject.Object.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, GObject.Object.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, GObject.Object.WritableProperties {
                }

                interface ConstructOnlyProperties extends GObject.Object.ConstructOnlyProperties {
                }
            }

            interface Frame extends GObject.Object {
                readonly $signals: Frame.SignalSignatures
                readonly $readableProperties: Frame.ReadableProperties
                readonly $writableProperties: Frame.WritableProperties
                readonly $constructOnlyProperties: Frame.ConstructOnlyProperties
                /**
                 * Gets the process-unique identifier of this #WebKitFrame. No other
                 * frame in the same web process will have the same ID; however, frames
                 * in other web processes may.
                 * @since 2.26
                 * @returns the identifier of `frame`
                 */
                get_id(): number
                /**
                 * Get the JavaScript execution context of `frame`. Use this function to bridge
                 * between the WebKit and JavaScriptCore APIs.
                 * @since 2.22
                 * @returns the #JSCContext for the JavaScript execution context of `frame`.
                 */
                get_js_context(): JavaScriptCore.Context
                /**
                 * Get the JavaScript execution context of `frame` for the given #WebKitScriptWorld.
                 * @since 2.22
                 * @param world a #WebKitScriptWorld
                 * @returns the #JSCContext for the JavaScript execution context of `frame` for `world`.
                 */
                get_js_context_for_script_world(world: ScriptWorld): JavaScriptCore.Context
                /**
                 * Gets the current active URI of `frame`.
                 * @since 2.2
                 * @returns the current active URI of `frame` or %NULL if nothing has been    loaded yet.
                 */
                get_uri(): string
                /**
                 * Gets whether `frame` is the main frame of a #WebKitWebPage
                 * @since 2.2
                 * @returns %TRUE if `frame` is a main frame or %FALSE otherwise
                 */
                is_main_frame(): boolean
            }

            interface FrameClass extends Omit<GObject.ObjectClass, "new"> {
                readonly $gtype: GObject.GType<Frame>
                readonly prototype: Frame

                new (props?: Partial<GObject.ConstructorProps<Frame>>): Frame
            }

            interface $Exports {
                /**
                 * A web page frame.
                 *
                 * Each `WebKitWebPage` has at least one main frame, and can have any number
                 * of subframes.
                 * @since 2.26
                 */
                Frame: FrameClass
            }
            

            namespace HitTestResult {
                interface SignalSignatures extends GObject.Object.SignalSignatures {
                }

                interface ReadWriteProperties extends GObject.Object.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, GObject.Object.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, GObject.Object.WritableProperties {
                }

                interface ConstructOnlyProperties extends GObject.Object.ConstructOnlyProperties {
                    "context": number
                    "image-uri": string
                    "link-label": string
                    "link-title": string
                    "link-uri": string
                    "media-uri": string
                }
            }

            interface HitTestResult extends GObject.Object {
                readonly $signals: HitTestResult.SignalSignatures
                readonly $readableProperties: HitTestResult.ReadableProperties
                readonly $writableProperties: HitTestResult.WritableProperties
                readonly $constructOnlyProperties: HitTestResult.ConstructOnlyProperties
                /**
                 * Bitmask of #WebKitHitTestResultContext flags representing
                 * the context of the #WebKitHitTestResult.
                 * @default 0
                 */
                get context(): number
                set context(value: number)
                /**
                 * The URI of the image if flag %WEBKIT_HIT_TEST_RESULT_CONTEXT_IMAGE
                 * is present in #WebKitHitTestResult:context
                 * @default NULL
                 */
                get imageUri(): string
                set imageUri(value: string)
                /**
                 * The label of the link if flag %WEBKIT_HIT_TEST_RESULT_CONTEXT_LINK
                 * is present in #WebKitHitTestResult:context
                 * @default NULL
                 */
                get linkLabel(): string
                set linkLabel(value: string)
                /**
                 * The title of the link if flag %WEBKIT_HIT_TEST_RESULT_CONTEXT_LINK
                 * is present in #WebKitHitTestResult:context
                 * @default NULL
                 */
                get linkTitle(): string
                set linkTitle(value: string)
                /**
                 * The URI of the link if flag %WEBKIT_HIT_TEST_RESULT_CONTEXT_LINK
                 * is present in #WebKitHitTestResult:context
                 * @default NULL
                 */
                get linkUri(): string
                set linkUri(value: string)
                /**
                 * The URI of the media if flag %WEBKIT_HIT_TEST_RESULT_CONTEXT_MEDIA
                 * is present in #WebKitHitTestResult:context
                 * @default NULL
                 */
                get mediaUri(): string
                set mediaUri(value: string)
                /**
                 * Gets whether %WEBKIT_HIT_TEST_RESULT_CONTEXT_EDITABLE flag is present in
                 * #WebKitHitTestResult:context.
                 * @returns %TRUE if there's an editable element at the coordinates of the `hit_test_result`,    or %FALSE otherwise
                 */
                context_is_editable(): boolean
                /**
                 * Gets whether %WEBKIT_HIT_TEST_RESULT_CONTEXT_IMAGE flag is present in
                 * #WebKitHitTestResult:context.
                 * @returns %TRUE if there's an image element in the coordinates of the Hit Test,    or %FALSE otherwise
                 */
                context_is_image(): boolean
                /**
                 * Gets whether %WEBKIT_HIT_TEST_RESULT_CONTEXT_LINK flag is present in
                 * #WebKitHitTestResult:context.
                 * @returns %TRUE if there's a link element in the coordinates of the Hit Test,    or %FALSE otherwise
                 */
                context_is_link(): boolean
                /**
                 * Gets whether %WEBKIT_HIT_TEST_RESULT_CONTEXT_MEDIA flag is present in
                 * #WebKitHitTestResult:context.
                 * @returns %TRUE if there's a media element in the coordinates of the Hit Test,    or %FALSE otherwise
                 */
                context_is_media(): boolean
                /**
                 * Gets whether %WEBKIT_HIT_TEST_RESULT_CONTEXT_SCROLLBAR flag is present in
                 * #WebKitHitTestResult:context.
                 * @returns %TRUE if there's a scrollbar element at the coordinates of the `hit_test_result`,    or %FALSE otherwise
                 */
                context_is_scrollbar(): boolean
                /**
                 * Gets whether %WEBKIT_HIT_TEST_RESULT_CONTEXT_SELECTION flag is present in
                 * #WebKitHitTestResult:context.
                 * @since 2.8
                 * @returns %TRUE if there's a selected element at the coordinates of the `hit_test_result`,    or %FALSE otherwise
                 */
                context_is_selection(): boolean
                /**
                 * Gets the value of the #WebKitHitTestResult:context property.
                 * @returns a bitmask of #WebKitHitTestResultContext flags
                 */
                get_context(): number
                /**
                 * Gets the value of the #WebKitHitTestResult:image-uri property.
                 * @returns the URI of the image element in the coordinates of the Hit Test,    or %NULL if there isn't an image element in `hit_test_result` context
                 */
                get_image_uri(): string
                /**
                 * Gets the value of the #WebKitHitTestResult:link-label property.
                 * @returns the label of the link element in the coordinates of the Hit Test,    or %NULL if there isn't a link element in `hit_test_result` context or the    link element doesn't have a label
                 */
                get_link_label(): string
                /**
                 * Gets the value of the #WebKitHitTestResult:link-title property.
                 * @returns the title of the link element in the coordinates of the Hit Test,    or %NULL if there isn't a link element in `hit_test_result` context or the    link element doesn't have a title
                 */
                get_link_title(): string
                /**
                 * Gets the value of the #WebKitHitTestResult:link-uri property.
                 * @returns the URI of the link element in the coordinates of the Hit Test,    or %NULL if there isn't a link element in `hit_test_result` context
                 */
                get_link_uri(): string
                /**
                 * Gets the value of the #WebKitHitTestResult:media-uri property.
                 * @returns the URI of the media element in the coordinates of the Hit Test,    or %NULL if there isn't a media element in `hit_test_result` context
                 */
                get_media_uri(): string
            }

            interface HitTestResultClass extends Omit<GObject.ObjectClass, "new"> {
                readonly $gtype: GObject.GType<HitTestResult>
                readonly prototype: HitTestResult

                new (props?: Partial<GObject.ConstructorProps<HitTestResult>>): HitTestResult
            }

            interface $Exports {
                /**
                 * Result of a Hit Test.
                 *
                 * A Hit Test is an operation to get context information about a given
                 * point in a #WebKitWebView. #WebKitHitTestResult represents the
                 * result of a Hit Test. It provides context information about what is
                 * at the coordinates of the Hit Test, such as if there's a link,
                 * an image or a media.
                 *
                 * You can get the context of the HitTestResult with
                 * webkit_hit_test_result_get_context() that returns a bitmask of
                 * #WebKitHitTestResultContext flags. You can also use
                 * webkit_hit_test_result_context_is_link(), webkit_hit_test_result_context_is_image() and
                 * webkit_hit_test_result_context_is_media() to determine whether there's
                 * a link, image or a media element at the coordinates of the Hit Test.
                 * Note that it's possible that several #WebKitHitTestResultContext flags
                 * are active at the same time, for example if there's a link containing an image.
                 *
                 * When the mouse is moved over a #WebKitWebView a Hit Test is performed
                 * for the mouse coordinates and #WebKitWebView::mouse-target-changed
                 * signal is emitted with a #WebKitHitTestResult.
                 */
                HitTestResult: HitTestResultClass
            }
            

            namespace ScriptWorld {
                interface SignalSignatures extends GObject.Object.SignalSignatures {
                    /**
                     * Emitted when the JavaScript window object in a #WebKitScriptWorld has been
                     * cleared. This is the preferred place to set custom properties on the window
                     * object using the JavaScriptCore API. You can get the window object of `frame`
                     * from the JavaScript execution context of `world` that is returned by
                     * webkit_frame_get_js_context_for_script_world().
                     * @since 2.2
                     * @param page a #WebKitWebPage
                     * @param frame the #WebKitFrame  to which `world` belongs
                     */
                    "window-object-cleared"(page: WebPage, frame: Frame): void
                }

                interface ReadWriteProperties extends GObject.Object.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, GObject.Object.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, GObject.Object.WritableProperties {
                }

                interface ConstructOnlyProperties extends GObject.Object.ConstructOnlyProperties {
                }
            }

            interface ScriptWorld extends GObject.Object {
                readonly $signals: ScriptWorld.SignalSignatures
                readonly $readableProperties: ScriptWorld.ReadableProperties
                readonly $writableProperties: ScriptWorld.WritableProperties
                readonly $constructOnlyProperties: ScriptWorld.ConstructOnlyProperties
                /**
                 * Get the name of a #WebKitScriptWorld.
                 * @since 2.22
                 * @returns the name of `world`
                 */
                get_name(): string
            }

            interface ScriptWorldClass extends Omit<GObject.ObjectClass, "new"> {
                readonly $gtype: GObject.GType<ScriptWorld>
                readonly prototype: ScriptWorld

                new (props?: Partial<GObject.ConstructorProps<ScriptWorld>>): ScriptWorld
                /**
                 * Creates a new isolated #WebKitScriptWorld. Scripts executed in
                 * isolated worlds have access to the DOM but not to other variable
                 * or functions created by the page.
                 * The #WebKitScriptWorld is created with a generated unique name. Use
                 * webkit_script_world_new_with_name() if you want to create it with a
                 * custom name.
                 * You can get the JavaScript execution context of a #WebKitScriptWorld
                 * for a given #WebKitFrame with webkit_frame_get_javascript_context_for_script_world().
                 * @since 2.2
                 * @returns a new isolated #WebKitScriptWorld
                 */
                "new"(): ScriptWorld
                /**
                 * Creates a new isolated #WebKitScriptWorld with a name. Scripts executed in
                 * isolated worlds have access to the DOM but not to other variable
                 * or functions created by the page.
                 * You can get the JavaScript execution context of a #WebKitScriptWorld
                 * for a given #WebKitFrame with webkit_frame_get_javascript_context_for_script_world().
                 * @since 2.22
                 * @param name a name for the script world
                 * @returns a new isolated #WebKitScriptWorld
                 */
                new_with_name(name: string): ScriptWorld
                /**
                 * Get the default #WebKitScriptWorld. This is the normal script world
                 * where all scripts are executed by default.
                 * You can get the JavaScript execution context of a #WebKitScriptWorld
                 * for a given #WebKitFrame with webkit_frame_get_javascript_context_for_script_world().
                 * @since 2.2
                 * @returns the default #WebKitScriptWorld
                 */
                get_default(): ScriptWorld
            }

            interface $Exports {
                
                ScriptWorld: ScriptWorldClass
            }
            

            namespace URIRequest {
                interface SignalSignatures extends GObject.Object.SignalSignatures {
                }

                interface ReadWriteProperties extends GObject.Object.ReadWriteProperties {
                    "uri": string
                }

                interface ReadableProperties extends ReadWriteProperties, GObject.Object.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, GObject.Object.WritableProperties {
                }

                interface ConstructOnlyProperties extends GObject.Object.ConstructOnlyProperties {
                }
            }

            interface URIRequest extends GObject.Object {
                readonly $signals: URIRequest.SignalSignatures
                readonly $readableProperties: URIRequest.ReadableProperties
                readonly $writableProperties: URIRequest.WritableProperties
                readonly $constructOnlyProperties: URIRequest.ConstructOnlyProperties
                /**
                 * The URI to which the request will be made.
                 * @default about:blank
                 */
                get uri(): string
                set uri(value: string)
                /**
                 * Get the HTTP headers of a #WebKitURIRequest as a #SoupMessageHeaders.
                 * @returns a #SoupMessageHeaders with the HTTP headers of `request`    or %NULL if `request` is not an HTTP request.
                 */
                get_http_headers(): Soup.MessageHeaders
                /**
                 * Get the HTTP method of the #WebKitURIRequest.
                 * @since 2.12
                 * @returns the HTTP method of the #WebKitURIRequest or %NULL if `request` is not    an HTTP request.
                 */
                get_http_method(): string
                /**
                 * Obtains the request URI.
                 * @returns request URI, as a string.
                 */
                get_uri(): string
                /**
                 * Set the URI of `request`
                 * @param uri an URI
                 */
                set_uri(uri: string): void
            }

            interface URIRequestClass extends Omit<GObject.ObjectClass, "new"> {
                readonly $gtype: GObject.GType<URIRequest>
                readonly prototype: URIRequest

                new (props?: Partial<GObject.ConstructorProps<URIRequest>>): URIRequest
                /**
                 * Creates a new #WebKitURIRequest for the given URI.
                 * @param uri an URI
                 * @returns a new #WebKitURIRequest
                 */
                "new"(uri: string): URIRequest
            }

            interface $Exports {
                /**
                 * Represents a URI request.
                 *
                 * A #WebKitURIRequest can be created with a URI using the
                 * webkit_uri_request_new() method, and you can get the URI of an
                 * existing request with the webkit_uri_request_get_uri() one.
                 */
                URIRequest: URIRequestClass
            }
            

            namespace URIResponse {
                interface SignalSignatures extends GObject.Object.SignalSignatures {
                }

                interface ReadWriteProperties extends GObject.Object.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, GObject.Object.ReadableProperties {
                    "content-length": number
                    "http-headers": Soup.MessageHeaders
                    "mime-type": string
                    "status-code": number
                    "suggested-filename": string
                    "uri": string
                }

                interface WritableProperties extends ReadWriteProperties, GObject.Object.WritableProperties {
                }

                interface ConstructOnlyProperties extends GObject.Object.ConstructOnlyProperties {
                }
            }

            interface URIResponse extends GObject.Object {
                readonly $signals: URIResponse.SignalSignatures
                readonly $readableProperties: URIResponse.ReadableProperties
                readonly $writableProperties: URIResponse.WritableProperties
                readonly $constructOnlyProperties: URIResponse.ConstructOnlyProperties
                /**
                 * The expected content length of the response.
                 * @default 0
                 */
                get contentLength(): number
                /**
                 * The HTTP headers of the response, or %NULL if the response is not an HTTP response.
                 * @since 2.6
                 */
                get httpHeaders(): Soup.MessageHeaders
                /**
                 * The MIME type of the response.
                 * @default NULL
                 */
                get mimeType(): string
                /**
                 * The status code of the response as returned by the server.
                 * @default 0
                 */
                get statusCode(): number
                /**
                 * The suggested filename for the URI response.
                 * @default NULL
                 */
                get suggestedFilename(): string
                /**
                 * The URI for which the response was made.
                 * @default NULL
                 */
                get uri(): string
                /**
                 * Get the expected content length of the #WebKitURIResponse.
                 *
                 * It can be 0 if the server provided an incorrect or missing Content-Length.
                 * @returns the expected content length of `response`.
                 */
                get_content_length(): number
                /**
                 * Get the HTTP headers of a #WebKitURIResponse as a #SoupMessageHeaders.
                 * @since 2.6
                 * @returns a #SoupMessageHeaders with the HTTP headers of `response`    or %NULL if `response` is not an HTTP response.
                 */
                get_http_headers(): Soup.MessageHeaders
                /**
                 * Gets the MIME type of the response.
                 * @returns MIME type, as a string.
                 */
                get_mime_type(): string
                /**
                 * Get the status code of the #WebKitURIResponse.
                 *
                 * Get the status code of the #WebKitURIResponse as returned by
                 * the server. It will normally be a #SoupKnownStatusCode, for
                 * example %SOUP_STATUS_OK, though the server can respond with any
                 * unsigned integer.
                 * @returns the status code of `response`
                 */
                get_status_code(): number
                /**
                 * Get the suggested filename for `response`.
                 *
                 * Get the suggested filename for `response`, as specified by
                 * the 'Content-Disposition' HTTP header, or %NULL if it's not
                 * present.
                 * @returns the suggested filename or %NULL if    the 'Content-Disposition' HTTP header is not present.
                 */
                get_suggested_filename(): string
                /**
                 * Gets the URI which resulted in the response.
                 * @returns response URI, as a string.
                 */
                get_uri(): string
            }

            interface URIResponseClass extends Omit<GObject.ObjectClass, "new"> {
                readonly $gtype: GObject.GType<URIResponse>
                readonly prototype: URIResponse

                new (props?: Partial<GObject.ConstructorProps<URIResponse>>): URIResponse
            }

            interface $Exports {
                /**
                 * Represents an URI response.
                 *
                 * A #WebKitURIResponse contains information such as the URI, the
                 * status code, the content length, the mime type, the HTTP status or
                 * the suggested filename.
                 */
                URIResponse: URIResponseClass
            }
            

            namespace UserMessage {
                interface SignalSignatures extends GObject.InitiallyUnowned.SignalSignatures {
                }

                interface ReadWriteProperties extends GObject.InitiallyUnowned.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, GObject.InitiallyUnowned.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, GObject.InitiallyUnowned.WritableProperties {
                }

                interface ConstructOnlyProperties extends GObject.InitiallyUnowned.ConstructOnlyProperties {
                    "fd-list": Gio.UnixFDList | null
                    "name": string
                    "parameters": GLib.Variant | null
                }
            }

            interface UserMessage extends GObject.InitiallyUnowned {
                readonly $signals: UserMessage.SignalSignatures
                readonly $readableProperties: UserMessage.ReadableProperties
                readonly $writableProperties: UserMessage.WritableProperties
                readonly $constructOnlyProperties: UserMessage.ConstructOnlyProperties
                /**
                 * The UNIX file descriptors of the user message.
                 * @since 2.28
                 */
                get fdList(): Gio.UnixFDList | null
                set fdList(value: Gio.UnixFDList | null)
                /**
                 * The name of the user message.
                 * @since 2.28
                 * @default NULL
                 */
                get name(): string
                set name(value: string)
                /**
                 * The parameters of the user message as a #GVariant, or %NULL
                 * if the message doesn't include parameters. Note that only complete types are
                 * allowed.
                 * @since 2.28
                 */
                get parameters(): GLib.Variant | null
                set parameters(value: GLib.Variant | null)
                /**
                 * Get the `message` list of file descritpor.
                 * @since 2.28
                 * @returns the message list of file descriptors
                 */
                get_fd_list(): Gio.UnixFDList | null
                /**
                 * Get the `message` name.
                 * @since 2.28
                 * @returns the message name
                 */
                get_name(): string
                /**
                 * Get the `message` parameters.
                 * @since 2.28
                 * @returns the message parameters
                 */
                get_parameters(): GLib.Variant | null
                /**
                 * Send a reply to an user message.
                 *
                 * If `reply` is floating, it's consumed.
                 * You can only send a reply to a #WebKitUserMessage that has been
                 * received.
                 * @since 2.28
                 * @param reply a #WebKitUserMessage to send as reply
                 */
                send_reply(reply: UserMessage): void
            }

            interface UserMessageClass extends Omit<GObject.InitiallyUnownedClass, "new"> {
                readonly $gtype: GObject.GType<UserMessage>
                readonly prototype: UserMessage

                new (props?: Partial<GObject.ConstructorProps<UserMessage>>): UserMessage
                /**
                 * Create a new #WebKitUserMessage with `name`.
                 * @since 2.28
                 * @param name the message name
                 * @param parameters the message parameters as a #GVariant, or %NULL
                 * @returns the newly created #WebKitUserMessage object.
                 */
                "new"(name: string, parameters: GLib.Variant | null): UserMessage
                /**
                 * Create a new #WebKitUserMessage including also a list of UNIX file descriptors to be sent.
                 * @since 2.28
                 * @param name the message name
                 * @param parameters the message parameters as a #GVariant
                 * @param fd_list the message file descriptors
                 * @returns the newly created #WebKitUserMessage object.
                 */
                new_with_fd_list(name: string, parameters: GLib.Variant | null, fd_list: Gio.UnixFDList | null): UserMessage
                /**
                 * Gets the quark for the domain of user message errors.
                 * @returns user message error domain.
                 */
                error_quark(): GLib.Quark
            }

            interface $Exports {
                /**
                 * Message that can be sent between the UI process and web process extensions.
                 *
                 * A WebKitUserMessage is a message that can be used for the communication between the UI process
                 * and web process extensions. A WebKitUserMessage always has a name, and it can also include parameters and
                 * UNIX file descriptors. Messages can be sent from a #WebKitWebContext to all web process extensions,
                 * from a web process extension to its corresponding #WebKitWebContext, and from a #WebKitWebView to its
                 * corresponding #WebKitWebPage (and vice versa). One to one messages can be replied to directly with
                 * webkit_user_message_send_reply().
                 * @since 2.28
                 */
                UserMessage: UserMessageClass
            }
            

            namespace WebEditor {
                interface SignalSignatures extends GObject.Object.SignalSignatures {
                    /**
                     * This signal is emitted for every selection change inside a #WebKitWebPage
                     * as well as for every caret position change as the caret is a collapsed
                     * selection.
                     * @since 2.10
                     */
                    "selection-changed"(): void
                }

                interface ReadWriteProperties extends GObject.Object.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, GObject.Object.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, GObject.Object.WritableProperties {
                }

                interface ConstructOnlyProperties extends GObject.Object.ConstructOnlyProperties {
                }
            }

            interface WebEditor extends GObject.Object {
                readonly $signals: WebEditor.SignalSignatures
                readonly $readableProperties: WebEditor.ReadableProperties
                readonly $writableProperties: WebEditor.WritableProperties
                readonly $constructOnlyProperties: WebEditor.ConstructOnlyProperties
                /**
                 * Gets the #WebKitWebPage that is associated with the #WebKitWebEditor.
                 * @since 2.10
                 * @returns the associated #WebKitWebPage
                 */
                get_page(): WebPage
            }

            interface WebEditorClass extends Omit<GObject.ObjectClass, "new"> {
                readonly $gtype: GObject.GType<WebEditor>
                readonly prototype: WebEditor

                new (props?: Partial<GObject.ConstructorProps<WebEditor>>): WebEditor
            }

            interface $Exports {
                /**
                 * Access to editing capabilities of a #WebKitWebPage.
                 *
                 * The WebKitWebEditor provides access to various editing capabilities of
                 * a #WebKitWebPage such as a possibility to react to the current selection in
                 * #WebKitWebPage.
                 * @since 2.10
                 */
                WebEditor: WebEditorClass
            }
            

            namespace WebFormManager {
                interface SignalSignatures extends GObject.Object.SignalSignatures {
                    /**
                     * Emitted after form elements (or form associated elements) are associated to `frame`.
                     * This is useful to implement form auto filling for web pages where form fields are added
                     * dynamically. This signal might be emitted multiple times for the same frame.
                     *
                     * Note that this signal could be also emitted when form controls are moved between forms. In
                     * that case, the `elements` array carries the list of those elements which have moved.
                     *
                     * Clients should take a reference to the members of the `elements` array if it is desired to
                     * keep them alive after the signal handler returns.
                     * @since 2.40
                     * @param frame a #WebKitFrame
                     * @param elements a #GPtrArray of     #JSCValue with the list of forms in the page
                     */
                    "form-controls-associated"(frame: Frame, elements: JavaScriptCore.Value[]): void
                    /**
                     * This signal is emitted when the DOM submit event is about to be fired for `form`.
                     * JavaScript code may rely on the submit event to detect that the user has clicked
                     * on a submit button, and to possibly cancel the form submission before
                     * #WebKitWebFormManager::will-submit-form signal is emitted.
                     * However, beware that, for historical reasons, the submit event is not emitted at
                     * all if the form submission is triggered by JavaScript. For these reasons,
                     * this signal may not be used to reliably detect whether a form will be submitted.
                     * Instead, use it to detect if a user has clicked on a form's submit button even if
                     * JavaScript later cancels the form submission, or to read the values of the form's
                     * fields even if JavaScript later clears certain fields before submitting. This may
                     * be needed, for example, to implement a robust browser password manager, as some
                     * misguided websites may use such techniques to attempt to thwart password managers.
                     * @since 2.40
                     * @param form the #JSCValue to be submitted, which will always correspond to an HTMLFormElement
                     * @param source_frame the #WebKitFrame containing the form to be submitted
                     * @param target_frame the #WebKitFrame containing the form's target,     which may be the same as `source_frame` if no target was specified
                     */
                    "will-send-submit-event"(form: JavaScriptCore.Value, source_frame: Frame, target_frame: Frame): void
                    /**
                     * This signal is emitted when `form` will imminently be submitted. It can no longer
                     * be cancelled. This event always occurs immediately before a form is submitted to
                     * its target, so use this event to reliably detect when a form is submitted. This
                     * signal is emitted after #WebKitWebFormManager::will-send-submit-event if that
                     * signal is emitted.
                     * @since 2.40
                     * @param form the #JSCValue to be submitted, which will always correspond to an HTMLFormElement
                     * @param source_frame the #WebKitFrame containing the form to be submitted
                     * @param target_frame the #WebKitFrame containing the form's target,     which may be the same as `source_frame` if no target was specified
                     */
                    "will-submit-form"(form: JavaScriptCore.Value, source_frame: Frame, target_frame: Frame): void
                }

                interface ReadWriteProperties extends GObject.Object.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, GObject.Object.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, GObject.Object.WritableProperties {
                }

                interface ConstructOnlyProperties extends GObject.Object.ConstructOnlyProperties {
                }
            }

            interface WebFormManager extends GObject.Object {
                readonly $signals: WebFormManager.SignalSignatures
                readonly $readableProperties: WebFormManager.ReadableProperties
                readonly $writableProperties: WebFormManager.WritableProperties
                readonly $constructOnlyProperties: WebFormManager.ConstructOnlyProperties
            }

            interface WebFormManagerClass extends Omit<GObject.ObjectClass, "new"> {
                readonly $gtype: GObject.GType<WebFormManager>
                readonly prototype: WebFormManager

                new (props?: Partial<GObject.ConstructorProps<WebFormManager>>): WebFormManager
                /**
                 * Set the value of an HTML input element as if it had been edited by
                 * the user, triggering a change event, and set it as filled automatically.
                 * If `element` is not an HTML input element this function does nothing.
                 * @since 2.40
                 * @param element a #JSCValue
                 * @param value the text to set
                 */
                input_element_auto_fill(element: JavaScriptCore.Value, value: string): void
                /**
                 * Get whether `element` is an HTML input element that has been filled automatically.
                 * @since 2.40
                 * @param element a #JSCValue
                 * @returns %TRUE if `element` is an HTML input element that has been filled automatically,    or %FALSE otherwise
                 */
                input_element_is_auto_filled(element: JavaScriptCore.Value): boolean
                /**
                 * Get whether `element` is an HTML text input element that has been edited by a user action.
                 * @since 2.40
                 * @param element a #JSCValue
                 * @returns %TRUE if `element` is an HTML text input element that has been edited by a user action,    or %FALSE otherwise
                 */
                input_element_is_user_edited(element: JavaScriptCore.Value): boolean
            }

            interface $Exports {
                /**
                 * Form manager of a #WebKitWebPage in a #WebKitScriptWorld
                 * @since 2.40
                 */
                WebFormManager: WebFormManagerClass
            }
            

            namespace WebHitTestResult {
                interface SignalSignatures extends GObject.Object.SignalSignatures {
                }

                interface ReadWriteProperties extends GObject.Object.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, GObject.Object.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, GObject.Object.WritableProperties {
                }

                interface ConstructOnlyProperties extends GObject.Object.ConstructOnlyProperties {
                }
            }

            interface WebHitTestResult extends GObject.Object {
                readonly $signals: WebHitTestResult.SignalSignatures
                readonly $readableProperties: WebHitTestResult.ReadableProperties
                readonly $writableProperties: WebHitTestResult.WritableProperties
                readonly $constructOnlyProperties: WebHitTestResult.ConstructOnlyProperties
                /**
                 * Check whether there is an editable element at the hit test position.
                 *
                 * Checks whether %WEBKIT_HIT_TEST_RESULT_CONTEXT_EDITABLE flag is present in
                 * the context flags.
                 * @returns %TRUE if the hit test covers an editable element or %FALSE otherwise.
                 */
                context_is_editable(): boolean
                /**
                 * Check whether there is an image element at the hit test position.
                 *
                 * Checks whether %WEBKIT_HIT_TEST_RESULT_CONTEXT_IMAGE flag is present in
                 * the context flags.
                 * @returns %TRUE if the hit test covers an image element or %FALSE otherwise.
                 */
                context_is_image(): boolean
                /**
                 * Check whether there is a link element at the hit test position.
                 *
                 * Checks whether %WEBKIT_HIT_TEST_RESULT_CONTEXT_LINK flag is present in
                 * the context flags.
                 * @returns %TRUE if the hit test covers a link element or %FALSE otherwise.
                 */
                context_is_link(): boolean
                /**
                 * Check whether there is a media element at the hit test position.
                 *
                 * Checks whether %WEBKIT_HIT_TEST_RESULT_CONTEXT_MEDIA flag is present in
                 * the context flags.
                 * @returns %TRUE if the hit test covers a media element or %FALSE otherwise.
                 */
                context_is_media(): boolean
                /**
                 * Check whether there is a scrollbar at the hit test position.
                 *
                 * Checks whether %WEBKIT_HIT_TEST_RESULT_CONTEXT_SCROLLBAR flag is present in
                 * the context flags.
                 * @returns %TRUE if the hit test covers a scrollbar or %FALSE otherwise.
                 */
                context_is_scrollbar(): boolean
                /**
                 * Check whether there is a selected element at the hit test position.
                 *
                 * Checks whether %WEBKIT_HIT_TEST_RESULT_CONTEXT_SELECTION flag is present in
                 * the context flags.
                 * @returns %TRUE if the hit test covers a selected element or %FALSE otherwise.
                 */
                context_is_selection(): boolean
                /**
                 * Gets the the context flags for the hit test result.
                 * @returns a bitmask of #WebKitHitTestResultContext flags
                 */
                get_context(): number
                /**
                 * Obtains the URI associated with the image element at the hit test position.
                 * @returns the URI of the image element, or %NULL if the hit test does not cover an image element.
                 */
                get_image_uri(): string
                /**
                 * Get the #JSCValue for the DOM node in `world` at the coordinates of the Hit Test.
                 * @since 2.40
                 * @param world a #WebKitScriptWorld, or %NULL to use the default
                 * @returns a #JSCValue for the DOM node, or %NULL
                 */
                get_js_node(world: ScriptWorld | null): JavaScriptCore.Value | null
                /**
                 * Obtains the label associated with the link element at the hit test position.
                 * @returns the label of the link element, or %NULL if the hit test does not cover a link element    or the link element does not have a label.
                 */
                get_link_label(): string
                /**
                 * Obtains the title associated with the link element at the hit test position.
                 * @returns the title of the link element, or %NULL if the hit test does not cover a link element    or the link element does not have a title.
                 */
                get_link_title(): string
                /**
                 * Obtains the URI associated with the link element at the hit test position.
                 * @returns the URI of the link element, or %NULL if the hit test does not cover a link element.
                 */
                get_link_uri(): string
                /**
                 * Obtains the URI associated with the media element at the hit test position.
                 * @returns the URI of the media element, or %NULL if the hit test does not cover a media element.
                 */
                get_media_uri(): string
            }

            interface WebHitTestResultClass extends Omit<GObject.ObjectClass, "new"> {
                readonly $gtype: GObject.GType<WebHitTestResult>
                readonly prototype: WebHitTestResult

                new (props?: Partial<GObject.ConstructorProps<WebHitTestResult>>): WebHitTestResult
            }

            interface $Exports {
                /**
                 * Result of a Hit Test (Web Process Extensions).
                 *
                 * WebKitWebHitTestResult extends #WebKitHitTestResult to provide information
                 * about the #WebKitDOMNode in the coordinates of the Hit Test.
                 * @since 2.8
                 */
                WebHitTestResult: WebHitTestResultClass
            }
            

            namespace WebPage {
                interface SignalSignatures extends GObject.Object.SignalSignatures {
                    /**
                     * Emitted when a message is sent to the console. This can be a message
                     * produced by the use of JavaScript console API, a JavaScript exception,
                     * a security error or other errors, warnings, debug or log messages.
                     * The `console_message` contains information of the message.
                     * @since 2.12
                     * @param console_message the #WebKitConsoleMessage
                     */
                    "console-message-sent"(console_message: ConsoleMessage): void
                    /**
                     * Emitted before a context menu is displayed in the UI Process to
                     * give the application a chance to customize the proposed menu,
                     * build its own context menu or pass user data to the UI Process.
                     * This signal is useful when the information available in the UI Process
                     * is not enough to build or customize the context menu, for example, to
                     * add menu entries depending on the node at the coordinates of the
                     *  `hit_test_result`. Otherwise, it's recommended to use #WebKitWebView::context-menu
                     * signal instead.
                     * @since 2.8
                     * @param context_menu the proposed #WebKitContextMenu
                     * @param hit_test_result a #WebKitWebHitTestResult
                     * @returns %TRUE if the proposed `context_menu` has been modified, or %FALSE otherwise.
                     */
                    "context-menu"(context_menu: ContextMenu, hit_test_result: WebHitTestResult): boolean
                    /**
                     * This signal is emitted when the DOM document of a #WebKitWebPage has been
                     * loaded.
                     *
                     * You can wait for this signal to get the DOM document
                     */
                    "document-loaded"(): void
                    /**
                     * This signal is emitted when `request` is about to be sent to
                     * the server. This signal can be used to modify the #WebKitURIRequest
                     * that will be sent to the server. You can also cancel the resource load
                     * operation by connecting to this signal and returning %TRUE.
                     *
                     * In case of a server redirection this signal is
                     * emitted again with the `request` argument containing the new
                     * request to be sent to the server due to the redirection and the
                     *  `redirected_response` parameter containing the response
                     * received by the server for the initial request.
                     *
                     * Modifications to the #WebKitURIRequest and its associated
                     * #SoupMessageHeaders will be taken into account when the request
                     * is sent over the network.
                     * @param request a #WebKitURIRequest
                     * @param redirected_response a #WebKitURIResponse, or %NULL
                     * @returns %TRUE to stop other handlers from being invoked for the event.    %FALSE to continue emission of the event.
                     */
                    "send-request"(request: URIRequest, redirected_response: URIResponse): boolean
                    /**
                     * This signal is emitted when a #WebKitUserMessage is received from the
                     * #WebKitWebView corresponding to `web_page`. You can reply to the message
                     * using webkit_user_message_send_reply().
                     *
                     * You can handle the user message asynchronously by calling g_object_ref() on
                     *  `message` and returning %TRUE. If the last reference of `message` is removed
                     * and the message has been replied, the operation in the #WebKitWebView will
                     * finish with error %WEBKIT_USER_MESSAGE_UNHANDLED_MESSAGE.
                     * @since 2.28
                     * @param message the #WebKitUserMessage received
                     * @returns %TRUE if the message was handled, or %FALSE otherwise.
                     */
                    "user-message-received"(message: UserMessage): boolean
                }

                interface ReadWriteProperties extends GObject.Object.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, GObject.Object.ReadableProperties {
                    "uri": string
                }

                interface WritableProperties extends ReadWriteProperties, GObject.Object.WritableProperties {
                }

                interface ConstructOnlyProperties extends GObject.Object.ConstructOnlyProperties {
                }
            }

            interface WebPage extends GObject.Object {
                readonly $signals: WebPage.SignalSignatures
                readonly $readableProperties: WebPage.ReadableProperties
                readonly $writableProperties: WebPage.WritableProperties
                readonly $constructOnlyProperties: WebPage.ConstructOnlyProperties
                /**
                 * The current active URI of the #WebKitWebPage.
                 * @default NULL
                 */
                get uri(): string
                /**
                 * Gets the #WebKitWebEditor of a #WebKitWebPage.
                 * @since 2.10
                 * @returns the #WebKitWebEditor
                 */
                get_editor(): WebEditor
                /**
                 * Get the #WebKitWebFormManager of `web_page` in `world`.
                 * @since 2.40
                 * @param world a #WebKitScriptWorld
                 * @returns a #WebKitWebFormManager
                 */
                get_form_manager(world: ScriptWorld | null): WebFormManager
                /**
                 * Get the identifier of the #WebKitWebPage
                 * @returns the identifier of `web_page`
                 */
                get_id(): number
                /**
                 * Returns the main frame of a #WebKitWebPage.
                 * @since 2.2
                 * @deprecated since 2.48
                 * @returns the #WebKitFrame that is the main frame of `web_page`
                 */
                get_main_frame(): Frame
                /**
                 * Returns the current active URI of `web_page`.
                 *
                 * You can monitor the active URI by connecting to the notify::uri
                 * signal of `web_page`.
                 * @returns the current active URI of `web_view` or %NULL if nothing has been    loaded yet.
                 */
                get_uri(): string
                /**
                 * Send `message` to the #WebKitWebView corresponding to `web_page`. If `message` is floating, it's consumed.
                 *
                 * If you don't expect any reply, or you simply want to ignore it, you can pass %NULL as `callback`.
                 * When the operation is finished, `callback` will be called. You can then call
                 * webkit_web_page_send_message_to_view_finish() to get the message reply.
                 * @since 2.28
                 * @param message a #WebKitUserMessage
                 * @param cancellable a #GCancellable or %NULL to ignore
                 * @param callback A #GAsyncReadyCallback to call when the request is satisfied or %NULL
                 */
                send_message_to_view(message: UserMessage, cancellable: Gio.Cancellable | null, callback: Gio.AsyncReadyCallback | null): void
                /**
                 * Finish an asynchronous operation started with webkit_web_page_send_message_to_view().
                 * @throws {GLib.Error}
                 * @since 2.28
                 * @param result a #GAsyncResult
                 * @returns a #WebKitUserMessage with the reply or %NULL in case of error.
                 */
                send_message_to_view_finish(result: Gio.AsyncResult): UserMessage
            }

            interface WebPageClass extends Omit<GObject.ObjectClass, "new"> {
                readonly $gtype: GObject.GType<WebPage>
                readonly prototype: WebPage

                new (props?: Partial<GObject.ConstructorProps<WebPage>>): WebPage
            }

            interface $Exports {
                /**
                 * A loaded web page.
                 */
                WebPage: WebPageClass
            }
            

            namespace WebProcessExtension {
                interface SignalSignatures extends GObject.Object.SignalSignatures {
                    /**
                     * This signal is emitted when a new #WebKitWebPage is created in
                     * the Web Process.
                     * @since 2.40
                     * @param web_page the #WebKitWebPage created
                     */
                    "page-created"(web_page: WebPage): void
                    /**
                     * This signal is emitted when a #WebKitUserMessage is received from the
                     * #WebKitWebContext corresponding to `extension`. Messages sent by #WebKitWebContext
                     * are always broadcasted to all web extensions and they can't be
                     * replied to. Calling webkit_user_message_send_reply() will do nothing.
                     * @since 2.40
                     * @param message the #WebKitUserMessage received
                     */
                    "user-message-received"(message: UserMessage): void
                }

                interface ReadWriteProperties extends GObject.Object.ReadWriteProperties {
                }

                interface ReadableProperties extends ReadWriteProperties, GObject.Object.ReadableProperties {
                }

                interface WritableProperties extends ReadWriteProperties, GObject.Object.WritableProperties {
                }

                interface ConstructOnlyProperties extends GObject.Object.ConstructOnlyProperties {
                }
            }

            interface WebProcessExtension extends GObject.Object {
                readonly $signals: WebProcessExtension.SignalSignatures
                readonly $readableProperties: WebProcessExtension.ReadableProperties
                readonly $writableProperties: WebProcessExtension.WritableProperties
                readonly $constructOnlyProperties: WebProcessExtension.ConstructOnlyProperties
                /**
                 * Get the web page of the given `page_id`.
                 * @since 2.40
                 * @param page_id the identifier of the #WebKitWebPage to get
                 * @returns the #WebKitWebPage for the given `page_id`, or %NULL if the    identifier doesn't correspond to an existing web page.
                 */
                get_page(page_id: number): WebPage
                /**
                 * Send `message` to the #WebKitWebContext corresponding to `extension`. If `message` is floating, it's consumed.
                 *
                 * If you don't expect any reply, or you simply want to ignore it, you can pass %NULL as `calback`.
                 * When the operation is finished, `callback` will be called. You can then call
                 * webkit_web_process_extension_send_message_to_context_finish() to get the message reply.
                 * @since 2.40
                 * @param message a #WebKitUserMessage
                 * @param cancellable a #GCancellable or %NULL to ignore
                 * @param callback A #GAsyncReadyCallback to call when the request is satisfied or %NULL
                 */
                send_message_to_context(message: UserMessage, cancellable: Gio.Cancellable | null, callback: Gio.AsyncReadyCallback | null): void
                /**
                 * Finish an asynchronous operation started with webkit_web_process_extension_send_message_to_context().
                 * @throws {GLib.Error}
                 * @since 2.40
                 * @param result a #GAsyncResult
                 * @returns a #WebKitUserMessage with the reply or %NULL in case of error.
                 */
                send_message_to_context_finish(result: Gio.AsyncResult): UserMessage
            }

            interface WebProcessExtensionClass extends Omit<GObject.ObjectClass, "new"> {
                readonly $gtype: GObject.GType<WebProcessExtension>
                readonly prototype: WebProcessExtension

                new (props?: Partial<GObject.ConstructorProps<WebProcessExtension>>): WebProcessExtension
            }

            interface $Exports {
                /**
                 * Represents an extension of the web process.
                 *
                 * WebKitWebProcessExtension is a loadable module for the web process. It allows you to execute code in the
                 * web process and being able to use the DOM API, to change any request or to inject custom
                 * JavaScript code, for example.
                 *
                 * To create a WebKitWebProcessExtension you should write a module with an initialization function that could
                 * be either webkit_web_process_extension_initialize() with prototype #WebKitWebProcessExtensionInitializeFunction or
                 * webkit_web_process_extension_initialize_with_user_data() with prototype #WebKitWebProcessExtensionInitializeWithUserDataFunction.
                 * This function has to be public and it has to use the #G_MODULE_EXPORT macro. It is called when the
                 * web process is initialized.
                 *
                 * ```c
                 * static void
                 * web_page_created_callback (WebKitWebProcessExtension *extension,
                 *                            WebKitWebPage             *web_page,
                 *                            gpointer                   user_data)
                 * {
                 *     g_print ("Page %d created for %s\n",
                 *              webkit_web_page_get_id (web_page),
                 *              webkit_web_page_get_uri (web_page));
                 * }
                 *
                 * G_MODULE_EXPORT void
                 * webkit_web_process_extension_initialize (WebKitWebProcessExtension *extension)
                 * {
                 *     g_signal_connect (extension, "page-created",
                 *                       G_CALLBACK (web_page_created_callback),
                 *                       NULL);
                 * }
                 * ```
                 *
                 * The previous piece of code shows a trivial example of an extension that notifies when
                 * a #WebKitWebPage is created.
                 *
                 * WebKit has to know where it can find the created WebKitWebProcessExtension. To do so you
                 * should use the webkit_web_context_set_web_extensions_directory() function. The signal
                 * #WebKitWebContext::initialize-web-extensions is the recommended place to call it.
                 *
                 * To provide the initialization data used by the webkit_web_process_extension_initialize_with_user_data()
                 * function, you have to call webkit_web_context_set_web_extensions_initialization_user_data() with
                 * the desired data as parameter. You can see an example of this in the following piece of code:
                 *
                 * ```c
                 * #define WEB_EXTENSIONS_DIRECTORY // ...
                 *
                 * static void
                 * initialize_web_extensions (WebKitWebContext *context,
                 *                            gpointer          user_data)
                 * {
                 *   // Web Extensions get a different ID for each Web Process
                 *   static guint32 unique_id = 0;
                 *
                 *   webkit_web_context_set_web_extensions_directory (
                 *      context, WEB_EXTENSIONS_DIRECTORY);
                 *   webkit_web_context_set_web_extensions_initialization_user_data (
                 *      context, g_variant_new_uint32 (unique_id++));
                 * }
                 *
                 * int main (int argc, char **argv)
                 * {
                 *   g_signal_connect (webkit_web_context_get_default (),
                 *                    "initialize-web-extensions",
                 *                     G_CALLBACK (initialize_web_extensions),
                 *                     NULL);
                 *
                 *   GtkWidget *view = webkit_web_view_new ();
                 *
                 *   // ...
                 * }
                 * ```
                 * @since 2.40
                 */
                WebProcessExtension: WebProcessExtensionClass
            }
            

            interface ConsoleMessageStruct {
                readonly $gtype: GObject.GType<ConsoleMessage>
                [Symbol.hasInstance](instance: unknown): instance is ConsoleMessage
            }

            interface ConsoleMessage {
                /**
                 * Make a copy of `console_message`.
                 * @since 2.12
                 * @returns A copy of passed in #WebKitConsoleMessage
                 */
                copy(): ConsoleMessage
                /**
                 * Free the #WebKitConsoleMessage
                 * @since 2.12
                 */
                free(): void
                /**
                 * Gets the log level of a #WebKitConsoleMessage
                 * @since 2.12
                 * @returns a #WebKitConsoleMessageLevel indicating the log level of `console_message`
                 */
                get_level(): ConsoleMessageLevel
                /**
                 * Gets the line number of a #WebKitConsoleMessage
                 * @since 2.12
                 * @returns the line number of `console_message`
                 */
                get_line(): number
                /**
                 * Gets the source of a #WebKitConsoleMessage
                 * @since 2.12
                 * @returns a #WebKitConsoleMessageSource indicating the source of `console_message`
                 */
                get_source(): ConsoleMessageSource
                /**
                 * Gets the source identifier of a #WebKitConsoleMessage
                 * @since 2.12
                 * @returns the source identifier of `console_message`
                 */
                get_source_id(): string
                /**
                 * Gets the text message of a #WebKitConsoleMessage
                 * @since 2.12
                 * @returns the text message of `console_message`
                 */
                get_text(): string
            }

            interface $Exports {
                ConsoleMessage: ConsoleMessageStruct
            }
            
            interface ConsoleMessageLevelEnum {
                readonly $gtype: GObject.GType<ConsoleMessageLevel>
                /**
                 * Information message.
                 */
                readonly "INFO": 0
                /**
                 * Log message.
                 */
                readonly "LOG": 1
                /**
                 * Warning message.
                 */
                readonly "WARNING": 2
                /**
                 * Error message.
                 */
                readonly "ERROR": 3
                /**
                 * Debug message.
                 */
                readonly "DEBUG": 4
            }
            type ConsoleMessageLevel = ConsoleMessageLevelEnum[Exclude<keyof ConsoleMessageLevelEnum, "$gtype">]
            interface $Exports {
                /**
                 * Enum values used to denote the various levels of console messages.
                 * @since 2.12
                 */
                ConsoleMessageLevel: ConsoleMessageLevelEnum
            }
            
            interface ConsoleMessageSourceEnum {
                readonly $gtype: GObject.GType<ConsoleMessageSource>
                /**
                 * Message produced by JavaScript.
                 */
                readonly "JAVASCRIPT": 0
                /**
                 * Network messages.
                 */
                readonly "NETWORK": 1
                /**
                 * Messages produced by console API.
                 */
                readonly "CONSOLE_API": 2
                /**
                 * Security messages.
                 */
                readonly "SECURITY": 3
                /**
                 * Other messages.
                 */
                readonly "OTHER": 4
            }
            type ConsoleMessageSource = ConsoleMessageSourceEnum[Exclude<keyof ConsoleMessageSourceEnum, "$gtype">]
            interface $Exports {
                /**
                 * Enum values used to denote the various sources of console messages.
                 * @since 2.12
                 */
                ConsoleMessageSource: ConsoleMessageSourceEnum
            }
            
            interface ContextMenuActionEnum {
                readonly $gtype: GObject.GType<ContextMenuAction>
                /**
                 * No action, used by separator menu items.
                 */
                readonly "NO_ACTION": 0
                /**
                 * Open current link.
                 */
                readonly "OPEN_LINK": 1
                /**
                 * Open current link in a new window.
                 */
                readonly "OPEN_LINK_IN_NEW_WINDOW": 2
                /**
                 * Download link destination.
                 */
                readonly "DOWNLOAD_LINK_TO_DISK": 3
                /**
                 * Copy link location to the clipboard.
                 */
                readonly "COPY_LINK_TO_CLIPBOARD": 4
                /**
                 * Open current image in a new window.
                 */
                readonly "OPEN_IMAGE_IN_NEW_WINDOW": 5
                /**
                 * Download current image.
                 */
                readonly "DOWNLOAD_IMAGE_TO_DISK": 6
                /**
                 * Copy current image to the clipboard.
                 */
                readonly "COPY_IMAGE_TO_CLIPBOARD": 7
                /**
                 * Copy current image location to the clipboard.
                 */
                readonly "COPY_IMAGE_URL_TO_CLIPBOARD": 8
                /**
                 * Open current frame in a new window.
                 */
                readonly "OPEN_FRAME_IN_NEW_WINDOW": 9
                /**
                 * Load the previous history item.
                 */
                readonly "GO_BACK": 10
                /**
                 * Load the next history item.
                 */
                readonly "GO_FORWARD": 11
                /**
                 * Stop any ongoing loading operation.
                 */
                readonly "STOP": 12
                /**
                 * Reload the contents of current view.
                 */
                readonly "RELOAD": 13
                /**
                 * Copy current selection the clipboard.
                 */
                readonly "COPY": 14
                /**
                 * Cut current selection to the clipboard.
                 */
                readonly "CUT": 15
                /**
                 * Paste clipboard contents.
                 */
                readonly "PASTE": 16
                /**
                 * Delete current selection.
                 */
                readonly "DELETE": 17
                /**
                 * Select all text.
                 */
                readonly "SELECT_ALL": 18
                /**
                 * Input methods menu.
                 */
                readonly "INPUT_METHODS": 19
                /**
                 * Unicode menu.
                 */
                readonly "UNICODE": 20
                /**
                 * A proposed replacement for a misspelled word.
                 */
                readonly "SPELLING_GUESS": 21
                /**
                 * An indicator that spellchecking found no proposed replacements.
                 */
                readonly "NO_GUESSES_FOUND": 22
                /**
                 * Causes the spellchecker to ignore the word for this session.
                 */
                readonly "IGNORE_SPELLING": 23
                /**
                 * Causes the spellchecker to add the word to the dictionary.
                 */
                readonly "LEARN_SPELLING": 24
                /**
                 * Ignore grammar.
                 */
                readonly "IGNORE_GRAMMAR": 25
                /**
                 * Font options menu.
                 */
                readonly "FONT_MENU": 26
                /**
                 * Bold.
                 */
                readonly "BOLD": 27
                /**
                 * Italic.
                 */
                readonly "ITALIC": 28
                /**
                 * Underline.
                 */
                readonly "UNDERLINE": 29
                /**
                 * Outline.
                 */
                readonly "OUTLINE": 30
                /**
                 * Open current element in the inspector.
                 */
                readonly "INSPECT_ELEMENT": 31
                /**
                 * Open current video element in a new window.
                 */
                readonly "OPEN_VIDEO_IN_NEW_WINDOW": 32
                /**
                 * Open current audio element in a new window.
                 */
                readonly "OPEN_AUDIO_IN_NEW_WINDOW": 33
                /**
                 * Copy video link location in to the clipboard.
                 */
                readonly "COPY_VIDEO_LINK_TO_CLIPBOARD": 34
                /**
                 * Copy audio link location in to the clipboard.
                 */
                readonly "COPY_AUDIO_LINK_TO_CLIPBOARD": 35
                /**
                 * Enable or disable media controls.
                 */
                readonly "TOGGLE_MEDIA_CONTROLS": 36
                /**
                 * Enable or disable media loop.
                 */
                readonly "TOGGLE_MEDIA_LOOP": 37
                /**
                 * Show current video element in fullscreen mode.
                 */
                readonly "ENTER_VIDEO_FULLSCREEN": 38
                /**
                 * Play current media element.
                 */
                readonly "MEDIA_PLAY": 39
                /**
                 * Pause current media element.
                 */
                readonly "MEDIA_PAUSE": 40
                /**
                 * Mute current media element.
                 */
                readonly "MEDIA_MUTE": 41
                /**
                 * Download video to disk. Since 2.2
                 */
                readonly "DOWNLOAD_VIDEO_TO_DISK": 42
                /**
                 * Download audio to disk. Since 2.2
                 */
                readonly "DOWNLOAD_AUDIO_TO_DISK": 43
                /**
                 * Insert an emoji. Since 2.26
                 */
                readonly "INSERT_EMOJI": 44
                /**
                 * Paste clipboard contents as plain text. Since 2.30
                 */
                readonly "PASTE_AS_PLAIN_TEXT": 45
                /**
                 * Custom action defined by applications.
                 */
                readonly "CUSTOM": 10000
            }
            type ContextMenuAction = ContextMenuActionEnum[Exclude<keyof ContextMenuActionEnum, "$gtype">]
            interface $Exports {
                /**
                 * Enum values used to denote the stock actions for
                 * #WebKitContextMenuItem<!-- -->s
                 */
                ContextMenuAction: ContextMenuActionEnum
            }
            
            interface UserMessageErrorEnum {
                readonly $gtype: GObject.GType<UserMessageError>
                /**
                 * The message was not handled by the receiver.
                 */
                readonly "USER_MESSAGE_UNHANDLED_MESSAGE": 0
            }
            type UserMessageError = UserMessageErrorEnum[Exclude<keyof UserMessageErrorEnum, "$gtype">]
            interface $Exports {
                /**
                 * Enum values used to denote errors happening when sending user messages.
                 * @since 2.28
                 */
                UserMessageError: UserMessageErrorEnum
            }
            
            interface HitTestResultContextBitfield {
                readonly $gtype: GObject.GType<HitTestResultContext>
                /**
                 * anywhere in the document.
                 */
                readonly "DOCUMENT": 2
                /**
                 * a hyperlink element.
                 */
                readonly "LINK": 4
                /**
                 * an image element.
                 */
                readonly "IMAGE": 8
                /**
                 * a video or audio element.
                 */
                readonly "MEDIA": 16
                /**
                 * an editable element
                 */
                readonly "EDITABLE": 32
                /**
                 * a scrollbar element.
                 */
                readonly "SCROLLBAR": 64
                /**
                 * a selected element. Since 2.8
                 */
                readonly "SELECTION": 128
            }
            type HitTestResultContext = number
            interface $Exports {
                /**
                 * Enum values with flags representing the context of a #WebKitHitTestResult.
                 */
                HitTestResultContext: HitTestResultContextBitfield
            }
            /**
             * Type definition for a function that will be called to initialize
             * the web extension when the web process starts.
             * @since 2.40
             * @param extension a #WebKitWebProcessExtension
             */
            type WebProcessExtensionInitializeFunction = (extension: WebProcessExtension) => void
            /**
             * Type definition for a function that will be called to initialize
             * the web extensions when the web process starts, and which receives
             * as additional argument the user data set with
             * webkit_web_context_set_web_process_extensions_initialization_user_data().
             * @since 2.40
             * @param extension a #WebKitWebProcessExtension
             * @param user_data a #GVariant
             */
            type WebProcessExtensionInitializeWithUserDataFunction = (extension: WebProcessExtension, user_data: GLib.Variant) => void

            interface $Exports {
                __name__: "WebKitWebProcessExtension"
                __version__: "6.0"
            }
        }

        const WebKitWebProcessExtension: WebKitWebProcessExtension.$Exports
    }

    export default GI.WebKitWebProcessExtension
}